# =============================================================================
# Postgres Exporter - Custom Queries
# =============================================================================
#
# Extended queries for postgres_exporter to collect additional metrics
# beyond the default set.
#
# Documentation: https://github.com/prometheus-community/postgres_exporter
#
# =============================================================================

# Query: pg_stat_statements (requires pg_stat_statements extension)
# Provides per-query statistics
pg_stat_statements:
  query: |
    SELECT
      queryid,
      calls,
      total_exec_time,
      mean_exec_time,
      stddev_exec_time,
      rows
    FROM pg_stat_statements
    WHERE queryid IS NOT NULL
    ORDER BY total_exec_time DESC
    LIMIT 100
  master: true
  cache_seconds: 30
  metrics:
    - queryid:
        usage: "LABEL"
        description: "Query ID"
    - calls:
        usage: "COUNTER"
        description: "Number of times executed"
    - total_exec_time:
        usage: "COUNTER"
        description: "Total time spent executing query (ms)"
    - mean_exec_time:
        usage: "GAUGE"
        description: "Mean execution time (ms)"
    - stddev_exec_time:
        usage: "GAUGE"
        description: "Standard deviation of execution time (ms)"
    - rows:
        usage: "COUNTER"
        description: "Total rows retrieved or affected"

# Query: Table bloat estimation
# Estimates table bloat (dead tuples)
pg_bloat_tables:
  query: |
    SELECT
      schemaname,
      tablename,
      pg_total_relation_size(schemaname||'.'||tablename)::bigint as total_bytes,
      pg_relation_size(schemaname||'.'||tablename)::bigint as table_bytes,
      (pg_total_relation_size(schemaname||'.'||tablename) - pg_relation_size(schemaname||'.'||tablename))::bigint as index_bytes
    FROM pg_tables
    WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
    ORDER BY pg_total_relation_size(schemaname||'.'||tablename) DESC
    LIMIT 50
  master: true
  cache_seconds: 300
  metrics:
    - schemaname:
        usage: "LABEL"
        description: "Schema name"
    - tablename:
        usage: "LABEL"
        description: "Table name"
    - total_bytes:
        usage: "GAUGE"
        description: "Total size of table (including indexes)"
    - table_bytes:
        usage: "GAUGE"
        description: "Size of table data"
    - index_bytes:
        usage: "GAUGE"
        description: "Size of indexes"

# Query: Replication lag (for standby servers)
# Only works on standby databases
pg_replication_lag:
  query: |
    SELECT
      COALESCE(EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())), 0) as lag_seconds
    WHERE pg_is_in_recovery()
  master: false
  cache_seconds: 10
  metrics:
    - lag_seconds:
        usage: "GAUGE"
        description: "Replication lag in seconds"

# Query: Long running queries
pg_long_running_queries:
  query: |
    SELECT
      COUNT(*) FILTER (WHERE state = 'active' AND (now() - query_start) > interval '30 seconds') as active_30s,
      COUNT(*) FILTER (WHERE state = 'active' AND (now() - query_start) > interval '1 minute') as active_1m,
      COUNT(*) FILTER (WHERE state = 'active' AND (now() - query_start) > interval '5 minutes') as active_5m
    FROM pg_stat_activity
    WHERE pid != pg_backend_pid()
  master: true
  cache_seconds: 10
  metrics:
    - active_30s:
        usage: "GAUGE"
        description: "Number of queries running longer than 30 seconds"
    - active_1m:
        usage: "GAUGE"
        description: "Number of queries running longer than 1 minute"
    - active_5m:
        usage: "GAUGE"
        description: "Number of queries running longer than 5 minutes"

# Query: Lock contention by type
pg_locks_by_type:
  query: |
    SELECT
      mode,
      COUNT(*) as count
    FROM pg_locks
    GROUP BY mode
  master: true
  cache_seconds: 10
  metrics:
    - mode:
        usage: "LABEL"
        description: "Lock mode"
    - count:
        usage: "GAUGE"
        description: "Number of locks of this type"

# Query: Connection states
pg_connection_states:
  query: |
    SELECT
      state,
      COUNT(*) as count
    FROM pg_stat_activity
    WHERE pid != pg_backend_pid()
    GROUP BY state
  master: true
  cache_seconds: 10
  metrics:
    - state:
        usage: "LABEL"
        description: "Connection state"
    - count:
        usage: "GAUGE"
        description: "Number of connections in this state"

