export const FIXED_INTENTS_TARGET = 30;

export const FIXED_IDS = {
  ADMIN: 'u_admin_00000000000000000001',
  MODERATOR: 'u_moderator_00000000000000000001',
  USER: 'u_user_00000000000000000001',
  // Users with active plans for testing
  USER_PLUS_MONTHLY: 'u_plus_monthly_000000000001',
  USER_PRO_MONTHLY: 'u_pro_monthly_0000000000001',
  USER_PLUS_YEARLY: 'u_plus_yearly_00000000000001',
  USER_PRO_YEARLY: 'u_pro_yearly_000000000000001',
} as const;

/** ---------- Realistic-ish data pools ---------- */
export const FIRST_NAMES = [
  'Adam',
  'Zuzanna',
  'Michał',
  'Kasia',
  'Bartek',
  'Ola',
  'Piotr',
  'Ania',
  'Tomek',
  'Magda',
  'Krzysztof',
  'Natalia',
  'Paweł',
  'Ewa',
  'Maciek',
  'Agnieszka',
  'Marcin',
  'Karolina',
];
export const LAST_NAMES = [
  'Nowak',
  'Kowalska',
  'Wiśniewski',
  'Wójcik',
  'Kamińska',
  'Lewandowski',
  'Zielińska',
  'Szymański',
  'Dąbrowska',
  'Kozłowski',
  'Jankowska',
  'Mazur',
  'Krawczyk',
  'Piotrowska',
];

/** Cities with rough coords and sample places (for address realism) */
export const CITIES = [
  {
    name: 'Warszawa',
    placeId: 'ChIJm-_nMEbMHkcRgEoyuuNYpa8', // Real Warsaw Place ID
    lat: 52.2297,
    lng: 21.0122,
    places: [
      { name: 'Plac Zbawiciela', placeId: 'ChIJ0fZbavUDFkcRZbawiciela01' },
      { name: 'PGE Narodowy', placeId: 'ChIJs7e8w40DFkcRPGENarodowy01' },
      { name: 'Muzeum POLIN', placeId: 'ChIJB7o3-mADFkcRPolinMuseum01' },
      { name: 'Łazienki Królewskie', placeId: 'ChIJLazienki0001' },
      { name: 'Stare Miasto', placeId: 'ChIJStareMiasto01' },
    ],
  },
  {
    name: 'Kraków',
    placeId: 'ChIJ0RhONcBEFkcRv4pHdrW2a7Q', // Real Krakow Place ID
    lat: 50.0647,
    lng: 19.945,
    places: [
      { name: 'Rynek Główny', placeId: 'ChIJ0T2TeoAFBUcRRynekGlowny01' },
      { name: 'Błonia', placeId: 'ChIJxzE9bR8FBUcRBloniaKrakow01' },
      { name: 'Kazimierz', placeId: 'ChIJBc7n8DkFBUcRKazimierz01' },
      { name: 'Wawel', placeId: 'ChIJWawel0001' },
      { name: 'Nowa Huta', placeId: 'ChIJNowaHuta01' },
    ],
  },
  {
    name: 'Gdańsk',
    placeId: 'ChIJt7qDCNq3_UYRgmz3VJzVB6c', // Real Gdansk Place ID
    lat: 54.352,
    lng: 18.6466,
    places: [
      { name: 'Długi Targ', placeId: 'ChIJQ9jAQxq3_UYRDLugiTarg01' },
      { name: 'Molo Brzeźno', placeId: 'ChIJ-3b8rje3_UYRBrzeznoPier01' },
      { name: 'Park Oliwski', placeId: 'ChIJG2n2mxa3_UYROliwaPark01' },
      { name: 'Stare Miasto', placeId: 'ChIJStareMiastoGdansk01' },
    ],
  },
  {
    name: 'Wrocław',
    placeId: 'ChIJOwEiRqbMD0cRYDvkPv7MJXQ', // Real Wroclaw Place ID
    lat: 51.1079,
    lng: 17.0385,
    places: [
      { name: 'Hala Stulecia', placeId: 'ChIJG9XlgbJED0cRHalaStulecia01' },
      { name: 'Rynek', placeId: 'ChIJkz1c8bNED0cRWroclawRynek01' },
      { name: 'Wyspa Słodowa', placeId: 'ChIJq4xUj7JED0cRWyspaSlodowa01' },
      { name: 'Ostrów Tumski', placeId: 'ChIJOstrowTumski01' },
    ],
  },
  {
    name: 'Poznań',
    placeId: 'ChIJtwrh0GqNG0cRCHwcFl2gIQQ', // Real Poznan Place ID
    lat: 52.4064,
    lng: 16.9252,
    places: [
      { name: 'Stary Rynek', placeId: 'ChIJw8tc1KqNG0cRStaryRynek01' },
      { name: 'Jezioro Malta', placeId: 'ChIJq2l1v6-NG0cRJezioroMalta01' },
      { name: 'Park Cytadela', placeId: 'ChIJ1y5V96GNG0cRCytadelaPark01' },
      { name: 'Stary Browar', placeId: 'ChIJStaryBrowar01' },
    ],
  },
  {
    name: 'Łódź',
    placeId: 'ChIJVxLqvPZYGUcRYJY6_YBbOPo', // Real Lodz Place ID
    lat: 51.7592,
    lng: 19.456,
    places: [
      { name: 'Piotrkowska', placeId: 'ChIJPiotrkowska01' },
      { name: 'Manufaktura', placeId: 'ChIJManufaktura01' },
      { name: 'Park Poniatowskiego', placeId: 'ChIJParkPoniatowskiego01' },
    ],
  },
  {
    name: 'Katowice',
    placeId: 'ChIJY_s8Fa3bD0cRYjz6cHBslKw', // Real Katowice Place ID
    lat: 50.2649,
    lng: 19.0238,
    places: [
      { name: 'Spodek', placeId: 'ChIJSpodek01' },
      { name: 'Strefa Kultury', placeId: 'ChIJStrefaKultury01' },
      { name: 'Park Kościuszki', placeId: 'ChIJParkKosciuszki01' },
    ],
  },
  {
    name: 'Szczecin',
    placeId: 'ChIJvQYmq_xNBUcRgEoyuuNYpa8', // Real Szczecin Place ID
    lat: 53.4285,
    lng: 14.5528,
    places: [
      { name: 'Wały Chrobrego', placeId: 'ChIJWalyChrobrego01' },
      { name: 'Jasne Błonia', placeId: 'ChIJJasneBlonia01' },
      { name: 'Stare Miasto', placeId: 'ChIJStareMiastoSzczecin01' },
    ],
  },
  {
    name: 'Lublin',
    placeId: 'ChIJOwEiRqbMD0cRYDvkPv7MJXR', // Real Lublin Place ID
    lat: 51.2465,
    lng: 22.5684,
    places: [
      { name: 'Stare Miasto', placeId: 'ChIJStareMiastoLublin01' },
      { name: 'Zamek Lubelski', placeId: 'ChIJZamekLubelski01' },
      { name: 'Plac Litewski', placeId: 'ChIJPlacLitewski01' },
    ],
  },
  {
    name: 'Białystok',
    placeId: 'ChIJvQYmq_xNBUcRgEoyuuNYpa9', // Real Bialystok Place ID
    lat: 53.1325,
    lng: 23.1688,
    places: [
      { name: 'Rynek Kościuszki', placeId: 'ChIJRynekKosciuszki01' },
      { name: 'Pałac Branickich', placeId: 'ChIJPalacBranickich01' },
      { name: 'Park Planty', placeId: 'ChIJParkPlanty01' },
    ],
  },
];

export const CATEGORY_DEFS = [
  // Sport & Fitness
  {
    slug: 'running',
    pl: 'Bieganie',
    de: 'Laufen',
    en: 'Running',
    icon: '🏃',
    color: '#ef4444',
  },
  {
    slug: 'cycling',
    pl: 'Kolarstwo',
    de: 'Radfahren',
    en: 'Cycling',
    icon: '🚴',
    color: '#f59e0b',
  },
  {
    slug: 'hiking',
    pl: 'Wędrówki',
    de: 'Wandern',
    en: 'Hiking',
    icon: '🥾',
    color: '#22c55e',
  },
  {
    slug: 'yoga',
    pl: 'Joga',
    de: 'Yoga',
    en: 'Yoga',
    icon: '🧘',
    color: '#a855f7',
  },
  {
    slug: 'swimming',
    pl: 'Pływanie',
    de: 'Schwimmen',
    en: 'Swimming',
    icon: '🏊',
    color: '#0ea5e9',
  },
  {
    slug: 'gym',
    pl: 'Siłownia',
    de: 'Fitnessstudio',
    en: 'Gym',
    icon: '💪',
    color: '#dc2626',
  },
  {
    slug: 'climbing',
    pl: 'Wspinaczka',
    de: 'Klettern',
    en: 'Climbing',
    icon: '🧗',
    color: '#f97316',
  },
  {
    slug: 'tennis',
    pl: 'Tenis',
    de: 'Tennis',
    en: 'Tennis',
    icon: '🎾',
    color: '#84cc16',
  },
  {
    slug: 'football',
    pl: 'Piłka nożna',
    de: 'Fußball',
    en: 'Football',
    icon: '⚽',
    color: '#16a34a',
  },
  {
    slug: 'basketball',
    pl: 'Koszykówka',
    de: 'Basketball',
    en: 'Basketball',
    icon: '🏀',
    color: '#ea580c',
  },
  {
    slug: 'volleyball',
    pl: 'Siatkówka',
    de: 'Volleyball',
    en: 'Volleyball',
    icon: '🏐',
    color: '#0284c7',
  },
  {
    slug: 'martial-arts',
    pl: 'Sztuki walki',
    de: 'Kampfsport',
    en: 'Martial arts',
    icon: '🥋',
    color: '#7c3aed',
  },
  {
    slug: 'dance',
    pl: 'Taniec',
    de: 'Tanzen',
    en: 'Dance',
    icon: '💃',
    color: '#ec4899',
  },
  {
    slug: 'skateboarding',
    pl: 'Skateboarding',
    de: 'Skateboarding',
    en: 'Skateboarding',
    icon: '🛹',
    color: '#64748b',
  },
  {
    slug: 'skiing',
    pl: 'Narciarstwo',
    de: 'Skifahren',
    en: 'Skiing',
    icon: '⛷️',
    color: '#06b6d4',
  },

  // Kultura & Sztuka
  {
    slug: 'reading',
    pl: 'Czytanie',
    de: 'Lesen',
    en: 'Reading',
    icon: '📚',
    color: '#10b981',
  },
  {
    slug: 'photography',
    pl: 'Fotografia',
    de: 'Fotografie',
    en: 'Photography',
    icon: '📷',
    color: '#f97316',
  },
  {
    slug: 'painting',
    pl: 'Malarstwo',
    de: 'Malerei',
    en: 'Painting',
    icon: '🎨',
    color: '#f43f5e',
  },
  {
    slug: 'drawing',
    pl: 'Rysowanie',
    de: 'Zeichnen',
    en: 'Drawing',
    icon: '✏️',
    color: '#8b5cf6',
  },
  {
    slug: 'music',
    pl: 'Muzyka',
    de: 'Musik',
    en: 'Music',
    icon: '🎵',
    color: '#a855f7',
  },
  {
    slug: 'singing',
    pl: 'Śpiewanie',
    de: 'Singen',
    en: 'Singing',
    icon: '🎤',
    color: '#ec4899',
  },
  {
    slug: 'guitar',
    pl: 'Gitara',
    de: 'Gitarre',
    en: 'Guitar',
    icon: '🎸',
    color: '#f59e0b',
  },
  {
    slug: 'piano',
    pl: 'Fortepian',
    de: 'Klavier',
    en: 'Piano',
    icon: '🎹',
    color: '#6366f1',
  },
  {
    slug: 'theater',
    pl: 'Teatr',
    de: 'Theater',
    en: 'Theater',
    icon: '🎭',
    color: '#dc2626',
  },
  {
    slug: 'cinema',
    pl: 'Kino',
    de: 'Kino',
    en: 'Cinema',
    icon: '🎬',
    color: '#1e293b',
  },
  {
    slug: 'writing',
    pl: 'Pisanie',
    de: 'Schreiben',
    en: 'Writing',
    icon: '✍️',
    color: '#0891b2',
  },
  {
    slug: 'poetry',
    pl: 'Poezja',
    de: 'Poesie',
    en: 'Poetry',
    icon: '📝',
    color: '#7c3aed',
  },

  // Technologia & Nauka
  {
    slug: 'coding',
    pl: 'Programowanie',
    de: 'Programmieren',
    en: 'Coding',
    icon: '💻',
    color: '#3b82f6',
  },
  {
    slug: 'ai-ml',
    pl: 'AI & Machine Learning',
    de: 'KI & ML',
    en: 'AI & ML',
    icon: '🤖',
    color: '#6366f1',
  },
  {
    slug: 'web-development',
    pl: 'Tworzenie stron',
    de: 'Webentwicklung',
    en: 'Web development',
    icon: '🌐',
    color: '#0ea5e9',
  },
  {
    slug: 'game-development',
    pl: 'Tworzenie gier',
    de: 'Spieleentwicklung',
    en: 'Game development',
    icon: '🎮',
    color: '#8b5cf6',
  },
  {
    slug: 'robotics',
    pl: 'Robotyka',
    de: 'Robotik',
    en: 'Robotics',
    icon: '🦾',
    color: '#64748b',
  },
  {
    slug: 'electronics',
    pl: 'Elektronika',
    de: 'Elektronik',
    en: 'Electronics',
    icon: '⚡',
    color: '#eab308',
  },
  {
    slug: 'science',
    pl: 'Nauka',
    de: 'Wissenschaft',
    en: 'Science',
    icon: '🔬',
    color: '#06b6d4',
  },
  {
    slug: 'astronomy',
    pl: 'Astronomia',
    de: 'Astronomie',
    en: 'Astronomy',
    icon: '🔭',
    color: '#1e293b',
  },

  // Gry & Rozrywka
  {
    slug: 'boardgames',
    pl: 'Planszówki',
    de: 'Brettspiele',
    en: 'Board games',
    icon: '🎲',
    color: '#8b5cf6',
  },
  {
    slug: 'chess',
    pl: 'Szachy',
    de: 'Schach',
    en: 'Chess',
    icon: '♟️',
    color: '#475569',
  },
  {
    slug: 'video-games',
    pl: 'Gry wideo',
    de: 'Videospiele',
    en: 'Video games',
    icon: '🎮',
    color: '#a855f7',
  },
  {
    slug: 'card-games',
    pl: 'Gry karciane',
    de: 'Kartenspiele',
    en: 'Card games',
    icon: '🃏',
    color: '#dc2626',
  },
  {
    slug: 'rpg',
    pl: 'RPG',
    de: 'Rollenspiele',
    en: 'RPG',
    icon: '🐉',
    color: '#7c3aed',
  },
  {
    slug: 'escape-room',
    pl: 'Escape room',
    de: 'Escape Room',
    en: 'Escape room',
    icon: '🔐',
    color: '#f59e0b',
  },

  // Jedzenie & Napoje
  {
    slug: 'cooking',
    pl: 'Gotowanie',
    de: 'Kochen',
    en: 'Cooking',
    icon: '🍳',
    color: '#84cc16',
  },
  {
    slug: 'baking',
    pl: 'Pieczenie',
    de: 'Backen',
    en: 'Baking',
    icon: '🧁',
    color: '#f472b6',
  },
  {
    slug: 'coffee',
    pl: 'Kawa',
    de: 'Kaffee',
    en: 'Coffee',
    icon: '☕',
    color: '#78350f',
  },
  {
    slug: 'wine-tasting',
    pl: 'Degustacja wina',
    de: 'Weinverkostung',
    en: 'Wine tasting',
    icon: '🍷',
    color: '#991b1b',
  },
  {
    slug: 'beer-tasting',
    pl: 'Degustacja piwa',
    de: 'Bierverkostung',
    en: 'Beer tasting',
    icon: '🍺',
    color: '#f59e0b',
  },
  {
    slug: 'vegan-cooking',
    pl: 'Kuchnia wegańska',
    de: 'Veganes Kochen',
    en: 'Vegan cooking',
    icon: '🥗',
    color: '#16a34a',
  },

  // Języki & Edukacja
  {
    slug: 'language-exchange',
    pl: 'Wymiana językowa',
    de: 'Sprachaustausch',
    en: 'Language exchange',
    icon: '🗣️',
    color: '#06b6d4',
  },
  {
    slug: 'english',
    pl: 'Angielski',
    de: 'Englisch',
    en: 'English',
    icon: '🇬🇧',
    color: '#dc2626',
  },
  {
    slug: 'spanish',
    pl: 'Hiszpański',
    de: 'Spanisch',
    en: 'Spanish',
    icon: '🇪🇸',
    color: '#eab308',
  },
  {
    slug: 'german',
    pl: 'Niemiecki',
    de: 'Deutsch',
    en: 'German',
    icon: '🇩🇪',
    color: '#1e293b',
  },
  {
    slug: 'french',
    pl: 'Francuski',
    de: 'Französisch',
    en: 'French',
    icon: '🇫🇷',
    color: '#3b82f6',
  },
  {
    slug: 'study-group',
    pl: 'Grupa nauki',
    de: 'Lerngruppe',
    en: 'Study group',
    icon: '📖',
    color: '#0891b2',
  },

  // Biznes & Networking
  {
    slug: 'networking',
    pl: 'Networking',
    de: 'Networking',
    en: 'Networking',
    icon: '🤝',
    color: '#0284c7',
  },
  {
    slug: 'startup',
    pl: 'Startup',
    de: 'Startup',
    en: 'Startup',
    icon: '🚀',
    color: '#7c3aed',
  },
  {
    slug: 'entrepreneurship',
    pl: 'Przedsiębiorczość',
    de: 'Unternehmertum',
    en: 'Entrepreneurship',
    icon: '💼',
    color: '#475569',
  },
  {
    slug: 'investing',
    pl: 'Inwestowanie',
    de: 'Investieren',
    en: 'Investing',
    icon: '📈',
    color: '#16a34a',
  },
  {
    slug: 'marketing',
    pl: 'Marketing',
    de: 'Marketing',
    en: 'Marketing',
    icon: '📢',
    color: '#f59e0b',
  },

  // Przyroda & Zwierzęta
  {
    slug: 'gardening',
    pl: 'Ogrodnictwo',
    de: 'Gartenarbeit',
    en: 'Gardening',
    icon: '🌱',
    color: '#22c55e',
  },
  {
    slug: 'birdwatching',
    pl: 'Obserwacja ptaków',
    de: 'Vogelbeobachtung',
    en: 'Birdwatching',
    icon: '🦜',
    color: '#0ea5e9',
  },
  {
    slug: 'pets',
    pl: 'Zwierzęta',
    de: 'Haustiere',
    en: 'Pets',
    icon: '🐕',
    color: '#f59e0b',
  },
  {
    slug: 'volunteering',
    pl: 'Wolontariat',
    de: 'Freiwilligenarbeit',
    en: 'Volunteering',
    icon: '❤️',
    color: '#dc2626',
  },
  {
    slug: 'ecology',
    pl: 'Ekologia',
    de: 'Ökologie',
    en: 'Ecology',
    icon: '♻️',
    color: '#16a34a',
  },

  // Wellness & Rozwój osobisty
  {
    slug: 'meditation',
    pl: 'Medytacja',
    de: 'Meditation',
    en: 'Meditation',
    icon: '🧘‍♀️',
    color: '#a855f7',
  },
  {
    slug: 'mindfulness',
    pl: 'Uważność',
    de: 'Achtsamkeit',
    en: 'Mindfulness',
    icon: '🕉️',
    color: '#8b5cf6',
  },
  {
    slug: 'personal-development',
    pl: 'Rozwój osobisty',
    de: 'Persönliche Entwicklung',
    en: 'Personal development',
    icon: '🌟',
    color: '#eab308',
  },
  {
    slug: 'psychology',
    pl: 'Psychologia',
    de: 'Psychologie',
    en: 'Psychology',
    icon: '🧠',
    color: '#6366f1',
  },

  // Inne
  {
    slug: 'travel',
    pl: 'Podróże',
    de: 'Reisen',
    en: 'Travel',
    icon: '✈️',
    color: '#0ea5e9',
  },
  {
    slug: 'fashion',
    pl: 'Moda',
    de: 'Mode',
    en: 'Fashion',
    icon: '👗',
    color: '#ec4899',
  },
  {
    slug: 'crafts',
    pl: 'Rękodzieło',
    de: 'Handwerk',
    en: 'Crafts',
    icon: '🧶',
    color: '#f472b6',
  },
  {
    slug: 'diy',
    pl: 'Zrób to sam',
    de: 'Heimwerken',
    en: 'DIY',
    icon: '🔨',
    color: '#f59e0b',
  },
  {
    slug: 'cars',
    pl: 'Samochody',
    de: 'Autos',
    en: 'Cars',
    icon: '🚗',
    color: '#dc2626',
  },
  {
    slug: 'motorcycles',
    pl: 'Motocykle',
    de: 'Motorräder',
    en: 'Motorcycles',
    icon: '🏍️',
    color: '#1e293b',
  },
];

export const TAGS = [
  // Miejsce
  'outdoor',
  'indoor',
  'online',
  'park',
  'cafe',
  'home',
  'gym',
  'studio',
  'library',
  'coworking',
  'beach',
  'forest',
  'mountains',
  'city-center',
  'suburbs',

  // Koszt
  'free',
  'paid',
  'donation',
  'budget-friendly',
  'premium',

  // Intensywność
  'chill',
  'relaxed',
  'moderate',
  'intense',
  'challenging',
  'beginner-friendly',
  'advanced',
  'all-levels',

  // Cel
  'networking',
  'study',
  'learning',
  'practice',
  'competition',
  'fun',
  'social',
  'professional',
  'hobby',
  'skill-building',
  'creative',
  'wellness',
  'fitness',

  // Grupa
  'team',
  'solo',
  'pairs',
  'small-group',
  'large-group',
  'community',
  'club',
  'meetup',

  // Czas
  'morning',
  'afternoon',
  'evening',
  'night',
  'weekend',
  'weekday',
  'flexible',
  'recurring',
  'one-time',
  'series',
  'drop-in',

  // Atmosfera
  'casual',
  'formal',
  'friendly',
  'competitive',
  'collaborative',
  'quiet',
  'energetic',
  'inspiring',

  // Dodatkowe
  'coffee',
  'food',
  'drinks',
  'family',
  'kids-friendly',
  'pet-friendly',
  'lgbtq-friendly',
  'women-only',
  'men-only',
  'seniors',
  'students',
  'expats',
  'locals',
  'international',
  'english-speaking',
  'multilingual',

  // Specjalne
  'workshop',
  'lecture',
  'discussion',
  'hands-on',
  'demo',
  'showcase',
  'exhibition',
  'performance',
  'tournament',
  'hackathon',
  'jam-session',
  'open-mic',
  'potluck',
  'picnic',
  'party',
  'celebration',

  // Sezonowe
  'summer',
  'winter',
  'spring',
  'autumn',
  'seasonal',
  'holiday',

  // Dostępność
  'wheelchair-accessible',
  'public-transport',
  'parking-available',
  'bike-friendly',

  // Wymagania
  'no-experience',
  'bring-your-own',
  'equipment-provided',
  'registration-required',
  'limited-spots',
  'first-come',
];

export const TITLE_BY_CATEGORY: Record<string, string[]> = {
  // Sport & Fitness
  running: [
    'Easy 5k Run',
    'Intervals by the River',
    'Sunday Long Run',
    'Trail Running Adventure',
  ],
  cycling: [
    'City Ride After Work',
    'Gravel Loop',
    'Evening Sprint',
    'Mountain Bike Trail',
  ],
  hiking: ['Forest Trail', 'Sunrise Walk', 'Weekend Hike', 'Peak Challenge'],
  yoga: ['Morning Flow', 'Yin & Restore', 'Sunset Yoga', 'Power Yoga Session'],
  swimming: [
    'Open Water Swim',
    'Pool Training',
    'Aqua Fitness',
    'Swimming Technique',
  ],
  gym: [
    'Strength Training',
    'CrossFit WOD',
    'Bodyweight Basics',
    'Powerlifting Session',
  ],
  climbing: [
    'Bouldering Night',
    'Top Rope Practice',
    'Lead Climbing',
    'Outdoor Climbing Trip',
  ],
  tennis: [
    'Doubles Match',
    'Singles Practice',
    'Tennis Drills',
    'Tournament Prep',
  ],
  football: [
    'Friendly Match',
    'Skills Training',
    '5-a-side Game',
    'Tactics Workshop',
  ],
  basketball: [
    'Pick-up Game',
    'Shooting Practice',
    '3v3 Tournament',
    'Skills & Drills',
  ],
  volleyball: [
    'Beach Volleyball',
    'Indoor Match',
    'Bump Set Spike',
    'Tournament Play',
  ],
  'martial-arts': [
    'Karate Practice',
    'BJJ Rolling',
    'Muay Thai Sparring',
    'Self-Defense Workshop',
  ],
  dance: [
    'Salsa Night',
    'Hip-Hop Class',
    'Contemporary Workshop',
    'Social Dance',
  ],
  skateboarding: [
    'Skatepark Session',
    'Street Skating',
    'Tricks Workshop',
    'Beginner Basics',
  ],
  skiing: [
    'Slope Day',
    'Off-Piste Adventure',
    'Ski Technique',
    'Backcountry Tour',
  ],

  // Kultura & Sztuka
  reading: [
    'Book Club – Chapter 1',
    'Quiet Reading Hour',
    'Discuss & Coffee',
    'Poetry Reading',
  ],
  photography: [
    'Golden Hour Walk',
    'Portraits Basics',
    'Composition in the City',
    'Street Photography',
  ],
  painting: [
    'Watercolor Workshop',
    'Acrylic Painting',
    'Plein Air Session',
    'Abstract Art Night',
  ],
  drawing: ['Life Drawing', 'Sketch Walk', 'Digital Art', 'Character Design'],
  music: [
    'Jam Session',
    'Music Theory',
    'Songwriting Circle',
    'Open Rehearsal',
  ],
  singing: [
    'Choir Practice',
    'Vocal Workshop',
    'Karaoke Night',
    'Harmony Training',
  ],
  guitar: [
    'Acoustic Session',
    'Electric Guitar',
    'Fingerstyle Practice',
    'Song Learning',
  ],
  piano: [
    'Classical Pieces',
    'Jazz Improvisation',
    'Pop Songs',
    'Sight Reading',
  ],
  theater: [
    'Improv Workshop',
    'Scene Study',
    'Monologue Practice',
    'Theater Games',
  ],
  cinema: [
    'Film Screening',
    'Director Discussion',
    'Short Films Night',
    'Cinema Club',
  ],
  writing: [
    'Creative Writing',
    'Journaling Circle',
    'Story Workshop',
    'Writing Prompts',
  ],
  poetry: ['Poetry Slam', 'Verse Workshop', 'Open Mic Poetry', 'Haiku Session'],

  // Technologia & Nauka
  coding: [
    'Hack Night',
    'Open Source Sprint',
    'Pair Programming',
    'Code Review Session',
  ],
  'ai-ml': [
    'ML Model Training',
    'AI Ethics Discussion',
    'Neural Networks',
    'Data Science Meetup',
  ],
  'web-development': [
    'Frontend Workshop',
    'Backend API',
    'Full Stack Project',
    'React Study Group',
  ],
  'game-development': [
    'Game Jam',
    'Unity Workshop',
    'Pixel Art',
    'Game Design Discussion',
  ],
  robotics: [
    'Robot Building',
    'Arduino Projects',
    'Automation Workshop',
    'Robotics Competition',
  ],
  electronics: [
    'Circuit Design',
    'Soldering Workshop',
    'IoT Projects',
    'Electronics Basics',
  ],
  science: [
    'Science Cafe',
    'Experiment Night',
    'Research Discussion',
    'Lab Tour',
  ],
  astronomy: [
    'Star Gazing',
    'Telescope Night',
    'Astrophotography',
    'Planetarium Visit',
  ],

  // Gry & Rozrywka
  boardgames: [
    'Strategy Night',
    'Party Games',
    'Eurogames Evening',
    'Co-op Campaign',
  ],
  chess: [
    'Chess Tournament',
    'Blitz Games',
    'Tactics Training',
    'Endgame Study',
  ],
  'video-games': ['LAN Party', 'Tournament', 'Co-op Campaign', 'Retro Gaming'],
  'card-games': [
    'Poker Night',
    'Magic: The Gathering',
    'Bridge Club',
    'Card Tricks',
  ],
  rpg: [
    'D&D Campaign',
    'One-Shot Adventure',
    'Character Creation',
    'World Building',
  ],
  'escape-room': [
    'Mystery Room',
    'Team Challenge',
    'Horror Escape',
    'Puzzle Solving',
  ],

  // Jedzenie & Napoje
  cooking: [
    'Pasta Workshop',
    'Street Food Night',
    'Spices 101',
    'Knife Skills',
  ],
  baking: [
    'Sourdough Bread',
    'Pastry Class',
    'Cake Decorating',
    'Cookie Baking',
  ],
  coffee: ['Latte Art', 'Coffee Tasting', 'Brewing Methods', 'Espresso Basics'],
  'wine-tasting': [
    'Wine & Cheese',
    'Vineyard Tour',
    'Sommelier Session',
    'Wine Pairing',
  ],
  'beer-tasting': [
    'Craft Beer Night',
    'Brewery Tour',
    'Beer Styles',
    'Homebrewing',
  ],
  'vegan-cooking': [
    'Plant-Based Meals',
    'Vegan Baking',
    'Protein Sources',
    'Meal Prep',
  ],

  // Języki & Edukacja
  'language-exchange': [
    'EN–PL Swap',
    'Deutsch Stammtisch',
    'Casual Language Chat',
    'Polyglot Meetup',
  ],
  english: [
    'Conversation Club',
    'Grammar Workshop',
    'Business English',
    'Pronunciation Practice',
  ],
  spanish: ['Spanish Tapas', 'Conversación', 'Grammar Basics', 'Culture Night'],
  german: [
    'Deutsch Cafe',
    'Grammar Practice',
    'Conversation Hour',
    'German Culture',
  ],
  french: [
    'French Cafe',
    'Conversation',
    'Pronunciation',
    'Culture Discussion',
  ],
  'study-group': [
    'Exam Prep',
    'Group Study',
    'Homework Help',
    'Learning Together',
  ],

  // Biznes & Networking
  networking: [
    'Professional Mixer',
    'Industry Meetup',
    'Coffee Networking',
    'Speed Networking',
  ],
  startup: [
    'Pitch Night',
    'Founder Meetup',
    'Startup Weekend',
    'Product Launch',
  ],
  entrepreneurship: [
    'Business Ideas',
    'Founder Stories',
    'Growth Strategies',
    'Pitch Practice',
  ],
  investing: [
    'Stock Market',
    'Crypto Discussion',
    'Real Estate',
    'Investment Club',
  ],
  marketing: [
    'Digital Marketing',
    'Content Strategy',
    'Social Media',
    'Brand Building',
  ],

  // Przyroda & Zwierzęta
  gardening: [
    'Community Garden',
    'Plant Swap',
    'Composting Workshop',
    'Urban Farming',
  ],
  birdwatching: [
    'Morning Birding',
    'Species ID',
    'Migration Watch',
    'Bird Photography',
  ],
  pets: ['Dog Walk', 'Pet Meetup', 'Training Tips', 'Pet Care Workshop'],
  volunteering: [
    'Community Service',
    'Beach Cleanup',
    'Food Bank',
    'Animal Shelter',
  ],
  ecology: [
    'Zero Waste',
    'Sustainability Talk',
    'Nature Conservation',
    'Eco Workshop',
  ],

  // Wellness & Rozwój osobisty
  meditation: [
    'Guided Meditation',
    'Mindfulness Practice',
    'Breathing Techniques',
    'Silent Meditation',
  ],
  mindfulness: [
    'Present Moment',
    'Body Scan',
    'Walking Meditation',
    'Mindful Eating',
  ],
  'personal-development': [
    'Goal Setting',
    'Habit Building',
    'Life Coaching',
    'Self-Improvement',
  ],
  psychology: [
    'Psychology Talk',
    'Mental Health',
    'Behavior Patterns',
    'Therapy Discussion',
  ],

  // Inne
  travel: [
    'Travel Stories',
    'Trip Planning',
    'Budget Travel',
    'Adventure Tales',
  ],
  fashion: [
    'Style Workshop',
    'Fashion Show',
    'Sustainable Fashion',
    'Wardrobe Refresh',
  ],
  crafts: [
    'Knitting Circle',
    'Jewelry Making',
    'Origami Workshop',
    'Craft Night',
  ],
  diy: ['Home Projects', 'Furniture Upcycle', 'Tool Workshop', 'DIY Basics'],
  cars: ['Car Meetup', 'Maintenance Workshop', 'Road Trip', 'Classic Cars'],
  motorcycles: [
    'Group Ride',
    'Bike Maintenance',
    'Safety Course',
    'Motorcycle Meetup',
  ],
};
