
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `EventSponsorshipPeriod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model EventSponsorshipPeriod
 * Tracks individual event sponsorship purchases (new, reload, upgrade)
 * Similar to UserPlanPeriod but for event sponsorships
 */
export type EventSponsorshipPeriodModel = runtime.Types.Result.DefaultSelection<Prisma.$EventSponsorshipPeriodPayload>

export type AggregateEventSponsorshipPeriod = {
  _count: EventSponsorshipPeriodCountAggregateOutputType | null
  _avg: EventSponsorshipPeriodAvgAggregateOutputType | null
  _sum: EventSponsorshipPeriodSumAggregateOutputType | null
  _min: EventSponsorshipPeriodMinAggregateOutputType | null
  _max: EventSponsorshipPeriodMaxAggregateOutputType | null
}

export type EventSponsorshipPeriodAvgAggregateOutputType = {
  boostsAdded: number | null
  localPushesAdded: number | null
  amount: number | null
}

export type EventSponsorshipPeriodSumAggregateOutputType = {
  boostsAdded: number | null
  localPushesAdded: number | null
  amount: number | null
}

export type EventSponsorshipPeriodMinAggregateOutputType = {
  id: string | null
  eventId: string | null
  sponsorId: string | null
  plan: $Enums.EventPlan | null
  actionType: string | null
  boostsAdded: number | null
  localPushesAdded: number | null
  amount: number | null
  currency: string | null
  stripeCustomerId: string | null
  stripePaymentEventId: string | null
  stripeCheckoutSessionId: string | null
  createdAt: Date | null
}

export type EventSponsorshipPeriodMaxAggregateOutputType = {
  id: string | null
  eventId: string | null
  sponsorId: string | null
  plan: $Enums.EventPlan | null
  actionType: string | null
  boostsAdded: number | null
  localPushesAdded: number | null
  amount: number | null
  currency: string | null
  stripeCustomerId: string | null
  stripePaymentEventId: string | null
  stripeCheckoutSessionId: string | null
  createdAt: Date | null
}

export type EventSponsorshipPeriodCountAggregateOutputType = {
  id: number
  eventId: number
  sponsorId: number
  plan: number
  actionType: number
  boostsAdded: number
  localPushesAdded: number
  amount: number
  currency: number
  stripeCustomerId: number
  stripePaymentEventId: number
  stripeCheckoutSessionId: number
  createdAt: number
  _all: number
}


export type EventSponsorshipPeriodAvgAggregateInputType = {
  boostsAdded?: true
  localPushesAdded?: true
  amount?: true
}

export type EventSponsorshipPeriodSumAggregateInputType = {
  boostsAdded?: true
  localPushesAdded?: true
  amount?: true
}

export type EventSponsorshipPeriodMinAggregateInputType = {
  id?: true
  eventId?: true
  sponsorId?: true
  plan?: true
  actionType?: true
  boostsAdded?: true
  localPushesAdded?: true
  amount?: true
  currency?: true
  stripeCustomerId?: true
  stripePaymentEventId?: true
  stripeCheckoutSessionId?: true
  createdAt?: true
}

export type EventSponsorshipPeriodMaxAggregateInputType = {
  id?: true
  eventId?: true
  sponsorId?: true
  plan?: true
  actionType?: true
  boostsAdded?: true
  localPushesAdded?: true
  amount?: true
  currency?: true
  stripeCustomerId?: true
  stripePaymentEventId?: true
  stripeCheckoutSessionId?: true
  createdAt?: true
}

export type EventSponsorshipPeriodCountAggregateInputType = {
  id?: true
  eventId?: true
  sponsorId?: true
  plan?: true
  actionType?: true
  boostsAdded?: true
  localPushesAdded?: true
  amount?: true
  currency?: true
  stripeCustomerId?: true
  stripePaymentEventId?: true
  stripeCheckoutSessionId?: true
  createdAt?: true
  _all?: true
}

export type EventSponsorshipPeriodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventSponsorshipPeriod to aggregate.
   */
  where?: Prisma.EventSponsorshipPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventSponsorshipPeriods to fetch.
   */
  orderBy?: Prisma.EventSponsorshipPeriodOrderByWithRelationInput | Prisma.EventSponsorshipPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventSponsorshipPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventSponsorshipPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventSponsorshipPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventSponsorshipPeriods
  **/
  _count?: true | EventSponsorshipPeriodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EventSponsorshipPeriodAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EventSponsorshipPeriodSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventSponsorshipPeriodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventSponsorshipPeriodMaxAggregateInputType
}

export type GetEventSponsorshipPeriodAggregateType<T extends EventSponsorshipPeriodAggregateArgs> = {
      [P in keyof T & keyof AggregateEventSponsorshipPeriod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventSponsorshipPeriod[P]>
    : Prisma.GetScalarType<T[P], AggregateEventSponsorshipPeriod[P]>
}




export type EventSponsorshipPeriodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventSponsorshipPeriodWhereInput
  orderBy?: Prisma.EventSponsorshipPeriodOrderByWithAggregationInput | Prisma.EventSponsorshipPeriodOrderByWithAggregationInput[]
  by: Prisma.EventSponsorshipPeriodScalarFieldEnum[] | Prisma.EventSponsorshipPeriodScalarFieldEnum
  having?: Prisma.EventSponsorshipPeriodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventSponsorshipPeriodCountAggregateInputType | true
  _avg?: EventSponsorshipPeriodAvgAggregateInputType
  _sum?: EventSponsorshipPeriodSumAggregateInputType
  _min?: EventSponsorshipPeriodMinAggregateInputType
  _max?: EventSponsorshipPeriodMaxAggregateInputType
}

export type EventSponsorshipPeriodGroupByOutputType = {
  id: string
  eventId: string
  sponsorId: string
  plan: $Enums.EventPlan
  actionType: string
  boostsAdded: number
  localPushesAdded: number
  amount: number
  currency: string
  stripeCustomerId: string | null
  stripePaymentEventId: string | null
  stripeCheckoutSessionId: string | null
  createdAt: Date
  _count: EventSponsorshipPeriodCountAggregateOutputType | null
  _avg: EventSponsorshipPeriodAvgAggregateOutputType | null
  _sum: EventSponsorshipPeriodSumAggregateOutputType | null
  _min: EventSponsorshipPeriodMinAggregateOutputType | null
  _max: EventSponsorshipPeriodMaxAggregateOutputType | null
}

type GetEventSponsorshipPeriodGroupByPayload<T extends EventSponsorshipPeriodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventSponsorshipPeriodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventSponsorshipPeriodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventSponsorshipPeriodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventSponsorshipPeriodGroupByOutputType[P]>
      }
    >
  >



export type EventSponsorshipPeriodWhereInput = {
  AND?: Prisma.EventSponsorshipPeriodWhereInput | Prisma.EventSponsorshipPeriodWhereInput[]
  OR?: Prisma.EventSponsorshipPeriodWhereInput[]
  NOT?: Prisma.EventSponsorshipPeriodWhereInput | Prisma.EventSponsorshipPeriodWhereInput[]
  id?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  eventId?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  sponsorId?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  plan?: Prisma.EnumEventPlanFilter<"EventSponsorshipPeriod"> | $Enums.EventPlan
  actionType?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  boostsAdded?: Prisma.IntFilter<"EventSponsorshipPeriod"> | number
  localPushesAdded?: Prisma.IntFilter<"EventSponsorshipPeriod"> | number
  amount?: Prisma.FloatFilter<"EventSponsorshipPeriod"> | number
  currency?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  stripeCustomerId?: Prisma.StringNullableFilter<"EventSponsorshipPeriod"> | string | null
  stripePaymentEventId?: Prisma.StringNullableFilter<"EventSponsorshipPeriod"> | string | null
  stripeCheckoutSessionId?: Prisma.StringNullableFilter<"EventSponsorshipPeriod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventSponsorshipPeriod"> | Date | string
  eventSponsorship?: Prisma.XOR<Prisma.EventSponsorshipScalarRelationFilter, Prisma.EventSponsorshipWhereInput>
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  sponsor?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type EventSponsorshipPeriodOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  sponsorId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  actionType?: Prisma.SortOrder
  boostsAdded?: Prisma.SortOrder
  localPushesAdded?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripePaymentEventId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeCheckoutSessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  eventSponsorship?: Prisma.EventSponsorshipOrderByWithRelationInput
  event?: Prisma.EventOrderByWithRelationInput
  sponsor?: Prisma.UserOrderByWithRelationInput
}

export type EventSponsorshipPeriodWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EventSponsorshipPeriodWhereInput | Prisma.EventSponsorshipPeriodWhereInput[]
  OR?: Prisma.EventSponsorshipPeriodWhereInput[]
  NOT?: Prisma.EventSponsorshipPeriodWhereInput | Prisma.EventSponsorshipPeriodWhereInput[]
  eventId?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  sponsorId?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  plan?: Prisma.EnumEventPlanFilter<"EventSponsorshipPeriod"> | $Enums.EventPlan
  actionType?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  boostsAdded?: Prisma.IntFilter<"EventSponsorshipPeriod"> | number
  localPushesAdded?: Prisma.IntFilter<"EventSponsorshipPeriod"> | number
  amount?: Prisma.FloatFilter<"EventSponsorshipPeriod"> | number
  currency?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  stripeCustomerId?: Prisma.StringNullableFilter<"EventSponsorshipPeriod"> | string | null
  stripePaymentEventId?: Prisma.StringNullableFilter<"EventSponsorshipPeriod"> | string | null
  stripeCheckoutSessionId?: Prisma.StringNullableFilter<"EventSponsorshipPeriod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventSponsorshipPeriod"> | Date | string
  eventSponsorship?: Prisma.XOR<Prisma.EventSponsorshipScalarRelationFilter, Prisma.EventSponsorshipWhereInput>
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  sponsor?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type EventSponsorshipPeriodOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  sponsorId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  actionType?: Prisma.SortOrder
  boostsAdded?: Prisma.SortOrder
  localPushesAdded?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripePaymentEventId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeCheckoutSessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.EventSponsorshipPeriodCountOrderByAggregateInput
  _avg?: Prisma.EventSponsorshipPeriodAvgOrderByAggregateInput
  _max?: Prisma.EventSponsorshipPeriodMaxOrderByAggregateInput
  _min?: Prisma.EventSponsorshipPeriodMinOrderByAggregateInput
  _sum?: Prisma.EventSponsorshipPeriodSumOrderByAggregateInput
}

export type EventSponsorshipPeriodScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventSponsorshipPeriodScalarWhereWithAggregatesInput | Prisma.EventSponsorshipPeriodScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventSponsorshipPeriodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventSponsorshipPeriodScalarWhereWithAggregatesInput | Prisma.EventSponsorshipPeriodScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EventSponsorshipPeriod"> | string
  eventId?: Prisma.StringWithAggregatesFilter<"EventSponsorshipPeriod"> | string
  sponsorId?: Prisma.StringWithAggregatesFilter<"EventSponsorshipPeriod"> | string
  plan?: Prisma.EnumEventPlanWithAggregatesFilter<"EventSponsorshipPeriod"> | $Enums.EventPlan
  actionType?: Prisma.StringWithAggregatesFilter<"EventSponsorshipPeriod"> | string
  boostsAdded?: Prisma.IntWithAggregatesFilter<"EventSponsorshipPeriod"> | number
  localPushesAdded?: Prisma.IntWithAggregatesFilter<"EventSponsorshipPeriod"> | number
  amount?: Prisma.FloatWithAggregatesFilter<"EventSponsorshipPeriod"> | number
  currency?: Prisma.StringWithAggregatesFilter<"EventSponsorshipPeriod"> | string
  stripeCustomerId?: Prisma.StringNullableWithAggregatesFilter<"EventSponsorshipPeriod"> | string | null
  stripePaymentEventId?: Prisma.StringNullableWithAggregatesFilter<"EventSponsorshipPeriod"> | string | null
  stripeCheckoutSessionId?: Prisma.StringNullableWithAggregatesFilter<"EventSponsorshipPeriod"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventSponsorshipPeriod"> | Date | string
}

export type EventSponsorshipPeriodCreateInput = {
  id?: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
  eventSponsorship: Prisma.EventSponsorshipCreateNestedOneWithoutPeriodsInput
  event: Prisma.EventCreateNestedOneWithoutSponsorshipPeriodsInput
  sponsor: Prisma.UserCreateNestedOneWithoutEventSponsorshipPeriodsInput
}

export type EventSponsorshipPeriodUncheckedCreateInput = {
  id?: string
  eventId: string
  sponsorId: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
}

export type EventSponsorshipPeriodUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventSponsorship?: Prisma.EventSponsorshipUpdateOneRequiredWithoutPeriodsNestedInput
  event?: Prisma.EventUpdateOneRequiredWithoutSponsorshipPeriodsNestedInput
  sponsor?: Prisma.UserUpdateOneRequiredWithoutEventSponsorshipPeriodsNestedInput
}

export type EventSponsorshipPeriodUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  sponsorId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventSponsorshipPeriodCreateManyInput = {
  id?: string
  eventId: string
  sponsorId: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
}

export type EventSponsorshipPeriodUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventSponsorshipPeriodUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  sponsorId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventSponsorshipPeriodListRelationFilter = {
  every?: Prisma.EventSponsorshipPeriodWhereInput
  some?: Prisma.EventSponsorshipPeriodWhereInput
  none?: Prisma.EventSponsorshipPeriodWhereInput
}

export type EventSponsorshipPeriodOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EventSponsorshipPeriodCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  sponsorId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  actionType?: Prisma.SortOrder
  boostsAdded?: Prisma.SortOrder
  localPushesAdded?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrder
  stripePaymentEventId?: Prisma.SortOrder
  stripeCheckoutSessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EventSponsorshipPeriodAvgOrderByAggregateInput = {
  boostsAdded?: Prisma.SortOrder
  localPushesAdded?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type EventSponsorshipPeriodMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  sponsorId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  actionType?: Prisma.SortOrder
  boostsAdded?: Prisma.SortOrder
  localPushesAdded?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrder
  stripePaymentEventId?: Prisma.SortOrder
  stripeCheckoutSessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EventSponsorshipPeriodMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  sponsorId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  actionType?: Prisma.SortOrder
  boostsAdded?: Prisma.SortOrder
  localPushesAdded?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrder
  stripePaymentEventId?: Prisma.SortOrder
  stripeCheckoutSessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EventSponsorshipPeriodSumOrderByAggregateInput = {
  boostsAdded?: Prisma.SortOrder
  localPushesAdded?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type EventSponsorshipPeriodCreateNestedManyWithoutSponsorInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutSponsorInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutSponsorInput> | Prisma.EventSponsorshipPeriodCreateWithoutSponsorInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutSponsorInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutSponsorInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutSponsorInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManySponsorInputEnvelope
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
}

export type EventSponsorshipPeriodUncheckedCreateNestedManyWithoutSponsorInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutSponsorInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutSponsorInput> | Prisma.EventSponsorshipPeriodCreateWithoutSponsorInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutSponsorInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutSponsorInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutSponsorInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManySponsorInputEnvelope
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
}

export type EventSponsorshipPeriodUpdateManyWithoutSponsorNestedInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutSponsorInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutSponsorInput> | Prisma.EventSponsorshipPeriodCreateWithoutSponsorInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutSponsorInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutSponsorInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutSponsorInput[]
  upsert?: Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutSponsorInput | Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutSponsorInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManySponsorInputEnvelope
  set?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  disconnect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  delete?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  update?: Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutSponsorInput | Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutSponsorInput[]
  updateMany?: Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutSponsorInput | Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutSponsorInput[]
  deleteMany?: Prisma.EventSponsorshipPeriodScalarWhereInput | Prisma.EventSponsorshipPeriodScalarWhereInput[]
}

export type EventSponsorshipPeriodUncheckedUpdateManyWithoutSponsorNestedInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutSponsorInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutSponsorInput> | Prisma.EventSponsorshipPeriodCreateWithoutSponsorInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutSponsorInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutSponsorInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutSponsorInput[]
  upsert?: Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutSponsorInput | Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutSponsorInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManySponsorInputEnvelope
  set?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  disconnect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  delete?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  update?: Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutSponsorInput | Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutSponsorInput[]
  updateMany?: Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutSponsorInput | Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutSponsorInput[]
  deleteMany?: Prisma.EventSponsorshipPeriodScalarWhereInput | Prisma.EventSponsorshipPeriodScalarWhereInput[]
}

export type EventSponsorshipPeriodCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventInput> | Prisma.EventSponsorshipPeriodCreateWithoutEventInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManyEventInputEnvelope
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
}

export type EventSponsorshipPeriodUncheckedCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventInput> | Prisma.EventSponsorshipPeriodCreateWithoutEventInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManyEventInputEnvelope
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
}

export type EventSponsorshipPeriodUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventInput> | Prisma.EventSponsorshipPeriodCreateWithoutEventInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutEventInput | Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManyEventInputEnvelope
  set?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  disconnect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  delete?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  update?: Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutEventInput | Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutEventInput | Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventSponsorshipPeriodScalarWhereInput | Prisma.EventSponsorshipPeriodScalarWhereInput[]
}

export type EventSponsorshipPeriodUncheckedUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventInput> | Prisma.EventSponsorshipPeriodCreateWithoutEventInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutEventInput | Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManyEventInputEnvelope
  set?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  disconnect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  delete?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  update?: Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutEventInput | Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutEventInput | Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventSponsorshipPeriodScalarWhereInput | Prisma.EventSponsorshipPeriodScalarWhereInput[]
}

export type EventSponsorshipPeriodCreateNestedManyWithoutEventSponsorshipInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventSponsorshipInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventSponsorshipInput> | Prisma.EventSponsorshipPeriodCreateWithoutEventSponsorshipInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventSponsorshipInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventSponsorshipInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventSponsorshipInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManyEventSponsorshipInputEnvelope
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
}

export type EventSponsorshipPeriodUncheckedCreateNestedManyWithoutEventSponsorshipInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventSponsorshipInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventSponsorshipInput> | Prisma.EventSponsorshipPeriodCreateWithoutEventSponsorshipInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventSponsorshipInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventSponsorshipInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventSponsorshipInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManyEventSponsorshipInputEnvelope
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
}

export type EventSponsorshipPeriodUpdateManyWithoutEventSponsorshipNestedInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventSponsorshipInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventSponsorshipInput> | Prisma.EventSponsorshipPeriodCreateWithoutEventSponsorshipInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventSponsorshipInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventSponsorshipInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventSponsorshipInput[]
  upsert?: Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutEventSponsorshipInput | Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutEventSponsorshipInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManyEventSponsorshipInputEnvelope
  set?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  disconnect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  delete?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  update?: Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutEventSponsorshipInput | Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutEventSponsorshipInput[]
  updateMany?: Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutEventSponsorshipInput | Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutEventSponsorshipInput[]
  deleteMany?: Prisma.EventSponsorshipPeriodScalarWhereInput | Prisma.EventSponsorshipPeriodScalarWhereInput[]
}

export type EventSponsorshipPeriodUncheckedUpdateManyWithoutEventSponsorshipNestedInput = {
  create?: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventSponsorshipInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventSponsorshipInput> | Prisma.EventSponsorshipPeriodCreateWithoutEventSponsorshipInput[] | Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventSponsorshipInput[]
  connectOrCreate?: Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventSponsorshipInput | Prisma.EventSponsorshipPeriodCreateOrConnectWithoutEventSponsorshipInput[]
  upsert?: Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutEventSponsorshipInput | Prisma.EventSponsorshipPeriodUpsertWithWhereUniqueWithoutEventSponsorshipInput[]
  createMany?: Prisma.EventSponsorshipPeriodCreateManyEventSponsorshipInputEnvelope
  set?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  disconnect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  delete?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  connect?: Prisma.EventSponsorshipPeriodWhereUniqueInput | Prisma.EventSponsorshipPeriodWhereUniqueInput[]
  update?: Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutEventSponsorshipInput | Prisma.EventSponsorshipPeriodUpdateWithWhereUniqueWithoutEventSponsorshipInput[]
  updateMany?: Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutEventSponsorshipInput | Prisma.EventSponsorshipPeriodUpdateManyWithWhereWithoutEventSponsorshipInput[]
  deleteMany?: Prisma.EventSponsorshipPeriodScalarWhereInput | Prisma.EventSponsorshipPeriodScalarWhereInput[]
}

export type EventSponsorshipPeriodCreateWithoutSponsorInput = {
  id?: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
  eventSponsorship: Prisma.EventSponsorshipCreateNestedOneWithoutPeriodsInput
  event: Prisma.EventCreateNestedOneWithoutSponsorshipPeriodsInput
}

export type EventSponsorshipPeriodUncheckedCreateWithoutSponsorInput = {
  id?: string
  eventId: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
}

export type EventSponsorshipPeriodCreateOrConnectWithoutSponsorInput = {
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
  create: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutSponsorInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutSponsorInput>
}

export type EventSponsorshipPeriodCreateManySponsorInputEnvelope = {
  data: Prisma.EventSponsorshipPeriodCreateManySponsorInput | Prisma.EventSponsorshipPeriodCreateManySponsorInput[]
  skipDuplicates?: boolean
}

export type EventSponsorshipPeriodUpsertWithWhereUniqueWithoutSponsorInput = {
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
  update: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateWithoutSponsorInput, Prisma.EventSponsorshipPeriodUncheckedUpdateWithoutSponsorInput>
  create: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutSponsorInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutSponsorInput>
}

export type EventSponsorshipPeriodUpdateWithWhereUniqueWithoutSponsorInput = {
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
  data: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateWithoutSponsorInput, Prisma.EventSponsorshipPeriodUncheckedUpdateWithoutSponsorInput>
}

export type EventSponsorshipPeriodUpdateManyWithWhereWithoutSponsorInput = {
  where: Prisma.EventSponsorshipPeriodScalarWhereInput
  data: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateManyMutationInput, Prisma.EventSponsorshipPeriodUncheckedUpdateManyWithoutSponsorInput>
}

export type EventSponsorshipPeriodScalarWhereInput = {
  AND?: Prisma.EventSponsorshipPeriodScalarWhereInput | Prisma.EventSponsorshipPeriodScalarWhereInput[]
  OR?: Prisma.EventSponsorshipPeriodScalarWhereInput[]
  NOT?: Prisma.EventSponsorshipPeriodScalarWhereInput | Prisma.EventSponsorshipPeriodScalarWhereInput[]
  id?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  eventId?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  sponsorId?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  plan?: Prisma.EnumEventPlanFilter<"EventSponsorshipPeriod"> | $Enums.EventPlan
  actionType?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  boostsAdded?: Prisma.IntFilter<"EventSponsorshipPeriod"> | number
  localPushesAdded?: Prisma.IntFilter<"EventSponsorshipPeriod"> | number
  amount?: Prisma.FloatFilter<"EventSponsorshipPeriod"> | number
  currency?: Prisma.StringFilter<"EventSponsorshipPeriod"> | string
  stripeCustomerId?: Prisma.StringNullableFilter<"EventSponsorshipPeriod"> | string | null
  stripePaymentEventId?: Prisma.StringNullableFilter<"EventSponsorshipPeriod"> | string | null
  stripeCheckoutSessionId?: Prisma.StringNullableFilter<"EventSponsorshipPeriod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventSponsorshipPeriod"> | Date | string
}

export type EventSponsorshipPeriodCreateWithoutEventInput = {
  id?: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
  eventSponsorship: Prisma.EventSponsorshipCreateNestedOneWithoutPeriodsInput
  sponsor: Prisma.UserCreateNestedOneWithoutEventSponsorshipPeriodsInput
}

export type EventSponsorshipPeriodUncheckedCreateWithoutEventInput = {
  id?: string
  sponsorId: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
}

export type EventSponsorshipPeriodCreateOrConnectWithoutEventInput = {
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
  create: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventInput>
}

export type EventSponsorshipPeriodCreateManyEventInputEnvelope = {
  data: Prisma.EventSponsorshipPeriodCreateManyEventInput | Prisma.EventSponsorshipPeriodCreateManyEventInput[]
  skipDuplicates?: boolean
}

export type EventSponsorshipPeriodUpsertWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
  update: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateWithoutEventInput, Prisma.EventSponsorshipPeriodUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventInput>
}

export type EventSponsorshipPeriodUpdateWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
  data: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateWithoutEventInput, Prisma.EventSponsorshipPeriodUncheckedUpdateWithoutEventInput>
}

export type EventSponsorshipPeriodUpdateManyWithWhereWithoutEventInput = {
  where: Prisma.EventSponsorshipPeriodScalarWhereInput
  data: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateManyMutationInput, Prisma.EventSponsorshipPeriodUncheckedUpdateManyWithoutEventInput>
}

export type EventSponsorshipPeriodCreateWithoutEventSponsorshipInput = {
  id?: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutSponsorshipPeriodsInput
  sponsor: Prisma.UserCreateNestedOneWithoutEventSponsorshipPeriodsInput
}

export type EventSponsorshipPeriodUncheckedCreateWithoutEventSponsorshipInput = {
  id?: string
  sponsorId: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
}

export type EventSponsorshipPeriodCreateOrConnectWithoutEventSponsorshipInput = {
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
  create: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventSponsorshipInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventSponsorshipInput>
}

export type EventSponsorshipPeriodCreateManyEventSponsorshipInputEnvelope = {
  data: Prisma.EventSponsorshipPeriodCreateManyEventSponsorshipInput | Prisma.EventSponsorshipPeriodCreateManyEventSponsorshipInput[]
  skipDuplicates?: boolean
}

export type EventSponsorshipPeriodUpsertWithWhereUniqueWithoutEventSponsorshipInput = {
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
  update: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateWithoutEventSponsorshipInput, Prisma.EventSponsorshipPeriodUncheckedUpdateWithoutEventSponsorshipInput>
  create: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateWithoutEventSponsorshipInput, Prisma.EventSponsorshipPeriodUncheckedCreateWithoutEventSponsorshipInput>
}

export type EventSponsorshipPeriodUpdateWithWhereUniqueWithoutEventSponsorshipInput = {
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
  data: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateWithoutEventSponsorshipInput, Prisma.EventSponsorshipPeriodUncheckedUpdateWithoutEventSponsorshipInput>
}

export type EventSponsorshipPeriodUpdateManyWithWhereWithoutEventSponsorshipInput = {
  where: Prisma.EventSponsorshipPeriodScalarWhereInput
  data: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateManyMutationInput, Prisma.EventSponsorshipPeriodUncheckedUpdateManyWithoutEventSponsorshipInput>
}

export type EventSponsorshipPeriodCreateManySponsorInput = {
  id?: string
  eventId: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
}

export type EventSponsorshipPeriodUpdateWithoutSponsorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventSponsorship?: Prisma.EventSponsorshipUpdateOneRequiredWithoutPeriodsNestedInput
  event?: Prisma.EventUpdateOneRequiredWithoutSponsorshipPeriodsNestedInput
}

export type EventSponsorshipPeriodUncheckedUpdateWithoutSponsorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventSponsorshipPeriodUncheckedUpdateManyWithoutSponsorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventSponsorshipPeriodCreateManyEventInput = {
  id?: string
  sponsorId: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
}

export type EventSponsorshipPeriodUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventSponsorship?: Prisma.EventSponsorshipUpdateOneRequiredWithoutPeriodsNestedInput
  sponsor?: Prisma.UserUpdateOneRequiredWithoutEventSponsorshipPeriodsNestedInput
}

export type EventSponsorshipPeriodUncheckedUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sponsorId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventSponsorshipPeriodUncheckedUpdateManyWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sponsorId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventSponsorshipPeriodCreateManyEventSponsorshipInput = {
  id?: string
  sponsorId: string
  plan: $Enums.EventPlan
  actionType?: string
  boostsAdded?: number
  localPushesAdded?: number
  amount: number
  currency?: string
  stripeCustomerId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  createdAt?: Date | string
}

export type EventSponsorshipPeriodUpdateWithoutEventSponsorshipInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutSponsorshipPeriodsNestedInput
  sponsor?: Prisma.UserUpdateOneRequiredWithoutEventSponsorshipPeriodsNestedInput
}

export type EventSponsorshipPeriodUncheckedUpdateWithoutEventSponsorshipInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sponsorId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventSponsorshipPeriodUncheckedUpdateManyWithoutEventSponsorshipInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sponsorId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumEventPlanFieldUpdateOperationsInput | $Enums.EventPlan
  actionType?: Prisma.StringFieldUpdateOperationsInput | string
  boostsAdded?: Prisma.IntFieldUpdateOperationsInput | number
  localPushesAdded?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type EventSponsorshipPeriodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  sponsorId?: boolean
  plan?: boolean
  actionType?: boolean
  boostsAdded?: boolean
  localPushesAdded?: boolean
  amount?: boolean
  currency?: boolean
  stripeCustomerId?: boolean
  stripePaymentEventId?: boolean
  stripeCheckoutSessionId?: boolean
  createdAt?: boolean
  eventSponsorship?: boolean | Prisma.EventSponsorshipDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  sponsor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventSponsorshipPeriod"]>

export type EventSponsorshipPeriodSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  sponsorId?: boolean
  plan?: boolean
  actionType?: boolean
  boostsAdded?: boolean
  localPushesAdded?: boolean
  amount?: boolean
  currency?: boolean
  stripeCustomerId?: boolean
  stripePaymentEventId?: boolean
  stripeCheckoutSessionId?: boolean
  createdAt?: boolean
  eventSponsorship?: boolean | Prisma.EventSponsorshipDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  sponsor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventSponsorshipPeriod"]>

export type EventSponsorshipPeriodSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  sponsorId?: boolean
  plan?: boolean
  actionType?: boolean
  boostsAdded?: boolean
  localPushesAdded?: boolean
  amount?: boolean
  currency?: boolean
  stripeCustomerId?: boolean
  stripePaymentEventId?: boolean
  stripeCheckoutSessionId?: boolean
  createdAt?: boolean
  eventSponsorship?: boolean | Prisma.EventSponsorshipDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  sponsor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventSponsorshipPeriod"]>

export type EventSponsorshipPeriodSelectScalar = {
  id?: boolean
  eventId?: boolean
  sponsorId?: boolean
  plan?: boolean
  actionType?: boolean
  boostsAdded?: boolean
  localPushesAdded?: boolean
  amount?: boolean
  currency?: boolean
  stripeCustomerId?: boolean
  stripePaymentEventId?: boolean
  stripeCheckoutSessionId?: boolean
  createdAt?: boolean
}

export type EventSponsorshipPeriodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "eventId" | "sponsorId" | "plan" | "actionType" | "boostsAdded" | "localPushesAdded" | "amount" | "currency" | "stripeCustomerId" | "stripePaymentEventId" | "stripeCheckoutSessionId" | "createdAt", ExtArgs["result"]["eventSponsorshipPeriod"]>
export type EventSponsorshipPeriodInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eventSponsorship?: boolean | Prisma.EventSponsorshipDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  sponsor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type EventSponsorshipPeriodIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eventSponsorship?: boolean | Prisma.EventSponsorshipDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  sponsor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type EventSponsorshipPeriodIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eventSponsorship?: boolean | Prisma.EventSponsorshipDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  sponsor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $EventSponsorshipPeriodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventSponsorshipPeriod"
  objects: {
    eventSponsorship: Prisma.$EventSponsorshipPayload<ExtArgs>
    event: Prisma.$EventPayload<ExtArgs>
    sponsor: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    eventId: string
    sponsorId: string
    plan: $Enums.EventPlan
    actionType: string
    boostsAdded: number
    localPushesAdded: number
    amount: number
    currency: string
    stripeCustomerId: string | null
    stripePaymentEventId: string | null
    stripeCheckoutSessionId: string | null
    createdAt: Date
  }, ExtArgs["result"]["eventSponsorshipPeriod"]>
  composites: {}
}

export type EventSponsorshipPeriodGetPayload<S extends boolean | null | undefined | EventSponsorshipPeriodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload, S>

export type EventSponsorshipPeriodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventSponsorshipPeriodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventSponsorshipPeriodCountAggregateInputType | true
  }

export interface EventSponsorshipPeriodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventSponsorshipPeriod'], meta: { name: 'EventSponsorshipPeriod' } }
  /**
   * Find zero or one EventSponsorshipPeriod that matches the filter.
   * @param {EventSponsorshipPeriodFindUniqueArgs} args - Arguments to find a EventSponsorshipPeriod
   * @example
   * // Get one EventSponsorshipPeriod
   * const eventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventSponsorshipPeriodFindUniqueArgs>(args: Prisma.SelectSubset<T, EventSponsorshipPeriodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventSponsorshipPeriodClient<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventSponsorshipPeriod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventSponsorshipPeriodFindUniqueOrThrowArgs} args - Arguments to find a EventSponsorshipPeriod
   * @example
   * // Get one EventSponsorshipPeriod
   * const eventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventSponsorshipPeriodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventSponsorshipPeriodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventSponsorshipPeriodClient<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventSponsorshipPeriod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSponsorshipPeriodFindFirstArgs} args - Arguments to find a EventSponsorshipPeriod
   * @example
   * // Get one EventSponsorshipPeriod
   * const eventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventSponsorshipPeriodFindFirstArgs>(args?: Prisma.SelectSubset<T, EventSponsorshipPeriodFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventSponsorshipPeriodClient<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventSponsorshipPeriod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSponsorshipPeriodFindFirstOrThrowArgs} args - Arguments to find a EventSponsorshipPeriod
   * @example
   * // Get one EventSponsorshipPeriod
   * const eventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventSponsorshipPeriodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventSponsorshipPeriodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventSponsorshipPeriodClient<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventSponsorshipPeriods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSponsorshipPeriodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventSponsorshipPeriods
   * const eventSponsorshipPeriods = await prisma.eventSponsorshipPeriod.findMany()
   * 
   * // Get first 10 EventSponsorshipPeriods
   * const eventSponsorshipPeriods = await prisma.eventSponsorshipPeriod.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventSponsorshipPeriodWithIdOnly = await prisma.eventSponsorshipPeriod.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventSponsorshipPeriodFindManyArgs>(args?: Prisma.SelectSubset<T, EventSponsorshipPeriodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventSponsorshipPeriod.
   * @param {EventSponsorshipPeriodCreateArgs} args - Arguments to create a EventSponsorshipPeriod.
   * @example
   * // Create one EventSponsorshipPeriod
   * const EventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.create({
   *   data: {
   *     // ... data to create a EventSponsorshipPeriod
   *   }
   * })
   * 
   */
  create<T extends EventSponsorshipPeriodCreateArgs>(args: Prisma.SelectSubset<T, EventSponsorshipPeriodCreateArgs<ExtArgs>>): Prisma.Prisma__EventSponsorshipPeriodClient<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventSponsorshipPeriods.
   * @param {EventSponsorshipPeriodCreateManyArgs} args - Arguments to create many EventSponsorshipPeriods.
   * @example
   * // Create many EventSponsorshipPeriods
   * const eventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventSponsorshipPeriodCreateManyArgs>(args?: Prisma.SelectSubset<T, EventSponsorshipPeriodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventSponsorshipPeriods and returns the data saved in the database.
   * @param {EventSponsorshipPeriodCreateManyAndReturnArgs} args - Arguments to create many EventSponsorshipPeriods.
   * @example
   * // Create many EventSponsorshipPeriods
   * const eventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventSponsorshipPeriods and only return the `id`
   * const eventSponsorshipPeriodWithIdOnly = await prisma.eventSponsorshipPeriod.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventSponsorshipPeriodCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventSponsorshipPeriodCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventSponsorshipPeriod.
   * @param {EventSponsorshipPeriodDeleteArgs} args - Arguments to delete one EventSponsorshipPeriod.
   * @example
   * // Delete one EventSponsorshipPeriod
   * const EventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.delete({
   *   where: {
   *     // ... filter to delete one EventSponsorshipPeriod
   *   }
   * })
   * 
   */
  delete<T extends EventSponsorshipPeriodDeleteArgs>(args: Prisma.SelectSubset<T, EventSponsorshipPeriodDeleteArgs<ExtArgs>>): Prisma.Prisma__EventSponsorshipPeriodClient<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventSponsorshipPeriod.
   * @param {EventSponsorshipPeriodUpdateArgs} args - Arguments to update one EventSponsorshipPeriod.
   * @example
   * // Update one EventSponsorshipPeriod
   * const eventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventSponsorshipPeriodUpdateArgs>(args: Prisma.SelectSubset<T, EventSponsorshipPeriodUpdateArgs<ExtArgs>>): Prisma.Prisma__EventSponsorshipPeriodClient<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventSponsorshipPeriods.
   * @param {EventSponsorshipPeriodDeleteManyArgs} args - Arguments to filter EventSponsorshipPeriods to delete.
   * @example
   * // Delete a few EventSponsorshipPeriods
   * const { count } = await prisma.eventSponsorshipPeriod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventSponsorshipPeriodDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventSponsorshipPeriodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventSponsorshipPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSponsorshipPeriodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventSponsorshipPeriods
   * const eventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventSponsorshipPeriodUpdateManyArgs>(args: Prisma.SelectSubset<T, EventSponsorshipPeriodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventSponsorshipPeriods and returns the data updated in the database.
   * @param {EventSponsorshipPeriodUpdateManyAndReturnArgs} args - Arguments to update many EventSponsorshipPeriods.
   * @example
   * // Update many EventSponsorshipPeriods
   * const eventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventSponsorshipPeriods and only return the `id`
   * const eventSponsorshipPeriodWithIdOnly = await prisma.eventSponsorshipPeriod.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventSponsorshipPeriodUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventSponsorshipPeriodUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventSponsorshipPeriod.
   * @param {EventSponsorshipPeriodUpsertArgs} args - Arguments to update or create a EventSponsorshipPeriod.
   * @example
   * // Update or create a EventSponsorshipPeriod
   * const eventSponsorshipPeriod = await prisma.eventSponsorshipPeriod.upsert({
   *   create: {
   *     // ... data to create a EventSponsorshipPeriod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventSponsorshipPeriod we want to update
   *   }
   * })
   */
  upsert<T extends EventSponsorshipPeriodUpsertArgs>(args: Prisma.SelectSubset<T, EventSponsorshipPeriodUpsertArgs<ExtArgs>>): Prisma.Prisma__EventSponsorshipPeriodClient<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPeriodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventSponsorshipPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSponsorshipPeriodCountArgs} args - Arguments to filter EventSponsorshipPeriods to count.
   * @example
   * // Count the number of EventSponsorshipPeriods
   * const count = await prisma.eventSponsorshipPeriod.count({
   *   where: {
   *     // ... the filter for the EventSponsorshipPeriods we want to count
   *   }
   * })
  **/
  count<T extends EventSponsorshipPeriodCountArgs>(
    args?: Prisma.Subset<T, EventSponsorshipPeriodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventSponsorshipPeriodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventSponsorshipPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSponsorshipPeriodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventSponsorshipPeriodAggregateArgs>(args: Prisma.Subset<T, EventSponsorshipPeriodAggregateArgs>): Prisma.PrismaPromise<GetEventSponsorshipPeriodAggregateType<T>>

  /**
   * Group by EventSponsorshipPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSponsorshipPeriodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventSponsorshipPeriodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventSponsorshipPeriodGroupByArgs['orderBy'] }
      : { orderBy?: EventSponsorshipPeriodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventSponsorshipPeriodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventSponsorshipPeriodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventSponsorshipPeriod model
 */
readonly fields: EventSponsorshipPeriodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventSponsorshipPeriod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventSponsorshipPeriodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  eventSponsorship<T extends Prisma.EventSponsorshipDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventSponsorshipDefaultArgs<ExtArgs>>): Prisma.Prisma__EventSponsorshipClient<runtime.Types.Result.GetResult<Prisma.$EventSponsorshipPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  event<T extends Prisma.EventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDefaultArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  sponsor<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventSponsorshipPeriod model
 */
export interface EventSponsorshipPeriodFieldRefs {
  readonly id: Prisma.FieldRef<"EventSponsorshipPeriod", 'String'>
  readonly eventId: Prisma.FieldRef<"EventSponsorshipPeriod", 'String'>
  readonly sponsorId: Prisma.FieldRef<"EventSponsorshipPeriod", 'String'>
  readonly plan: Prisma.FieldRef<"EventSponsorshipPeriod", 'EventPlan'>
  readonly actionType: Prisma.FieldRef<"EventSponsorshipPeriod", 'String'>
  readonly boostsAdded: Prisma.FieldRef<"EventSponsorshipPeriod", 'Int'>
  readonly localPushesAdded: Prisma.FieldRef<"EventSponsorshipPeriod", 'Int'>
  readonly amount: Prisma.FieldRef<"EventSponsorshipPeriod", 'Float'>
  readonly currency: Prisma.FieldRef<"EventSponsorshipPeriod", 'String'>
  readonly stripeCustomerId: Prisma.FieldRef<"EventSponsorshipPeriod", 'String'>
  readonly stripePaymentEventId: Prisma.FieldRef<"EventSponsorshipPeriod", 'String'>
  readonly stripeCheckoutSessionId: Prisma.FieldRef<"EventSponsorshipPeriod", 'String'>
  readonly createdAt: Prisma.FieldRef<"EventSponsorshipPeriod", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EventSponsorshipPeriod findUnique
 */
export type EventSponsorshipPeriodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodInclude<ExtArgs> | null
  /**
   * Filter, which EventSponsorshipPeriod to fetch.
   */
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
}

/**
 * EventSponsorshipPeriod findUniqueOrThrow
 */
export type EventSponsorshipPeriodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodInclude<ExtArgs> | null
  /**
   * Filter, which EventSponsorshipPeriod to fetch.
   */
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
}

/**
 * EventSponsorshipPeriod findFirst
 */
export type EventSponsorshipPeriodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodInclude<ExtArgs> | null
  /**
   * Filter, which EventSponsorshipPeriod to fetch.
   */
  where?: Prisma.EventSponsorshipPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventSponsorshipPeriods to fetch.
   */
  orderBy?: Prisma.EventSponsorshipPeriodOrderByWithRelationInput | Prisma.EventSponsorshipPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventSponsorshipPeriods.
   */
  cursor?: Prisma.EventSponsorshipPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventSponsorshipPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventSponsorshipPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventSponsorshipPeriods.
   */
  distinct?: Prisma.EventSponsorshipPeriodScalarFieldEnum | Prisma.EventSponsorshipPeriodScalarFieldEnum[]
}

/**
 * EventSponsorshipPeriod findFirstOrThrow
 */
export type EventSponsorshipPeriodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodInclude<ExtArgs> | null
  /**
   * Filter, which EventSponsorshipPeriod to fetch.
   */
  where?: Prisma.EventSponsorshipPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventSponsorshipPeriods to fetch.
   */
  orderBy?: Prisma.EventSponsorshipPeriodOrderByWithRelationInput | Prisma.EventSponsorshipPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventSponsorshipPeriods.
   */
  cursor?: Prisma.EventSponsorshipPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventSponsorshipPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventSponsorshipPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventSponsorshipPeriods.
   */
  distinct?: Prisma.EventSponsorshipPeriodScalarFieldEnum | Prisma.EventSponsorshipPeriodScalarFieldEnum[]
}

/**
 * EventSponsorshipPeriod findMany
 */
export type EventSponsorshipPeriodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodInclude<ExtArgs> | null
  /**
   * Filter, which EventSponsorshipPeriods to fetch.
   */
  where?: Prisma.EventSponsorshipPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventSponsorshipPeriods to fetch.
   */
  orderBy?: Prisma.EventSponsorshipPeriodOrderByWithRelationInput | Prisma.EventSponsorshipPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventSponsorshipPeriods.
   */
  cursor?: Prisma.EventSponsorshipPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventSponsorshipPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventSponsorshipPeriods.
   */
  skip?: number
  distinct?: Prisma.EventSponsorshipPeriodScalarFieldEnum | Prisma.EventSponsorshipPeriodScalarFieldEnum[]
}

/**
 * EventSponsorshipPeriod create
 */
export type EventSponsorshipPeriodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodInclude<ExtArgs> | null
  /**
   * The data needed to create a EventSponsorshipPeriod.
   */
  data: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateInput, Prisma.EventSponsorshipPeriodUncheckedCreateInput>
}

/**
 * EventSponsorshipPeriod createMany
 */
export type EventSponsorshipPeriodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventSponsorshipPeriods.
   */
  data: Prisma.EventSponsorshipPeriodCreateManyInput | Prisma.EventSponsorshipPeriodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EventSponsorshipPeriod createManyAndReturn
 */
export type EventSponsorshipPeriodCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * The data used to create many EventSponsorshipPeriods.
   */
  data: Prisma.EventSponsorshipPeriodCreateManyInput | Prisma.EventSponsorshipPeriodCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EventSponsorshipPeriod update
 */
export type EventSponsorshipPeriodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodInclude<ExtArgs> | null
  /**
   * The data needed to update a EventSponsorshipPeriod.
   */
  data: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateInput, Prisma.EventSponsorshipPeriodUncheckedUpdateInput>
  /**
   * Choose, which EventSponsorshipPeriod to update.
   */
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
}

/**
 * EventSponsorshipPeriod updateMany
 */
export type EventSponsorshipPeriodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventSponsorshipPeriods.
   */
  data: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateManyMutationInput, Prisma.EventSponsorshipPeriodUncheckedUpdateManyInput>
  /**
   * Filter which EventSponsorshipPeriods to update
   */
  where?: Prisma.EventSponsorshipPeriodWhereInput
  /**
   * Limit how many EventSponsorshipPeriods to update.
   */
  limit?: number
}

/**
 * EventSponsorshipPeriod updateManyAndReturn
 */
export type EventSponsorshipPeriodUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * The data used to update EventSponsorshipPeriods.
   */
  data: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateManyMutationInput, Prisma.EventSponsorshipPeriodUncheckedUpdateManyInput>
  /**
   * Filter which EventSponsorshipPeriods to update
   */
  where?: Prisma.EventSponsorshipPeriodWhereInput
  /**
   * Limit how many EventSponsorshipPeriods to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EventSponsorshipPeriod upsert
 */
export type EventSponsorshipPeriodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodInclude<ExtArgs> | null
  /**
   * The filter to search for the EventSponsorshipPeriod to update in case it exists.
   */
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
  /**
   * In case the EventSponsorshipPeriod found by the `where` argument doesn't exist, create a new EventSponsorshipPeriod with this data.
   */
  create: Prisma.XOR<Prisma.EventSponsorshipPeriodCreateInput, Prisma.EventSponsorshipPeriodUncheckedCreateInput>
  /**
   * In case the EventSponsorshipPeriod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventSponsorshipPeriodUpdateInput, Prisma.EventSponsorshipPeriodUncheckedUpdateInput>
}

/**
 * EventSponsorshipPeriod delete
 */
export type EventSponsorshipPeriodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodInclude<ExtArgs> | null
  /**
   * Filter which EventSponsorshipPeriod to delete.
   */
  where: Prisma.EventSponsorshipPeriodWhereUniqueInput
}

/**
 * EventSponsorshipPeriod deleteMany
 */
export type EventSponsorshipPeriodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventSponsorshipPeriods to delete
   */
  where?: Prisma.EventSponsorshipPeriodWhereInput
  /**
   * Limit how many EventSponsorshipPeriods to delete.
   */
  limit?: number
}

/**
 * EventSponsorshipPeriod without action
 */
export type EventSponsorshipPeriodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSponsorshipPeriod
   */
  select?: Prisma.EventSponsorshipPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSponsorshipPeriod
   */
  omit?: Prisma.EventSponsorshipPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSponsorshipPeriodInclude<ExtArgs> | null
}
