
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EventChatMessage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EventChatMessage
 * 
 */
export type EventChatMessageModel = runtime.Types.Result.DefaultSelection<Prisma.$EventChatMessagePayload>

export type AggregateEventChatMessage = {
  _count: EventChatMessageCountAggregateOutputType | null
  _min: EventChatMessageMinAggregateOutputType | null
  _max: EventChatMessageMaxAggregateOutputType | null
}

export type EventChatMessageMinAggregateOutputType = {
  id: string | null
  eventId: string | null
  authorId: string | null
  content: string | null
  replyToId: string | null
  createdAt: Date | null
  editedAt: Date | null
  deletedAt: Date | null
}

export type EventChatMessageMaxAggregateOutputType = {
  id: string | null
  eventId: string | null
  authorId: string | null
  content: string | null
  replyToId: string | null
  createdAt: Date | null
  editedAt: Date | null
  deletedAt: Date | null
}

export type EventChatMessageCountAggregateOutputType = {
  id: number
  eventId: number
  authorId: number
  content: number
  replyToId: number
  createdAt: number
  editedAt: number
  deletedAt: number
  _all: number
}


export type EventChatMessageMinAggregateInputType = {
  id?: true
  eventId?: true
  authorId?: true
  content?: true
  replyToId?: true
  createdAt?: true
  editedAt?: true
  deletedAt?: true
}

export type EventChatMessageMaxAggregateInputType = {
  id?: true
  eventId?: true
  authorId?: true
  content?: true
  replyToId?: true
  createdAt?: true
  editedAt?: true
  deletedAt?: true
}

export type EventChatMessageCountAggregateInputType = {
  id?: true
  eventId?: true
  authorId?: true
  content?: true
  replyToId?: true
  createdAt?: true
  editedAt?: true
  deletedAt?: true
  _all?: true
}

export type EventChatMessageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventChatMessage to aggregate.
   */
  where?: Prisma.EventChatMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventChatMessages to fetch.
   */
  orderBy?: Prisma.EventChatMessageOrderByWithRelationInput | Prisma.EventChatMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventChatMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventChatMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventChatMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventChatMessages
  **/
  _count?: true | EventChatMessageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventChatMessageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventChatMessageMaxAggregateInputType
}

export type GetEventChatMessageAggregateType<T extends EventChatMessageAggregateArgs> = {
      [P in keyof T & keyof AggregateEventChatMessage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventChatMessage[P]>
    : Prisma.GetScalarType<T[P], AggregateEventChatMessage[P]>
}




export type EventChatMessageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventChatMessageWhereInput
  orderBy?: Prisma.EventChatMessageOrderByWithAggregationInput | Prisma.EventChatMessageOrderByWithAggregationInput[]
  by: Prisma.EventChatMessageScalarFieldEnum[] | Prisma.EventChatMessageScalarFieldEnum
  having?: Prisma.EventChatMessageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventChatMessageCountAggregateInputType | true
  _min?: EventChatMessageMinAggregateInputType
  _max?: EventChatMessageMaxAggregateInputType
}

export type EventChatMessageGroupByOutputType = {
  id: string
  eventId: string
  authorId: string
  content: string
  replyToId: string | null
  createdAt: Date
  editedAt: Date | null
  deletedAt: Date | null
  _count: EventChatMessageCountAggregateOutputType | null
  _min: EventChatMessageMinAggregateOutputType | null
  _max: EventChatMessageMaxAggregateOutputType | null
}

type GetEventChatMessageGroupByPayload<T extends EventChatMessageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventChatMessageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventChatMessageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventChatMessageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventChatMessageGroupByOutputType[P]>
      }
    >
  >



export type EventChatMessageWhereInput = {
  AND?: Prisma.EventChatMessageWhereInput | Prisma.EventChatMessageWhereInput[]
  OR?: Prisma.EventChatMessageWhereInput[]
  NOT?: Prisma.EventChatMessageWhereInput | Prisma.EventChatMessageWhereInput[]
  id?: Prisma.StringFilter<"EventChatMessage"> | string
  eventId?: Prisma.StringFilter<"EventChatMessage"> | string
  authorId?: Prisma.StringFilter<"EventChatMessage"> | string
  content?: Prisma.StringFilter<"EventChatMessage"> | string
  replyToId?: Prisma.StringNullableFilter<"EventChatMessage"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventChatMessage"> | Date | string
  editedAt?: Prisma.DateTimeNullableFilter<"EventChatMessage"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"EventChatMessage"> | Date | string | null
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  reactions?: Prisma.EventChatMessageReactionListRelationFilter
  replyTo?: Prisma.XOR<Prisma.EventChatMessageNullableScalarRelationFilter, Prisma.EventChatMessageWhereInput> | null
  replies?: Prisma.EventChatMessageListRelationFilter
}

export type EventChatMessageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  replyToId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  editedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  event?: Prisma.EventOrderByWithRelationInput
  author?: Prisma.UserOrderByWithRelationInput
  reactions?: Prisma.EventChatMessageReactionOrderByRelationAggregateInput
  replyTo?: Prisma.EventChatMessageOrderByWithRelationInput
  replies?: Prisma.EventChatMessageOrderByRelationAggregateInput
}

export type EventChatMessageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EventChatMessageWhereInput | Prisma.EventChatMessageWhereInput[]
  OR?: Prisma.EventChatMessageWhereInput[]
  NOT?: Prisma.EventChatMessageWhereInput | Prisma.EventChatMessageWhereInput[]
  eventId?: Prisma.StringFilter<"EventChatMessage"> | string
  authorId?: Prisma.StringFilter<"EventChatMessage"> | string
  content?: Prisma.StringFilter<"EventChatMessage"> | string
  replyToId?: Prisma.StringNullableFilter<"EventChatMessage"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventChatMessage"> | Date | string
  editedAt?: Prisma.DateTimeNullableFilter<"EventChatMessage"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"EventChatMessage"> | Date | string | null
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  reactions?: Prisma.EventChatMessageReactionListRelationFilter
  replyTo?: Prisma.XOR<Prisma.EventChatMessageNullableScalarRelationFilter, Prisma.EventChatMessageWhereInput> | null
  replies?: Prisma.EventChatMessageListRelationFilter
}, "id">

export type EventChatMessageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  replyToId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  editedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EventChatMessageCountOrderByAggregateInput
  _max?: Prisma.EventChatMessageMaxOrderByAggregateInput
  _min?: Prisma.EventChatMessageMinOrderByAggregateInput
}

export type EventChatMessageScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventChatMessageScalarWhereWithAggregatesInput | Prisma.EventChatMessageScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventChatMessageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventChatMessageScalarWhereWithAggregatesInput | Prisma.EventChatMessageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EventChatMessage"> | string
  eventId?: Prisma.StringWithAggregatesFilter<"EventChatMessage"> | string
  authorId?: Prisma.StringWithAggregatesFilter<"EventChatMessage"> | string
  content?: Prisma.StringWithAggregatesFilter<"EventChatMessage"> | string
  replyToId?: Prisma.StringNullableWithAggregatesFilter<"EventChatMessage"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventChatMessage"> | Date | string
  editedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"EventChatMessage"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"EventChatMessage"> | Date | string | null
}

export type EventChatMessageCreateInput = {
  id?: string
  content: string
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  event: Prisma.EventCreateNestedOneWithoutChatMessagesInput
  author: Prisma.UserCreateNestedOneWithoutEventChatMessagesInput
  reactions?: Prisma.EventChatMessageReactionCreateNestedManyWithoutMessageInput
  replyTo?: Prisma.EventChatMessageCreateNestedOneWithoutRepliesInput
  replies?: Prisma.EventChatMessageCreateNestedManyWithoutReplyToInput
}

export type EventChatMessageUncheckedCreateInput = {
  id?: string
  eventId: string
  authorId: string
  content: string
  replyToId?: string | null
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  reactions?: Prisma.EventChatMessageReactionUncheckedCreateNestedManyWithoutMessageInput
  replies?: Prisma.EventChatMessageUncheckedCreateNestedManyWithoutReplyToInput
}

export type EventChatMessageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  event?: Prisma.EventUpdateOneRequiredWithoutChatMessagesNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutEventChatMessagesNestedInput
  reactions?: Prisma.EventChatMessageReactionUpdateManyWithoutMessageNestedInput
  replyTo?: Prisma.EventChatMessageUpdateOneWithoutRepliesNestedInput
  replies?: Prisma.EventChatMessageUpdateManyWithoutReplyToNestedInput
}

export type EventChatMessageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reactions?: Prisma.EventChatMessageReactionUncheckedUpdateManyWithoutMessageNestedInput
  replies?: Prisma.EventChatMessageUncheckedUpdateManyWithoutReplyToNestedInput
}

export type EventChatMessageCreateManyInput = {
  id?: string
  eventId: string
  authorId: string
  content: string
  replyToId?: string | null
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
}

export type EventChatMessageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EventChatMessageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EventChatMessageListRelationFilter = {
  every?: Prisma.EventChatMessageWhereInput
  some?: Prisma.EventChatMessageWhereInput
  none?: Prisma.EventChatMessageWhereInput
}

export type EventChatMessageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EventChatMessageNullableScalarRelationFilter = {
  is?: Prisma.EventChatMessageWhereInput | null
  isNot?: Prisma.EventChatMessageWhereInput | null
}

export type EventChatMessageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  replyToId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  editedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EventChatMessageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  replyToId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  editedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EventChatMessageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  replyToId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  editedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EventChatMessageScalarRelationFilter = {
  is?: Prisma.EventChatMessageWhereInput
  isNot?: Prisma.EventChatMessageWhereInput
}

export type EventChatMessageCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutAuthorInput, Prisma.EventChatMessageUncheckedCreateWithoutAuthorInput> | Prisma.EventChatMessageCreateWithoutAuthorInput[] | Prisma.EventChatMessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutAuthorInput | Prisma.EventChatMessageCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.EventChatMessageCreateManyAuthorInputEnvelope
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
}

export type EventChatMessageUncheckedCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutAuthorInput, Prisma.EventChatMessageUncheckedCreateWithoutAuthorInput> | Prisma.EventChatMessageCreateWithoutAuthorInput[] | Prisma.EventChatMessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutAuthorInput | Prisma.EventChatMessageCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.EventChatMessageCreateManyAuthorInputEnvelope
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
}

export type EventChatMessageUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutAuthorInput, Prisma.EventChatMessageUncheckedCreateWithoutAuthorInput> | Prisma.EventChatMessageCreateWithoutAuthorInput[] | Prisma.EventChatMessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutAuthorInput | Prisma.EventChatMessageCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.EventChatMessageUpsertWithWhereUniqueWithoutAuthorInput | Prisma.EventChatMessageUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.EventChatMessageCreateManyAuthorInputEnvelope
  set?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  disconnect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  delete?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  update?: Prisma.EventChatMessageUpdateWithWhereUniqueWithoutAuthorInput | Prisma.EventChatMessageUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.EventChatMessageUpdateManyWithWhereWithoutAuthorInput | Prisma.EventChatMessageUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.EventChatMessageScalarWhereInput | Prisma.EventChatMessageScalarWhereInput[]
}

export type EventChatMessageUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutAuthorInput, Prisma.EventChatMessageUncheckedCreateWithoutAuthorInput> | Prisma.EventChatMessageCreateWithoutAuthorInput[] | Prisma.EventChatMessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutAuthorInput | Prisma.EventChatMessageCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.EventChatMessageUpsertWithWhereUniqueWithoutAuthorInput | Prisma.EventChatMessageUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.EventChatMessageCreateManyAuthorInputEnvelope
  set?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  disconnect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  delete?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  update?: Prisma.EventChatMessageUpdateWithWhereUniqueWithoutAuthorInput | Prisma.EventChatMessageUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.EventChatMessageUpdateManyWithWhereWithoutAuthorInput | Prisma.EventChatMessageUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.EventChatMessageScalarWhereInput | Prisma.EventChatMessageScalarWhereInput[]
}

export type EventChatMessageCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutEventInput, Prisma.EventChatMessageUncheckedCreateWithoutEventInput> | Prisma.EventChatMessageCreateWithoutEventInput[] | Prisma.EventChatMessageUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutEventInput | Prisma.EventChatMessageCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventChatMessageCreateManyEventInputEnvelope
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
}

export type EventChatMessageUncheckedCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutEventInput, Prisma.EventChatMessageUncheckedCreateWithoutEventInput> | Prisma.EventChatMessageCreateWithoutEventInput[] | Prisma.EventChatMessageUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutEventInput | Prisma.EventChatMessageCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventChatMessageCreateManyEventInputEnvelope
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
}

export type EventChatMessageUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutEventInput, Prisma.EventChatMessageUncheckedCreateWithoutEventInput> | Prisma.EventChatMessageCreateWithoutEventInput[] | Prisma.EventChatMessageUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutEventInput | Prisma.EventChatMessageCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventChatMessageUpsertWithWhereUniqueWithoutEventInput | Prisma.EventChatMessageUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventChatMessageCreateManyEventInputEnvelope
  set?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  disconnect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  delete?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  update?: Prisma.EventChatMessageUpdateWithWhereUniqueWithoutEventInput | Prisma.EventChatMessageUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventChatMessageUpdateManyWithWhereWithoutEventInput | Prisma.EventChatMessageUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventChatMessageScalarWhereInput | Prisma.EventChatMessageScalarWhereInput[]
}

export type EventChatMessageUncheckedUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutEventInput, Prisma.EventChatMessageUncheckedCreateWithoutEventInput> | Prisma.EventChatMessageCreateWithoutEventInput[] | Prisma.EventChatMessageUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutEventInput | Prisma.EventChatMessageCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventChatMessageUpsertWithWhereUniqueWithoutEventInput | Prisma.EventChatMessageUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventChatMessageCreateManyEventInputEnvelope
  set?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  disconnect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  delete?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  update?: Prisma.EventChatMessageUpdateWithWhereUniqueWithoutEventInput | Prisma.EventChatMessageUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventChatMessageUpdateManyWithWhereWithoutEventInput | Prisma.EventChatMessageUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventChatMessageScalarWhereInput | Prisma.EventChatMessageScalarWhereInput[]
}

export type EventChatMessageCreateNestedOneWithoutRepliesInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutRepliesInput, Prisma.EventChatMessageUncheckedCreateWithoutRepliesInput>
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutRepliesInput
  connect?: Prisma.EventChatMessageWhereUniqueInput
}

export type EventChatMessageCreateNestedManyWithoutReplyToInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutReplyToInput, Prisma.EventChatMessageUncheckedCreateWithoutReplyToInput> | Prisma.EventChatMessageCreateWithoutReplyToInput[] | Prisma.EventChatMessageUncheckedCreateWithoutReplyToInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutReplyToInput | Prisma.EventChatMessageCreateOrConnectWithoutReplyToInput[]
  createMany?: Prisma.EventChatMessageCreateManyReplyToInputEnvelope
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
}

export type EventChatMessageUncheckedCreateNestedManyWithoutReplyToInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutReplyToInput, Prisma.EventChatMessageUncheckedCreateWithoutReplyToInput> | Prisma.EventChatMessageCreateWithoutReplyToInput[] | Prisma.EventChatMessageUncheckedCreateWithoutReplyToInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutReplyToInput | Prisma.EventChatMessageCreateOrConnectWithoutReplyToInput[]
  createMany?: Prisma.EventChatMessageCreateManyReplyToInputEnvelope
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
}

export type EventChatMessageUpdateOneWithoutRepliesNestedInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutRepliesInput, Prisma.EventChatMessageUncheckedCreateWithoutRepliesInput>
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutRepliesInput
  upsert?: Prisma.EventChatMessageUpsertWithoutRepliesInput
  disconnect?: Prisma.EventChatMessageWhereInput | boolean
  delete?: Prisma.EventChatMessageWhereInput | boolean
  connect?: Prisma.EventChatMessageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventChatMessageUpdateToOneWithWhereWithoutRepliesInput, Prisma.EventChatMessageUpdateWithoutRepliesInput>, Prisma.EventChatMessageUncheckedUpdateWithoutRepliesInput>
}

export type EventChatMessageUpdateManyWithoutReplyToNestedInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutReplyToInput, Prisma.EventChatMessageUncheckedCreateWithoutReplyToInput> | Prisma.EventChatMessageCreateWithoutReplyToInput[] | Prisma.EventChatMessageUncheckedCreateWithoutReplyToInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutReplyToInput | Prisma.EventChatMessageCreateOrConnectWithoutReplyToInput[]
  upsert?: Prisma.EventChatMessageUpsertWithWhereUniqueWithoutReplyToInput | Prisma.EventChatMessageUpsertWithWhereUniqueWithoutReplyToInput[]
  createMany?: Prisma.EventChatMessageCreateManyReplyToInputEnvelope
  set?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  disconnect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  delete?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  update?: Prisma.EventChatMessageUpdateWithWhereUniqueWithoutReplyToInput | Prisma.EventChatMessageUpdateWithWhereUniqueWithoutReplyToInput[]
  updateMany?: Prisma.EventChatMessageUpdateManyWithWhereWithoutReplyToInput | Prisma.EventChatMessageUpdateManyWithWhereWithoutReplyToInput[]
  deleteMany?: Prisma.EventChatMessageScalarWhereInput | Prisma.EventChatMessageScalarWhereInput[]
}

export type EventChatMessageUncheckedUpdateManyWithoutReplyToNestedInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutReplyToInput, Prisma.EventChatMessageUncheckedCreateWithoutReplyToInput> | Prisma.EventChatMessageCreateWithoutReplyToInput[] | Prisma.EventChatMessageUncheckedCreateWithoutReplyToInput[]
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutReplyToInput | Prisma.EventChatMessageCreateOrConnectWithoutReplyToInput[]
  upsert?: Prisma.EventChatMessageUpsertWithWhereUniqueWithoutReplyToInput | Prisma.EventChatMessageUpsertWithWhereUniqueWithoutReplyToInput[]
  createMany?: Prisma.EventChatMessageCreateManyReplyToInputEnvelope
  set?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  disconnect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  delete?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  connect?: Prisma.EventChatMessageWhereUniqueInput | Prisma.EventChatMessageWhereUniqueInput[]
  update?: Prisma.EventChatMessageUpdateWithWhereUniqueWithoutReplyToInput | Prisma.EventChatMessageUpdateWithWhereUniqueWithoutReplyToInput[]
  updateMany?: Prisma.EventChatMessageUpdateManyWithWhereWithoutReplyToInput | Prisma.EventChatMessageUpdateManyWithWhereWithoutReplyToInput[]
  deleteMany?: Prisma.EventChatMessageScalarWhereInput | Prisma.EventChatMessageScalarWhereInput[]
}

export type EventChatMessageCreateNestedOneWithoutReactionsInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutReactionsInput, Prisma.EventChatMessageUncheckedCreateWithoutReactionsInput>
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutReactionsInput
  connect?: Prisma.EventChatMessageWhereUniqueInput
}

export type EventChatMessageUpdateOneRequiredWithoutReactionsNestedInput = {
  create?: Prisma.XOR<Prisma.EventChatMessageCreateWithoutReactionsInput, Prisma.EventChatMessageUncheckedCreateWithoutReactionsInput>
  connectOrCreate?: Prisma.EventChatMessageCreateOrConnectWithoutReactionsInput
  upsert?: Prisma.EventChatMessageUpsertWithoutReactionsInput
  connect?: Prisma.EventChatMessageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventChatMessageUpdateToOneWithWhereWithoutReactionsInput, Prisma.EventChatMessageUpdateWithoutReactionsInput>, Prisma.EventChatMessageUncheckedUpdateWithoutReactionsInput>
}

export type EventChatMessageCreateWithoutAuthorInput = {
  id?: string
  content: string
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  event: Prisma.EventCreateNestedOneWithoutChatMessagesInput
  reactions?: Prisma.EventChatMessageReactionCreateNestedManyWithoutMessageInput
  replyTo?: Prisma.EventChatMessageCreateNestedOneWithoutRepliesInput
  replies?: Prisma.EventChatMessageCreateNestedManyWithoutReplyToInput
}

export type EventChatMessageUncheckedCreateWithoutAuthorInput = {
  id?: string
  eventId: string
  content: string
  replyToId?: string | null
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  reactions?: Prisma.EventChatMessageReactionUncheckedCreateNestedManyWithoutMessageInput
  replies?: Prisma.EventChatMessageUncheckedCreateNestedManyWithoutReplyToInput
}

export type EventChatMessageCreateOrConnectWithoutAuthorInput = {
  where: Prisma.EventChatMessageWhereUniqueInput
  create: Prisma.XOR<Prisma.EventChatMessageCreateWithoutAuthorInput, Prisma.EventChatMessageUncheckedCreateWithoutAuthorInput>
}

export type EventChatMessageCreateManyAuthorInputEnvelope = {
  data: Prisma.EventChatMessageCreateManyAuthorInput | Prisma.EventChatMessageCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type EventChatMessageUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.EventChatMessageWhereUniqueInput
  update: Prisma.XOR<Prisma.EventChatMessageUpdateWithoutAuthorInput, Prisma.EventChatMessageUncheckedUpdateWithoutAuthorInput>
  create: Prisma.XOR<Prisma.EventChatMessageCreateWithoutAuthorInput, Prisma.EventChatMessageUncheckedCreateWithoutAuthorInput>
}

export type EventChatMessageUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.EventChatMessageWhereUniqueInput
  data: Prisma.XOR<Prisma.EventChatMessageUpdateWithoutAuthorInput, Prisma.EventChatMessageUncheckedUpdateWithoutAuthorInput>
}

export type EventChatMessageUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.EventChatMessageScalarWhereInput
  data: Prisma.XOR<Prisma.EventChatMessageUpdateManyMutationInput, Prisma.EventChatMessageUncheckedUpdateManyWithoutAuthorInput>
}

export type EventChatMessageScalarWhereInput = {
  AND?: Prisma.EventChatMessageScalarWhereInput | Prisma.EventChatMessageScalarWhereInput[]
  OR?: Prisma.EventChatMessageScalarWhereInput[]
  NOT?: Prisma.EventChatMessageScalarWhereInput | Prisma.EventChatMessageScalarWhereInput[]
  id?: Prisma.StringFilter<"EventChatMessage"> | string
  eventId?: Prisma.StringFilter<"EventChatMessage"> | string
  authorId?: Prisma.StringFilter<"EventChatMessage"> | string
  content?: Prisma.StringFilter<"EventChatMessage"> | string
  replyToId?: Prisma.StringNullableFilter<"EventChatMessage"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventChatMessage"> | Date | string
  editedAt?: Prisma.DateTimeNullableFilter<"EventChatMessage"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"EventChatMessage"> | Date | string | null
}

export type EventChatMessageCreateWithoutEventInput = {
  id?: string
  content: string
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  author: Prisma.UserCreateNestedOneWithoutEventChatMessagesInput
  reactions?: Prisma.EventChatMessageReactionCreateNestedManyWithoutMessageInput
  replyTo?: Prisma.EventChatMessageCreateNestedOneWithoutRepliesInput
  replies?: Prisma.EventChatMessageCreateNestedManyWithoutReplyToInput
}

export type EventChatMessageUncheckedCreateWithoutEventInput = {
  id?: string
  authorId: string
  content: string
  replyToId?: string | null
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  reactions?: Prisma.EventChatMessageReactionUncheckedCreateNestedManyWithoutMessageInput
  replies?: Prisma.EventChatMessageUncheckedCreateNestedManyWithoutReplyToInput
}

export type EventChatMessageCreateOrConnectWithoutEventInput = {
  where: Prisma.EventChatMessageWhereUniqueInput
  create: Prisma.XOR<Prisma.EventChatMessageCreateWithoutEventInput, Prisma.EventChatMessageUncheckedCreateWithoutEventInput>
}

export type EventChatMessageCreateManyEventInputEnvelope = {
  data: Prisma.EventChatMessageCreateManyEventInput | Prisma.EventChatMessageCreateManyEventInput[]
  skipDuplicates?: boolean
}

export type EventChatMessageUpsertWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventChatMessageWhereUniqueInput
  update: Prisma.XOR<Prisma.EventChatMessageUpdateWithoutEventInput, Prisma.EventChatMessageUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.EventChatMessageCreateWithoutEventInput, Prisma.EventChatMessageUncheckedCreateWithoutEventInput>
}

export type EventChatMessageUpdateWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventChatMessageWhereUniqueInput
  data: Prisma.XOR<Prisma.EventChatMessageUpdateWithoutEventInput, Prisma.EventChatMessageUncheckedUpdateWithoutEventInput>
}

export type EventChatMessageUpdateManyWithWhereWithoutEventInput = {
  where: Prisma.EventChatMessageScalarWhereInput
  data: Prisma.XOR<Prisma.EventChatMessageUpdateManyMutationInput, Prisma.EventChatMessageUncheckedUpdateManyWithoutEventInput>
}

export type EventChatMessageCreateWithoutRepliesInput = {
  id?: string
  content: string
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  event: Prisma.EventCreateNestedOneWithoutChatMessagesInput
  author: Prisma.UserCreateNestedOneWithoutEventChatMessagesInput
  reactions?: Prisma.EventChatMessageReactionCreateNestedManyWithoutMessageInput
  replyTo?: Prisma.EventChatMessageCreateNestedOneWithoutRepliesInput
}

export type EventChatMessageUncheckedCreateWithoutRepliesInput = {
  id?: string
  eventId: string
  authorId: string
  content: string
  replyToId?: string | null
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  reactions?: Prisma.EventChatMessageReactionUncheckedCreateNestedManyWithoutMessageInput
}

export type EventChatMessageCreateOrConnectWithoutRepliesInput = {
  where: Prisma.EventChatMessageWhereUniqueInput
  create: Prisma.XOR<Prisma.EventChatMessageCreateWithoutRepliesInput, Prisma.EventChatMessageUncheckedCreateWithoutRepliesInput>
}

export type EventChatMessageCreateWithoutReplyToInput = {
  id?: string
  content: string
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  event: Prisma.EventCreateNestedOneWithoutChatMessagesInput
  author: Prisma.UserCreateNestedOneWithoutEventChatMessagesInput
  reactions?: Prisma.EventChatMessageReactionCreateNestedManyWithoutMessageInput
  replies?: Prisma.EventChatMessageCreateNestedManyWithoutReplyToInput
}

export type EventChatMessageUncheckedCreateWithoutReplyToInput = {
  id?: string
  eventId: string
  authorId: string
  content: string
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  reactions?: Prisma.EventChatMessageReactionUncheckedCreateNestedManyWithoutMessageInput
  replies?: Prisma.EventChatMessageUncheckedCreateNestedManyWithoutReplyToInput
}

export type EventChatMessageCreateOrConnectWithoutReplyToInput = {
  where: Prisma.EventChatMessageWhereUniqueInput
  create: Prisma.XOR<Prisma.EventChatMessageCreateWithoutReplyToInput, Prisma.EventChatMessageUncheckedCreateWithoutReplyToInput>
}

export type EventChatMessageCreateManyReplyToInputEnvelope = {
  data: Prisma.EventChatMessageCreateManyReplyToInput | Prisma.EventChatMessageCreateManyReplyToInput[]
  skipDuplicates?: boolean
}

export type EventChatMessageUpsertWithoutRepliesInput = {
  update: Prisma.XOR<Prisma.EventChatMessageUpdateWithoutRepliesInput, Prisma.EventChatMessageUncheckedUpdateWithoutRepliesInput>
  create: Prisma.XOR<Prisma.EventChatMessageCreateWithoutRepliesInput, Prisma.EventChatMessageUncheckedCreateWithoutRepliesInput>
  where?: Prisma.EventChatMessageWhereInput
}

export type EventChatMessageUpdateToOneWithWhereWithoutRepliesInput = {
  where?: Prisma.EventChatMessageWhereInput
  data: Prisma.XOR<Prisma.EventChatMessageUpdateWithoutRepliesInput, Prisma.EventChatMessageUncheckedUpdateWithoutRepliesInput>
}

export type EventChatMessageUpdateWithoutRepliesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  event?: Prisma.EventUpdateOneRequiredWithoutChatMessagesNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutEventChatMessagesNestedInput
  reactions?: Prisma.EventChatMessageReactionUpdateManyWithoutMessageNestedInput
  replyTo?: Prisma.EventChatMessageUpdateOneWithoutRepliesNestedInput
}

export type EventChatMessageUncheckedUpdateWithoutRepliesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reactions?: Prisma.EventChatMessageReactionUncheckedUpdateManyWithoutMessageNestedInput
}

export type EventChatMessageUpsertWithWhereUniqueWithoutReplyToInput = {
  where: Prisma.EventChatMessageWhereUniqueInput
  update: Prisma.XOR<Prisma.EventChatMessageUpdateWithoutReplyToInput, Prisma.EventChatMessageUncheckedUpdateWithoutReplyToInput>
  create: Prisma.XOR<Prisma.EventChatMessageCreateWithoutReplyToInput, Prisma.EventChatMessageUncheckedCreateWithoutReplyToInput>
}

export type EventChatMessageUpdateWithWhereUniqueWithoutReplyToInput = {
  where: Prisma.EventChatMessageWhereUniqueInput
  data: Prisma.XOR<Prisma.EventChatMessageUpdateWithoutReplyToInput, Prisma.EventChatMessageUncheckedUpdateWithoutReplyToInput>
}

export type EventChatMessageUpdateManyWithWhereWithoutReplyToInput = {
  where: Prisma.EventChatMessageScalarWhereInput
  data: Prisma.XOR<Prisma.EventChatMessageUpdateManyMutationInput, Prisma.EventChatMessageUncheckedUpdateManyWithoutReplyToInput>
}

export type EventChatMessageCreateWithoutReactionsInput = {
  id?: string
  content: string
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  event: Prisma.EventCreateNestedOneWithoutChatMessagesInput
  author: Prisma.UserCreateNestedOneWithoutEventChatMessagesInput
  replyTo?: Prisma.EventChatMessageCreateNestedOneWithoutRepliesInput
  replies?: Prisma.EventChatMessageCreateNestedManyWithoutReplyToInput
}

export type EventChatMessageUncheckedCreateWithoutReactionsInput = {
  id?: string
  eventId: string
  authorId: string
  content: string
  replyToId?: string | null
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  replies?: Prisma.EventChatMessageUncheckedCreateNestedManyWithoutReplyToInput
}

export type EventChatMessageCreateOrConnectWithoutReactionsInput = {
  where: Prisma.EventChatMessageWhereUniqueInput
  create: Prisma.XOR<Prisma.EventChatMessageCreateWithoutReactionsInput, Prisma.EventChatMessageUncheckedCreateWithoutReactionsInput>
}

export type EventChatMessageUpsertWithoutReactionsInput = {
  update: Prisma.XOR<Prisma.EventChatMessageUpdateWithoutReactionsInput, Prisma.EventChatMessageUncheckedUpdateWithoutReactionsInput>
  create: Prisma.XOR<Prisma.EventChatMessageCreateWithoutReactionsInput, Prisma.EventChatMessageUncheckedCreateWithoutReactionsInput>
  where?: Prisma.EventChatMessageWhereInput
}

export type EventChatMessageUpdateToOneWithWhereWithoutReactionsInput = {
  where?: Prisma.EventChatMessageWhereInput
  data: Prisma.XOR<Prisma.EventChatMessageUpdateWithoutReactionsInput, Prisma.EventChatMessageUncheckedUpdateWithoutReactionsInput>
}

export type EventChatMessageUpdateWithoutReactionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  event?: Prisma.EventUpdateOneRequiredWithoutChatMessagesNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutEventChatMessagesNestedInput
  replyTo?: Prisma.EventChatMessageUpdateOneWithoutRepliesNestedInput
  replies?: Prisma.EventChatMessageUpdateManyWithoutReplyToNestedInput
}

export type EventChatMessageUncheckedUpdateWithoutReactionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  replies?: Prisma.EventChatMessageUncheckedUpdateManyWithoutReplyToNestedInput
}

export type EventChatMessageCreateManyAuthorInput = {
  id?: string
  eventId: string
  content: string
  replyToId?: string | null
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
}

export type EventChatMessageUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  event?: Prisma.EventUpdateOneRequiredWithoutChatMessagesNestedInput
  reactions?: Prisma.EventChatMessageReactionUpdateManyWithoutMessageNestedInput
  replyTo?: Prisma.EventChatMessageUpdateOneWithoutRepliesNestedInput
  replies?: Prisma.EventChatMessageUpdateManyWithoutReplyToNestedInput
}

export type EventChatMessageUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reactions?: Prisma.EventChatMessageReactionUncheckedUpdateManyWithoutMessageNestedInput
  replies?: Prisma.EventChatMessageUncheckedUpdateManyWithoutReplyToNestedInput
}

export type EventChatMessageUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EventChatMessageCreateManyEventInput = {
  id?: string
  authorId: string
  content: string
  replyToId?: string | null
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
}

export type EventChatMessageUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  author?: Prisma.UserUpdateOneRequiredWithoutEventChatMessagesNestedInput
  reactions?: Prisma.EventChatMessageReactionUpdateManyWithoutMessageNestedInput
  replyTo?: Prisma.EventChatMessageUpdateOneWithoutRepliesNestedInput
  replies?: Prisma.EventChatMessageUpdateManyWithoutReplyToNestedInput
}

export type EventChatMessageUncheckedUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reactions?: Prisma.EventChatMessageReactionUncheckedUpdateManyWithoutMessageNestedInput
  replies?: Prisma.EventChatMessageUncheckedUpdateManyWithoutReplyToNestedInput
}

export type EventChatMessageUncheckedUpdateManyWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EventChatMessageCreateManyReplyToInput = {
  id?: string
  eventId: string
  authorId: string
  content: string
  createdAt?: Date | string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
}

export type EventChatMessageUpdateWithoutReplyToInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  event?: Prisma.EventUpdateOneRequiredWithoutChatMessagesNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutEventChatMessagesNestedInput
  reactions?: Prisma.EventChatMessageReactionUpdateManyWithoutMessageNestedInput
  replies?: Prisma.EventChatMessageUpdateManyWithoutReplyToNestedInput
}

export type EventChatMessageUncheckedUpdateWithoutReplyToInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reactions?: Prisma.EventChatMessageReactionUncheckedUpdateManyWithoutMessageNestedInput
  replies?: Prisma.EventChatMessageUncheckedUpdateManyWithoutReplyToNestedInput
}

export type EventChatMessageUncheckedUpdateManyWithoutReplyToInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type EventChatMessageCountOutputType
 */

export type EventChatMessageCountOutputType = {
  reactions: number
  replies: number
}

export type EventChatMessageCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reactions?: boolean | EventChatMessageCountOutputTypeCountReactionsArgs
  replies?: boolean | EventChatMessageCountOutputTypeCountRepliesArgs
}

/**
 * EventChatMessageCountOutputType without action
 */
export type EventChatMessageCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessageCountOutputType
   */
  select?: Prisma.EventChatMessageCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EventChatMessageCountOutputType without action
 */
export type EventChatMessageCountOutputTypeCountReactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventChatMessageReactionWhereInput
}

/**
 * EventChatMessageCountOutputType without action
 */
export type EventChatMessageCountOutputTypeCountRepliesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventChatMessageWhereInput
}


export type EventChatMessageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  authorId?: boolean
  content?: boolean
  replyToId?: boolean
  createdAt?: boolean
  editedAt?: boolean
  deletedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reactions?: boolean | Prisma.EventChatMessage$reactionsArgs<ExtArgs>
  replyTo?: boolean | Prisma.EventChatMessage$replyToArgs<ExtArgs>
  replies?: boolean | Prisma.EventChatMessage$repliesArgs<ExtArgs>
  _count?: boolean | Prisma.EventChatMessageCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventChatMessage"]>

export type EventChatMessageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  authorId?: boolean
  content?: boolean
  replyToId?: boolean
  createdAt?: boolean
  editedAt?: boolean
  deletedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replyTo?: boolean | Prisma.EventChatMessage$replyToArgs<ExtArgs>
}, ExtArgs["result"]["eventChatMessage"]>

export type EventChatMessageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  authorId?: boolean
  content?: boolean
  replyToId?: boolean
  createdAt?: boolean
  editedAt?: boolean
  deletedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replyTo?: boolean | Prisma.EventChatMessage$replyToArgs<ExtArgs>
}, ExtArgs["result"]["eventChatMessage"]>

export type EventChatMessageSelectScalar = {
  id?: boolean
  eventId?: boolean
  authorId?: boolean
  content?: boolean
  replyToId?: boolean
  createdAt?: boolean
  editedAt?: boolean
  deletedAt?: boolean
}

export type EventChatMessageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "eventId" | "authorId" | "content" | "replyToId" | "createdAt" | "editedAt" | "deletedAt", ExtArgs["result"]["eventChatMessage"]>
export type EventChatMessageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  reactions?: boolean | Prisma.EventChatMessage$reactionsArgs<ExtArgs>
  replyTo?: boolean | Prisma.EventChatMessage$replyToArgs<ExtArgs>
  replies?: boolean | Prisma.EventChatMessage$repliesArgs<ExtArgs>
  _count?: boolean | Prisma.EventChatMessageCountOutputTypeDefaultArgs<ExtArgs>
}
export type EventChatMessageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replyTo?: boolean | Prisma.EventChatMessage$replyToArgs<ExtArgs>
}
export type EventChatMessageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replyTo?: boolean | Prisma.EventChatMessage$replyToArgs<ExtArgs>
}

export type $EventChatMessagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventChatMessage"
  objects: {
    event: Prisma.$EventPayload<ExtArgs>
    author: Prisma.$UserPayload<ExtArgs>
    reactions: Prisma.$EventChatMessageReactionPayload<ExtArgs>[]
    replyTo: Prisma.$EventChatMessagePayload<ExtArgs> | null
    replies: Prisma.$EventChatMessagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    eventId: string
    authorId: string
    content: string
    replyToId: string | null
    createdAt: Date
    editedAt: Date | null
    deletedAt: Date | null
  }, ExtArgs["result"]["eventChatMessage"]>
  composites: {}
}

export type EventChatMessageGetPayload<S extends boolean | null | undefined | EventChatMessageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload, S>

export type EventChatMessageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventChatMessageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventChatMessageCountAggregateInputType | true
  }

export interface EventChatMessageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventChatMessage'], meta: { name: 'EventChatMessage' } }
  /**
   * Find zero or one EventChatMessage that matches the filter.
   * @param {EventChatMessageFindUniqueArgs} args - Arguments to find a EventChatMessage
   * @example
   * // Get one EventChatMessage
   * const eventChatMessage = await prisma.eventChatMessage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventChatMessageFindUniqueArgs>(args: Prisma.SelectSubset<T, EventChatMessageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventChatMessageClient<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventChatMessage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventChatMessageFindUniqueOrThrowArgs} args - Arguments to find a EventChatMessage
   * @example
   * // Get one EventChatMessage
   * const eventChatMessage = await prisma.eventChatMessage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventChatMessageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventChatMessageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventChatMessageClient<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventChatMessage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventChatMessageFindFirstArgs} args - Arguments to find a EventChatMessage
   * @example
   * // Get one EventChatMessage
   * const eventChatMessage = await prisma.eventChatMessage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventChatMessageFindFirstArgs>(args?: Prisma.SelectSubset<T, EventChatMessageFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventChatMessageClient<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventChatMessage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventChatMessageFindFirstOrThrowArgs} args - Arguments to find a EventChatMessage
   * @example
   * // Get one EventChatMessage
   * const eventChatMessage = await prisma.eventChatMessage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventChatMessageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventChatMessageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventChatMessageClient<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventChatMessages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventChatMessageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventChatMessages
   * const eventChatMessages = await prisma.eventChatMessage.findMany()
   * 
   * // Get first 10 EventChatMessages
   * const eventChatMessages = await prisma.eventChatMessage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventChatMessageWithIdOnly = await prisma.eventChatMessage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventChatMessageFindManyArgs>(args?: Prisma.SelectSubset<T, EventChatMessageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventChatMessage.
   * @param {EventChatMessageCreateArgs} args - Arguments to create a EventChatMessage.
   * @example
   * // Create one EventChatMessage
   * const EventChatMessage = await prisma.eventChatMessage.create({
   *   data: {
   *     // ... data to create a EventChatMessage
   *   }
   * })
   * 
   */
  create<T extends EventChatMessageCreateArgs>(args: Prisma.SelectSubset<T, EventChatMessageCreateArgs<ExtArgs>>): Prisma.Prisma__EventChatMessageClient<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventChatMessages.
   * @param {EventChatMessageCreateManyArgs} args - Arguments to create many EventChatMessages.
   * @example
   * // Create many EventChatMessages
   * const eventChatMessage = await prisma.eventChatMessage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventChatMessageCreateManyArgs>(args?: Prisma.SelectSubset<T, EventChatMessageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventChatMessages and returns the data saved in the database.
   * @param {EventChatMessageCreateManyAndReturnArgs} args - Arguments to create many EventChatMessages.
   * @example
   * // Create many EventChatMessages
   * const eventChatMessage = await prisma.eventChatMessage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventChatMessages and only return the `id`
   * const eventChatMessageWithIdOnly = await prisma.eventChatMessage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventChatMessageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventChatMessageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventChatMessage.
   * @param {EventChatMessageDeleteArgs} args - Arguments to delete one EventChatMessage.
   * @example
   * // Delete one EventChatMessage
   * const EventChatMessage = await prisma.eventChatMessage.delete({
   *   where: {
   *     // ... filter to delete one EventChatMessage
   *   }
   * })
   * 
   */
  delete<T extends EventChatMessageDeleteArgs>(args: Prisma.SelectSubset<T, EventChatMessageDeleteArgs<ExtArgs>>): Prisma.Prisma__EventChatMessageClient<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventChatMessage.
   * @param {EventChatMessageUpdateArgs} args - Arguments to update one EventChatMessage.
   * @example
   * // Update one EventChatMessage
   * const eventChatMessage = await prisma.eventChatMessage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventChatMessageUpdateArgs>(args: Prisma.SelectSubset<T, EventChatMessageUpdateArgs<ExtArgs>>): Prisma.Prisma__EventChatMessageClient<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventChatMessages.
   * @param {EventChatMessageDeleteManyArgs} args - Arguments to filter EventChatMessages to delete.
   * @example
   * // Delete a few EventChatMessages
   * const { count } = await prisma.eventChatMessage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventChatMessageDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventChatMessageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventChatMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventChatMessageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventChatMessages
   * const eventChatMessage = await prisma.eventChatMessage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventChatMessageUpdateManyArgs>(args: Prisma.SelectSubset<T, EventChatMessageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventChatMessages and returns the data updated in the database.
   * @param {EventChatMessageUpdateManyAndReturnArgs} args - Arguments to update many EventChatMessages.
   * @example
   * // Update many EventChatMessages
   * const eventChatMessage = await prisma.eventChatMessage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventChatMessages and only return the `id`
   * const eventChatMessageWithIdOnly = await prisma.eventChatMessage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventChatMessageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventChatMessageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventChatMessage.
   * @param {EventChatMessageUpsertArgs} args - Arguments to update or create a EventChatMessage.
   * @example
   * // Update or create a EventChatMessage
   * const eventChatMessage = await prisma.eventChatMessage.upsert({
   *   create: {
   *     // ... data to create a EventChatMessage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventChatMessage we want to update
   *   }
   * })
   */
  upsert<T extends EventChatMessageUpsertArgs>(args: Prisma.SelectSubset<T, EventChatMessageUpsertArgs<ExtArgs>>): Prisma.Prisma__EventChatMessageClient<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventChatMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventChatMessageCountArgs} args - Arguments to filter EventChatMessages to count.
   * @example
   * // Count the number of EventChatMessages
   * const count = await prisma.eventChatMessage.count({
   *   where: {
   *     // ... the filter for the EventChatMessages we want to count
   *   }
   * })
  **/
  count<T extends EventChatMessageCountArgs>(
    args?: Prisma.Subset<T, EventChatMessageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventChatMessageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventChatMessage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventChatMessageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventChatMessageAggregateArgs>(args: Prisma.Subset<T, EventChatMessageAggregateArgs>): Prisma.PrismaPromise<GetEventChatMessageAggregateType<T>>

  /**
   * Group by EventChatMessage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventChatMessageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventChatMessageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventChatMessageGroupByArgs['orderBy'] }
      : { orderBy?: EventChatMessageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventChatMessageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventChatMessageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventChatMessage model
 */
readonly fields: EventChatMessageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventChatMessage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventChatMessageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  event<T extends Prisma.EventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDefaultArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  author<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  reactions<T extends Prisma.EventChatMessage$reactionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventChatMessage$reactionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventChatMessageReactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  replyTo<T extends Prisma.EventChatMessage$replyToArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventChatMessage$replyToArgs<ExtArgs>>): Prisma.Prisma__EventChatMessageClient<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  replies<T extends Prisma.EventChatMessage$repliesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventChatMessage$repliesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventChatMessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventChatMessage model
 */
export interface EventChatMessageFieldRefs {
  readonly id: Prisma.FieldRef<"EventChatMessage", 'String'>
  readonly eventId: Prisma.FieldRef<"EventChatMessage", 'String'>
  readonly authorId: Prisma.FieldRef<"EventChatMessage", 'String'>
  readonly content: Prisma.FieldRef<"EventChatMessage", 'String'>
  readonly replyToId: Prisma.FieldRef<"EventChatMessage", 'String'>
  readonly createdAt: Prisma.FieldRef<"EventChatMessage", 'DateTime'>
  readonly editedAt: Prisma.FieldRef<"EventChatMessage", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"EventChatMessage", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EventChatMessage findUnique
 */
export type EventChatMessageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
  /**
   * Filter, which EventChatMessage to fetch.
   */
  where: Prisma.EventChatMessageWhereUniqueInput
}

/**
 * EventChatMessage findUniqueOrThrow
 */
export type EventChatMessageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
  /**
   * Filter, which EventChatMessage to fetch.
   */
  where: Prisma.EventChatMessageWhereUniqueInput
}

/**
 * EventChatMessage findFirst
 */
export type EventChatMessageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
  /**
   * Filter, which EventChatMessage to fetch.
   */
  where?: Prisma.EventChatMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventChatMessages to fetch.
   */
  orderBy?: Prisma.EventChatMessageOrderByWithRelationInput | Prisma.EventChatMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventChatMessages.
   */
  cursor?: Prisma.EventChatMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventChatMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventChatMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventChatMessages.
   */
  distinct?: Prisma.EventChatMessageScalarFieldEnum | Prisma.EventChatMessageScalarFieldEnum[]
}

/**
 * EventChatMessage findFirstOrThrow
 */
export type EventChatMessageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
  /**
   * Filter, which EventChatMessage to fetch.
   */
  where?: Prisma.EventChatMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventChatMessages to fetch.
   */
  orderBy?: Prisma.EventChatMessageOrderByWithRelationInput | Prisma.EventChatMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventChatMessages.
   */
  cursor?: Prisma.EventChatMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventChatMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventChatMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventChatMessages.
   */
  distinct?: Prisma.EventChatMessageScalarFieldEnum | Prisma.EventChatMessageScalarFieldEnum[]
}

/**
 * EventChatMessage findMany
 */
export type EventChatMessageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
  /**
   * Filter, which EventChatMessages to fetch.
   */
  where?: Prisma.EventChatMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventChatMessages to fetch.
   */
  orderBy?: Prisma.EventChatMessageOrderByWithRelationInput | Prisma.EventChatMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventChatMessages.
   */
  cursor?: Prisma.EventChatMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventChatMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventChatMessages.
   */
  skip?: number
  distinct?: Prisma.EventChatMessageScalarFieldEnum | Prisma.EventChatMessageScalarFieldEnum[]
}

/**
 * EventChatMessage create
 */
export type EventChatMessageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
  /**
   * The data needed to create a EventChatMessage.
   */
  data: Prisma.XOR<Prisma.EventChatMessageCreateInput, Prisma.EventChatMessageUncheckedCreateInput>
}

/**
 * EventChatMessage createMany
 */
export type EventChatMessageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventChatMessages.
   */
  data: Prisma.EventChatMessageCreateManyInput | Prisma.EventChatMessageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EventChatMessage createManyAndReturn
 */
export type EventChatMessageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * The data used to create many EventChatMessages.
   */
  data: Prisma.EventChatMessageCreateManyInput | Prisma.EventChatMessageCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EventChatMessage update
 */
export type EventChatMessageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
  /**
   * The data needed to update a EventChatMessage.
   */
  data: Prisma.XOR<Prisma.EventChatMessageUpdateInput, Prisma.EventChatMessageUncheckedUpdateInput>
  /**
   * Choose, which EventChatMessage to update.
   */
  where: Prisma.EventChatMessageWhereUniqueInput
}

/**
 * EventChatMessage updateMany
 */
export type EventChatMessageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventChatMessages.
   */
  data: Prisma.XOR<Prisma.EventChatMessageUpdateManyMutationInput, Prisma.EventChatMessageUncheckedUpdateManyInput>
  /**
   * Filter which EventChatMessages to update
   */
  where?: Prisma.EventChatMessageWhereInput
  /**
   * Limit how many EventChatMessages to update.
   */
  limit?: number
}

/**
 * EventChatMessage updateManyAndReturn
 */
export type EventChatMessageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * The data used to update EventChatMessages.
   */
  data: Prisma.XOR<Prisma.EventChatMessageUpdateManyMutationInput, Prisma.EventChatMessageUncheckedUpdateManyInput>
  /**
   * Filter which EventChatMessages to update
   */
  where?: Prisma.EventChatMessageWhereInput
  /**
   * Limit how many EventChatMessages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EventChatMessage upsert
 */
export type EventChatMessageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
  /**
   * The filter to search for the EventChatMessage to update in case it exists.
   */
  where: Prisma.EventChatMessageWhereUniqueInput
  /**
   * In case the EventChatMessage found by the `where` argument doesn't exist, create a new EventChatMessage with this data.
   */
  create: Prisma.XOR<Prisma.EventChatMessageCreateInput, Prisma.EventChatMessageUncheckedCreateInput>
  /**
   * In case the EventChatMessage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventChatMessageUpdateInput, Prisma.EventChatMessageUncheckedUpdateInput>
}

/**
 * EventChatMessage delete
 */
export type EventChatMessageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
  /**
   * Filter which EventChatMessage to delete.
   */
  where: Prisma.EventChatMessageWhereUniqueInput
}

/**
 * EventChatMessage deleteMany
 */
export type EventChatMessageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventChatMessages to delete
   */
  where?: Prisma.EventChatMessageWhereInput
  /**
   * Limit how many EventChatMessages to delete.
   */
  limit?: number
}

/**
 * EventChatMessage.reactions
 */
export type EventChatMessage$reactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessageReaction
   */
  select?: Prisma.EventChatMessageReactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessageReaction
   */
  omit?: Prisma.EventChatMessageReactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageReactionInclude<ExtArgs> | null
  where?: Prisma.EventChatMessageReactionWhereInput
  orderBy?: Prisma.EventChatMessageReactionOrderByWithRelationInput | Prisma.EventChatMessageReactionOrderByWithRelationInput[]
  cursor?: Prisma.EventChatMessageReactionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EventChatMessageReactionScalarFieldEnum | Prisma.EventChatMessageReactionScalarFieldEnum[]
}

/**
 * EventChatMessage.replyTo
 */
export type EventChatMessage$replyToArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
  where?: Prisma.EventChatMessageWhereInput
}

/**
 * EventChatMessage.replies
 */
export type EventChatMessage$repliesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
  where?: Prisma.EventChatMessageWhereInput
  orderBy?: Prisma.EventChatMessageOrderByWithRelationInput | Prisma.EventChatMessageOrderByWithRelationInput[]
  cursor?: Prisma.EventChatMessageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EventChatMessageScalarFieldEnum | Prisma.EventChatMessageScalarFieldEnum[]
}

/**
 * EventChatMessage without action
 */
export type EventChatMessageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventChatMessage
   */
  select?: Prisma.EventChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventChatMessage
   */
  omit?: Prisma.EventChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventChatMessageInclude<ExtArgs> | null
}
