
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `EventAgendaItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model EventAgendaItem
 * 
 */
export type EventAgendaItemModel = runtime.Types.Result.DefaultSelection<Prisma.$EventAgendaItemPayload>

export type AggregateEventAgendaItem = {
  _count: EventAgendaItemCountAggregateOutputType | null
  _avg: EventAgendaItemAvgAggregateOutputType | null
  _sum: EventAgendaItemSumAggregateOutputType | null
  _min: EventAgendaItemMinAggregateOutputType | null
  _max: EventAgendaItemMaxAggregateOutputType | null
}

export type EventAgendaItemAvgAggregateOutputType = {
  order: number | null
}

export type EventAgendaItemSumAggregateOutputType = {
  order: number | null
}

export type EventAgendaItemMinAggregateOutputType = {
  id: string | null
  eventId: string | null
  order: number | null
  title: string | null
  description: string | null
  startAt: Date | null
  endAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventAgendaItemMaxAggregateOutputType = {
  id: string | null
  eventId: string | null
  order: number | null
  title: string | null
  description: string | null
  startAt: Date | null
  endAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventAgendaItemCountAggregateOutputType = {
  id: number
  eventId: number
  order: number
  title: number
  description: number
  startAt: number
  endAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type EventAgendaItemAvgAggregateInputType = {
  order?: true
}

export type EventAgendaItemSumAggregateInputType = {
  order?: true
}

export type EventAgendaItemMinAggregateInputType = {
  id?: true
  eventId?: true
  order?: true
  title?: true
  description?: true
  startAt?: true
  endAt?: true
  createdAt?: true
  updatedAt?: true
}

export type EventAgendaItemMaxAggregateInputType = {
  id?: true
  eventId?: true
  order?: true
  title?: true
  description?: true
  startAt?: true
  endAt?: true
  createdAt?: true
  updatedAt?: true
}

export type EventAgendaItemCountAggregateInputType = {
  id?: true
  eventId?: true
  order?: true
  title?: true
  description?: true
  startAt?: true
  endAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type EventAgendaItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventAgendaItem to aggregate.
   */
  where?: Prisma.EventAgendaItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventAgendaItems to fetch.
   */
  orderBy?: Prisma.EventAgendaItemOrderByWithRelationInput | Prisma.EventAgendaItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventAgendaItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventAgendaItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventAgendaItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventAgendaItems
  **/
  _count?: true | EventAgendaItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EventAgendaItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EventAgendaItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventAgendaItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventAgendaItemMaxAggregateInputType
}

export type GetEventAgendaItemAggregateType<T extends EventAgendaItemAggregateArgs> = {
      [P in keyof T & keyof AggregateEventAgendaItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventAgendaItem[P]>
    : Prisma.GetScalarType<T[P], AggregateEventAgendaItem[P]>
}




export type EventAgendaItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventAgendaItemWhereInput
  orderBy?: Prisma.EventAgendaItemOrderByWithAggregationInput | Prisma.EventAgendaItemOrderByWithAggregationInput[]
  by: Prisma.EventAgendaItemScalarFieldEnum[] | Prisma.EventAgendaItemScalarFieldEnum
  having?: Prisma.EventAgendaItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventAgendaItemCountAggregateInputType | true
  _avg?: EventAgendaItemAvgAggregateInputType
  _sum?: EventAgendaItemSumAggregateInputType
  _min?: EventAgendaItemMinAggregateInputType
  _max?: EventAgendaItemMaxAggregateInputType
}

export type EventAgendaItemGroupByOutputType = {
  id: string
  eventId: string
  order: number
  title: string
  description: string | null
  startAt: Date | null
  endAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: EventAgendaItemCountAggregateOutputType | null
  _avg: EventAgendaItemAvgAggregateOutputType | null
  _sum: EventAgendaItemSumAggregateOutputType | null
  _min: EventAgendaItemMinAggregateOutputType | null
  _max: EventAgendaItemMaxAggregateOutputType | null
}

type GetEventAgendaItemGroupByPayload<T extends EventAgendaItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventAgendaItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventAgendaItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventAgendaItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventAgendaItemGroupByOutputType[P]>
      }
    >
  >



export type EventAgendaItemWhereInput = {
  AND?: Prisma.EventAgendaItemWhereInput | Prisma.EventAgendaItemWhereInput[]
  OR?: Prisma.EventAgendaItemWhereInput[]
  NOT?: Prisma.EventAgendaItemWhereInput | Prisma.EventAgendaItemWhereInput[]
  id?: Prisma.StringFilter<"EventAgendaItem"> | string
  eventId?: Prisma.StringFilter<"EventAgendaItem"> | string
  order?: Prisma.IntFilter<"EventAgendaItem"> | number
  title?: Prisma.StringFilter<"EventAgendaItem"> | string
  description?: Prisma.StringNullableFilter<"EventAgendaItem"> | string | null
  startAt?: Prisma.DateTimeNullableFilter<"EventAgendaItem"> | Date | string | null
  endAt?: Prisma.DateTimeNullableFilter<"EventAgendaItem"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"EventAgendaItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventAgendaItem"> | Date | string
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  hosts?: Prisma.EventAgendaItemHostListRelationFilter
}

export type EventAgendaItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  startAt?: Prisma.SortOrderInput | Prisma.SortOrder
  endAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  event?: Prisma.EventOrderByWithRelationInput
  hosts?: Prisma.EventAgendaItemHostOrderByRelationAggregateInput
}

export type EventAgendaItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EventAgendaItemWhereInput | Prisma.EventAgendaItemWhereInput[]
  OR?: Prisma.EventAgendaItemWhereInput[]
  NOT?: Prisma.EventAgendaItemWhereInput | Prisma.EventAgendaItemWhereInput[]
  eventId?: Prisma.StringFilter<"EventAgendaItem"> | string
  order?: Prisma.IntFilter<"EventAgendaItem"> | number
  title?: Prisma.StringFilter<"EventAgendaItem"> | string
  description?: Prisma.StringNullableFilter<"EventAgendaItem"> | string | null
  startAt?: Prisma.DateTimeNullableFilter<"EventAgendaItem"> | Date | string | null
  endAt?: Prisma.DateTimeNullableFilter<"EventAgendaItem"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"EventAgendaItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventAgendaItem"> | Date | string
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  hosts?: Prisma.EventAgendaItemHostListRelationFilter
}, "id">

export type EventAgendaItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  startAt?: Prisma.SortOrderInput | Prisma.SortOrder
  endAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.EventAgendaItemCountOrderByAggregateInput
  _avg?: Prisma.EventAgendaItemAvgOrderByAggregateInput
  _max?: Prisma.EventAgendaItemMaxOrderByAggregateInput
  _min?: Prisma.EventAgendaItemMinOrderByAggregateInput
  _sum?: Prisma.EventAgendaItemSumOrderByAggregateInput
}

export type EventAgendaItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventAgendaItemScalarWhereWithAggregatesInput | Prisma.EventAgendaItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventAgendaItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventAgendaItemScalarWhereWithAggregatesInput | Prisma.EventAgendaItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EventAgendaItem"> | string
  eventId?: Prisma.StringWithAggregatesFilter<"EventAgendaItem"> | string
  order?: Prisma.IntWithAggregatesFilter<"EventAgendaItem"> | number
  title?: Prisma.StringWithAggregatesFilter<"EventAgendaItem"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"EventAgendaItem"> | string | null
  startAt?: Prisma.DateTimeNullableWithAggregatesFilter<"EventAgendaItem"> | Date | string | null
  endAt?: Prisma.DateTimeNullableWithAggregatesFilter<"EventAgendaItem"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventAgendaItem"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EventAgendaItem"> | Date | string
}

export type EventAgendaItemCreateInput = {
  id?: string
  order?: number
  title: string
  description?: string | null
  startAt?: Date | string | null
  endAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutAgendaItemsInput
  hosts?: Prisma.EventAgendaItemHostCreateNestedManyWithoutAgendaItemInput
}

export type EventAgendaItemUncheckedCreateInput = {
  id?: string
  eventId: string
  order?: number
  title: string
  description?: string | null
  startAt?: Date | string | null
  endAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  hosts?: Prisma.EventAgendaItemHostUncheckedCreateNestedManyWithoutAgendaItemInput
}

export type EventAgendaItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutAgendaItemsNestedInput
  hosts?: Prisma.EventAgendaItemHostUpdateManyWithoutAgendaItemNestedInput
}

export type EventAgendaItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hosts?: Prisma.EventAgendaItemHostUncheckedUpdateManyWithoutAgendaItemNestedInput
}

export type EventAgendaItemCreateManyInput = {
  id?: string
  eventId: string
  order?: number
  title: string
  description?: string | null
  startAt?: Date | string | null
  endAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventAgendaItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventAgendaItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventAgendaItemListRelationFilter = {
  every?: Prisma.EventAgendaItemWhereInput
  some?: Prisma.EventAgendaItemWhereInput
  none?: Prisma.EventAgendaItemWhereInput
}

export type EventAgendaItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EventAgendaItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  startAt?: Prisma.SortOrder
  endAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventAgendaItemAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type EventAgendaItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  startAt?: Prisma.SortOrder
  endAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventAgendaItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  startAt?: Prisma.SortOrder
  endAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventAgendaItemSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type EventAgendaItemScalarRelationFilter = {
  is?: Prisma.EventAgendaItemWhereInput
  isNot?: Prisma.EventAgendaItemWhereInput
}

export type EventAgendaItemCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventAgendaItemCreateWithoutEventInput, Prisma.EventAgendaItemUncheckedCreateWithoutEventInput> | Prisma.EventAgendaItemCreateWithoutEventInput[] | Prisma.EventAgendaItemUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventAgendaItemCreateOrConnectWithoutEventInput | Prisma.EventAgendaItemCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventAgendaItemCreateManyEventInputEnvelope
  connect?: Prisma.EventAgendaItemWhereUniqueInput | Prisma.EventAgendaItemWhereUniqueInput[]
}

export type EventAgendaItemUncheckedCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventAgendaItemCreateWithoutEventInput, Prisma.EventAgendaItemUncheckedCreateWithoutEventInput> | Prisma.EventAgendaItemCreateWithoutEventInput[] | Prisma.EventAgendaItemUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventAgendaItemCreateOrConnectWithoutEventInput | Prisma.EventAgendaItemCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventAgendaItemCreateManyEventInputEnvelope
  connect?: Prisma.EventAgendaItemWhereUniqueInput | Prisma.EventAgendaItemWhereUniqueInput[]
}

export type EventAgendaItemUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventAgendaItemCreateWithoutEventInput, Prisma.EventAgendaItemUncheckedCreateWithoutEventInput> | Prisma.EventAgendaItemCreateWithoutEventInput[] | Prisma.EventAgendaItemUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventAgendaItemCreateOrConnectWithoutEventInput | Prisma.EventAgendaItemCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventAgendaItemUpsertWithWhereUniqueWithoutEventInput | Prisma.EventAgendaItemUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventAgendaItemCreateManyEventInputEnvelope
  set?: Prisma.EventAgendaItemWhereUniqueInput | Prisma.EventAgendaItemWhereUniqueInput[]
  disconnect?: Prisma.EventAgendaItemWhereUniqueInput | Prisma.EventAgendaItemWhereUniqueInput[]
  delete?: Prisma.EventAgendaItemWhereUniqueInput | Prisma.EventAgendaItemWhereUniqueInput[]
  connect?: Prisma.EventAgendaItemWhereUniqueInput | Prisma.EventAgendaItemWhereUniqueInput[]
  update?: Prisma.EventAgendaItemUpdateWithWhereUniqueWithoutEventInput | Prisma.EventAgendaItemUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventAgendaItemUpdateManyWithWhereWithoutEventInput | Prisma.EventAgendaItemUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventAgendaItemScalarWhereInput | Prisma.EventAgendaItemScalarWhereInput[]
}

export type EventAgendaItemUncheckedUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventAgendaItemCreateWithoutEventInput, Prisma.EventAgendaItemUncheckedCreateWithoutEventInput> | Prisma.EventAgendaItemCreateWithoutEventInput[] | Prisma.EventAgendaItemUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventAgendaItemCreateOrConnectWithoutEventInput | Prisma.EventAgendaItemCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventAgendaItemUpsertWithWhereUniqueWithoutEventInput | Prisma.EventAgendaItemUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventAgendaItemCreateManyEventInputEnvelope
  set?: Prisma.EventAgendaItemWhereUniqueInput | Prisma.EventAgendaItemWhereUniqueInput[]
  disconnect?: Prisma.EventAgendaItemWhereUniqueInput | Prisma.EventAgendaItemWhereUniqueInput[]
  delete?: Prisma.EventAgendaItemWhereUniqueInput | Prisma.EventAgendaItemWhereUniqueInput[]
  connect?: Prisma.EventAgendaItemWhereUniqueInput | Prisma.EventAgendaItemWhereUniqueInput[]
  update?: Prisma.EventAgendaItemUpdateWithWhereUniqueWithoutEventInput | Prisma.EventAgendaItemUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventAgendaItemUpdateManyWithWhereWithoutEventInput | Prisma.EventAgendaItemUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventAgendaItemScalarWhereInput | Prisma.EventAgendaItemScalarWhereInput[]
}

export type EventAgendaItemCreateNestedOneWithoutHostsInput = {
  create?: Prisma.XOR<Prisma.EventAgendaItemCreateWithoutHostsInput, Prisma.EventAgendaItemUncheckedCreateWithoutHostsInput>
  connectOrCreate?: Prisma.EventAgendaItemCreateOrConnectWithoutHostsInput
  connect?: Prisma.EventAgendaItemWhereUniqueInput
}

export type EventAgendaItemUpdateOneRequiredWithoutHostsNestedInput = {
  create?: Prisma.XOR<Prisma.EventAgendaItemCreateWithoutHostsInput, Prisma.EventAgendaItemUncheckedCreateWithoutHostsInput>
  connectOrCreate?: Prisma.EventAgendaItemCreateOrConnectWithoutHostsInput
  upsert?: Prisma.EventAgendaItemUpsertWithoutHostsInput
  connect?: Prisma.EventAgendaItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventAgendaItemUpdateToOneWithWhereWithoutHostsInput, Prisma.EventAgendaItemUpdateWithoutHostsInput>, Prisma.EventAgendaItemUncheckedUpdateWithoutHostsInput>
}

export type EventAgendaItemCreateWithoutEventInput = {
  id?: string
  order?: number
  title: string
  description?: string | null
  startAt?: Date | string | null
  endAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  hosts?: Prisma.EventAgendaItemHostCreateNestedManyWithoutAgendaItemInput
}

export type EventAgendaItemUncheckedCreateWithoutEventInput = {
  id?: string
  order?: number
  title: string
  description?: string | null
  startAt?: Date | string | null
  endAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  hosts?: Prisma.EventAgendaItemHostUncheckedCreateNestedManyWithoutAgendaItemInput
}

export type EventAgendaItemCreateOrConnectWithoutEventInput = {
  where: Prisma.EventAgendaItemWhereUniqueInput
  create: Prisma.XOR<Prisma.EventAgendaItemCreateWithoutEventInput, Prisma.EventAgendaItemUncheckedCreateWithoutEventInput>
}

export type EventAgendaItemCreateManyEventInputEnvelope = {
  data: Prisma.EventAgendaItemCreateManyEventInput | Prisma.EventAgendaItemCreateManyEventInput[]
  skipDuplicates?: boolean
}

export type EventAgendaItemUpsertWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventAgendaItemWhereUniqueInput
  update: Prisma.XOR<Prisma.EventAgendaItemUpdateWithoutEventInput, Prisma.EventAgendaItemUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.EventAgendaItemCreateWithoutEventInput, Prisma.EventAgendaItemUncheckedCreateWithoutEventInput>
}

export type EventAgendaItemUpdateWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventAgendaItemWhereUniqueInput
  data: Prisma.XOR<Prisma.EventAgendaItemUpdateWithoutEventInput, Prisma.EventAgendaItemUncheckedUpdateWithoutEventInput>
}

export type EventAgendaItemUpdateManyWithWhereWithoutEventInput = {
  where: Prisma.EventAgendaItemScalarWhereInput
  data: Prisma.XOR<Prisma.EventAgendaItemUpdateManyMutationInput, Prisma.EventAgendaItemUncheckedUpdateManyWithoutEventInput>
}

export type EventAgendaItemScalarWhereInput = {
  AND?: Prisma.EventAgendaItemScalarWhereInput | Prisma.EventAgendaItemScalarWhereInput[]
  OR?: Prisma.EventAgendaItemScalarWhereInput[]
  NOT?: Prisma.EventAgendaItemScalarWhereInput | Prisma.EventAgendaItemScalarWhereInput[]
  id?: Prisma.StringFilter<"EventAgendaItem"> | string
  eventId?: Prisma.StringFilter<"EventAgendaItem"> | string
  order?: Prisma.IntFilter<"EventAgendaItem"> | number
  title?: Prisma.StringFilter<"EventAgendaItem"> | string
  description?: Prisma.StringNullableFilter<"EventAgendaItem"> | string | null
  startAt?: Prisma.DateTimeNullableFilter<"EventAgendaItem"> | Date | string | null
  endAt?: Prisma.DateTimeNullableFilter<"EventAgendaItem"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"EventAgendaItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventAgendaItem"> | Date | string
}

export type EventAgendaItemCreateWithoutHostsInput = {
  id?: string
  order?: number
  title: string
  description?: string | null
  startAt?: Date | string | null
  endAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutAgendaItemsInput
}

export type EventAgendaItemUncheckedCreateWithoutHostsInput = {
  id?: string
  eventId: string
  order?: number
  title: string
  description?: string | null
  startAt?: Date | string | null
  endAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventAgendaItemCreateOrConnectWithoutHostsInput = {
  where: Prisma.EventAgendaItemWhereUniqueInput
  create: Prisma.XOR<Prisma.EventAgendaItemCreateWithoutHostsInput, Prisma.EventAgendaItemUncheckedCreateWithoutHostsInput>
}

export type EventAgendaItemUpsertWithoutHostsInput = {
  update: Prisma.XOR<Prisma.EventAgendaItemUpdateWithoutHostsInput, Prisma.EventAgendaItemUncheckedUpdateWithoutHostsInput>
  create: Prisma.XOR<Prisma.EventAgendaItemCreateWithoutHostsInput, Prisma.EventAgendaItemUncheckedCreateWithoutHostsInput>
  where?: Prisma.EventAgendaItemWhereInput
}

export type EventAgendaItemUpdateToOneWithWhereWithoutHostsInput = {
  where?: Prisma.EventAgendaItemWhereInput
  data: Prisma.XOR<Prisma.EventAgendaItemUpdateWithoutHostsInput, Prisma.EventAgendaItemUncheckedUpdateWithoutHostsInput>
}

export type EventAgendaItemUpdateWithoutHostsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutAgendaItemsNestedInput
}

export type EventAgendaItemUncheckedUpdateWithoutHostsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventAgendaItemCreateManyEventInput = {
  id?: string
  order?: number
  title: string
  description?: string | null
  startAt?: Date | string | null
  endAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventAgendaItemUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hosts?: Prisma.EventAgendaItemHostUpdateManyWithoutAgendaItemNestedInput
}

export type EventAgendaItemUncheckedUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hosts?: Prisma.EventAgendaItemHostUncheckedUpdateManyWithoutAgendaItemNestedInput
}

export type EventAgendaItemUncheckedUpdateManyWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type EventAgendaItemCountOutputType
 */

export type EventAgendaItemCountOutputType = {
  hosts: number
}

export type EventAgendaItemCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hosts?: boolean | EventAgendaItemCountOutputTypeCountHostsArgs
}

/**
 * EventAgendaItemCountOutputType without action
 */
export type EventAgendaItemCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItemCountOutputType
   */
  select?: Prisma.EventAgendaItemCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EventAgendaItemCountOutputType without action
 */
export type EventAgendaItemCountOutputTypeCountHostsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventAgendaItemHostWhereInput
}


export type EventAgendaItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  order?: boolean
  title?: boolean
  description?: boolean
  startAt?: boolean
  endAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  hosts?: boolean | Prisma.EventAgendaItem$hostsArgs<ExtArgs>
  _count?: boolean | Prisma.EventAgendaItemCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventAgendaItem"]>

export type EventAgendaItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  order?: boolean
  title?: boolean
  description?: boolean
  startAt?: boolean
  endAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventAgendaItem"]>

export type EventAgendaItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  order?: boolean
  title?: boolean
  description?: boolean
  startAt?: boolean
  endAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventAgendaItem"]>

export type EventAgendaItemSelectScalar = {
  id?: boolean
  eventId?: boolean
  order?: boolean
  title?: boolean
  description?: boolean
  startAt?: boolean
  endAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type EventAgendaItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "eventId" | "order" | "title" | "description" | "startAt" | "endAt" | "createdAt" | "updatedAt", ExtArgs["result"]["eventAgendaItem"]>
export type EventAgendaItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  hosts?: boolean | Prisma.EventAgendaItem$hostsArgs<ExtArgs>
  _count?: boolean | Prisma.EventAgendaItemCountOutputTypeDefaultArgs<ExtArgs>
}
export type EventAgendaItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}
export type EventAgendaItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}

export type $EventAgendaItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventAgendaItem"
  objects: {
    event: Prisma.$EventPayload<ExtArgs>
    hosts: Prisma.$EventAgendaItemHostPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    eventId: string
    /**
     * Display order (0-based)
     */
    order: number
    /**
     * Required: slot title (3-120 chars)
     */
    title: string
    /**
     * Optional: slot description (max 1000 chars)
     */
    description: string | null
    /**
     * Optional: start time (UTC)
     */
    startAt: Date | null
    /**
     * Optional: end time (UTC) - must be after startAt if both are set
     */
    endAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["eventAgendaItem"]>
  composites: {}
}

export type EventAgendaItemGetPayload<S extends boolean | null | undefined | EventAgendaItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload, S>

export type EventAgendaItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventAgendaItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventAgendaItemCountAggregateInputType | true
  }

export interface EventAgendaItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventAgendaItem'], meta: { name: 'EventAgendaItem' } }
  /**
   * Find zero or one EventAgendaItem that matches the filter.
   * @param {EventAgendaItemFindUniqueArgs} args - Arguments to find a EventAgendaItem
   * @example
   * // Get one EventAgendaItem
   * const eventAgendaItem = await prisma.eventAgendaItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventAgendaItemFindUniqueArgs>(args: Prisma.SelectSubset<T, EventAgendaItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventAgendaItemClient<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventAgendaItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventAgendaItemFindUniqueOrThrowArgs} args - Arguments to find a EventAgendaItem
   * @example
   * // Get one EventAgendaItem
   * const eventAgendaItem = await prisma.eventAgendaItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventAgendaItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventAgendaItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventAgendaItemClient<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventAgendaItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventAgendaItemFindFirstArgs} args - Arguments to find a EventAgendaItem
   * @example
   * // Get one EventAgendaItem
   * const eventAgendaItem = await prisma.eventAgendaItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventAgendaItemFindFirstArgs>(args?: Prisma.SelectSubset<T, EventAgendaItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventAgendaItemClient<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventAgendaItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventAgendaItemFindFirstOrThrowArgs} args - Arguments to find a EventAgendaItem
   * @example
   * // Get one EventAgendaItem
   * const eventAgendaItem = await prisma.eventAgendaItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventAgendaItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventAgendaItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventAgendaItemClient<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventAgendaItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventAgendaItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventAgendaItems
   * const eventAgendaItems = await prisma.eventAgendaItem.findMany()
   * 
   * // Get first 10 EventAgendaItems
   * const eventAgendaItems = await prisma.eventAgendaItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventAgendaItemWithIdOnly = await prisma.eventAgendaItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventAgendaItemFindManyArgs>(args?: Prisma.SelectSubset<T, EventAgendaItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventAgendaItem.
   * @param {EventAgendaItemCreateArgs} args - Arguments to create a EventAgendaItem.
   * @example
   * // Create one EventAgendaItem
   * const EventAgendaItem = await prisma.eventAgendaItem.create({
   *   data: {
   *     // ... data to create a EventAgendaItem
   *   }
   * })
   * 
   */
  create<T extends EventAgendaItemCreateArgs>(args: Prisma.SelectSubset<T, EventAgendaItemCreateArgs<ExtArgs>>): Prisma.Prisma__EventAgendaItemClient<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventAgendaItems.
   * @param {EventAgendaItemCreateManyArgs} args - Arguments to create many EventAgendaItems.
   * @example
   * // Create many EventAgendaItems
   * const eventAgendaItem = await prisma.eventAgendaItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventAgendaItemCreateManyArgs>(args?: Prisma.SelectSubset<T, EventAgendaItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventAgendaItems and returns the data saved in the database.
   * @param {EventAgendaItemCreateManyAndReturnArgs} args - Arguments to create many EventAgendaItems.
   * @example
   * // Create many EventAgendaItems
   * const eventAgendaItem = await prisma.eventAgendaItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventAgendaItems and only return the `id`
   * const eventAgendaItemWithIdOnly = await prisma.eventAgendaItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventAgendaItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventAgendaItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventAgendaItem.
   * @param {EventAgendaItemDeleteArgs} args - Arguments to delete one EventAgendaItem.
   * @example
   * // Delete one EventAgendaItem
   * const EventAgendaItem = await prisma.eventAgendaItem.delete({
   *   where: {
   *     // ... filter to delete one EventAgendaItem
   *   }
   * })
   * 
   */
  delete<T extends EventAgendaItemDeleteArgs>(args: Prisma.SelectSubset<T, EventAgendaItemDeleteArgs<ExtArgs>>): Prisma.Prisma__EventAgendaItemClient<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventAgendaItem.
   * @param {EventAgendaItemUpdateArgs} args - Arguments to update one EventAgendaItem.
   * @example
   * // Update one EventAgendaItem
   * const eventAgendaItem = await prisma.eventAgendaItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventAgendaItemUpdateArgs>(args: Prisma.SelectSubset<T, EventAgendaItemUpdateArgs<ExtArgs>>): Prisma.Prisma__EventAgendaItemClient<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventAgendaItems.
   * @param {EventAgendaItemDeleteManyArgs} args - Arguments to filter EventAgendaItems to delete.
   * @example
   * // Delete a few EventAgendaItems
   * const { count } = await prisma.eventAgendaItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventAgendaItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventAgendaItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventAgendaItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventAgendaItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventAgendaItems
   * const eventAgendaItem = await prisma.eventAgendaItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventAgendaItemUpdateManyArgs>(args: Prisma.SelectSubset<T, EventAgendaItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventAgendaItems and returns the data updated in the database.
   * @param {EventAgendaItemUpdateManyAndReturnArgs} args - Arguments to update many EventAgendaItems.
   * @example
   * // Update many EventAgendaItems
   * const eventAgendaItem = await prisma.eventAgendaItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventAgendaItems and only return the `id`
   * const eventAgendaItemWithIdOnly = await prisma.eventAgendaItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventAgendaItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventAgendaItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventAgendaItem.
   * @param {EventAgendaItemUpsertArgs} args - Arguments to update or create a EventAgendaItem.
   * @example
   * // Update or create a EventAgendaItem
   * const eventAgendaItem = await prisma.eventAgendaItem.upsert({
   *   create: {
   *     // ... data to create a EventAgendaItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventAgendaItem we want to update
   *   }
   * })
   */
  upsert<T extends EventAgendaItemUpsertArgs>(args: Prisma.SelectSubset<T, EventAgendaItemUpsertArgs<ExtArgs>>): Prisma.Prisma__EventAgendaItemClient<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventAgendaItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventAgendaItemCountArgs} args - Arguments to filter EventAgendaItems to count.
   * @example
   * // Count the number of EventAgendaItems
   * const count = await prisma.eventAgendaItem.count({
   *   where: {
   *     // ... the filter for the EventAgendaItems we want to count
   *   }
   * })
  **/
  count<T extends EventAgendaItemCountArgs>(
    args?: Prisma.Subset<T, EventAgendaItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventAgendaItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventAgendaItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventAgendaItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventAgendaItemAggregateArgs>(args: Prisma.Subset<T, EventAgendaItemAggregateArgs>): Prisma.PrismaPromise<GetEventAgendaItemAggregateType<T>>

  /**
   * Group by EventAgendaItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventAgendaItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventAgendaItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventAgendaItemGroupByArgs['orderBy'] }
      : { orderBy?: EventAgendaItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventAgendaItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventAgendaItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventAgendaItem model
 */
readonly fields: EventAgendaItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventAgendaItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventAgendaItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  event<T extends Prisma.EventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDefaultArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  hosts<T extends Prisma.EventAgendaItem$hostsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventAgendaItem$hostsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventAgendaItemHostPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventAgendaItem model
 */
export interface EventAgendaItemFieldRefs {
  readonly id: Prisma.FieldRef<"EventAgendaItem", 'String'>
  readonly eventId: Prisma.FieldRef<"EventAgendaItem", 'String'>
  readonly order: Prisma.FieldRef<"EventAgendaItem", 'Int'>
  readonly title: Prisma.FieldRef<"EventAgendaItem", 'String'>
  readonly description: Prisma.FieldRef<"EventAgendaItem", 'String'>
  readonly startAt: Prisma.FieldRef<"EventAgendaItem", 'DateTime'>
  readonly endAt: Prisma.FieldRef<"EventAgendaItem", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"EventAgendaItem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EventAgendaItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EventAgendaItem findUnique
 */
export type EventAgendaItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemInclude<ExtArgs> | null
  /**
   * Filter, which EventAgendaItem to fetch.
   */
  where: Prisma.EventAgendaItemWhereUniqueInput
}

/**
 * EventAgendaItem findUniqueOrThrow
 */
export type EventAgendaItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemInclude<ExtArgs> | null
  /**
   * Filter, which EventAgendaItem to fetch.
   */
  where: Prisma.EventAgendaItemWhereUniqueInput
}

/**
 * EventAgendaItem findFirst
 */
export type EventAgendaItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemInclude<ExtArgs> | null
  /**
   * Filter, which EventAgendaItem to fetch.
   */
  where?: Prisma.EventAgendaItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventAgendaItems to fetch.
   */
  orderBy?: Prisma.EventAgendaItemOrderByWithRelationInput | Prisma.EventAgendaItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventAgendaItems.
   */
  cursor?: Prisma.EventAgendaItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventAgendaItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventAgendaItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventAgendaItems.
   */
  distinct?: Prisma.EventAgendaItemScalarFieldEnum | Prisma.EventAgendaItemScalarFieldEnum[]
}

/**
 * EventAgendaItem findFirstOrThrow
 */
export type EventAgendaItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemInclude<ExtArgs> | null
  /**
   * Filter, which EventAgendaItem to fetch.
   */
  where?: Prisma.EventAgendaItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventAgendaItems to fetch.
   */
  orderBy?: Prisma.EventAgendaItemOrderByWithRelationInput | Prisma.EventAgendaItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventAgendaItems.
   */
  cursor?: Prisma.EventAgendaItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventAgendaItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventAgendaItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventAgendaItems.
   */
  distinct?: Prisma.EventAgendaItemScalarFieldEnum | Prisma.EventAgendaItemScalarFieldEnum[]
}

/**
 * EventAgendaItem findMany
 */
export type EventAgendaItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemInclude<ExtArgs> | null
  /**
   * Filter, which EventAgendaItems to fetch.
   */
  where?: Prisma.EventAgendaItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventAgendaItems to fetch.
   */
  orderBy?: Prisma.EventAgendaItemOrderByWithRelationInput | Prisma.EventAgendaItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventAgendaItems.
   */
  cursor?: Prisma.EventAgendaItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventAgendaItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventAgendaItems.
   */
  skip?: number
  distinct?: Prisma.EventAgendaItemScalarFieldEnum | Prisma.EventAgendaItemScalarFieldEnum[]
}

/**
 * EventAgendaItem create
 */
export type EventAgendaItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemInclude<ExtArgs> | null
  /**
   * The data needed to create a EventAgendaItem.
   */
  data: Prisma.XOR<Prisma.EventAgendaItemCreateInput, Prisma.EventAgendaItemUncheckedCreateInput>
}

/**
 * EventAgendaItem createMany
 */
export type EventAgendaItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventAgendaItems.
   */
  data: Prisma.EventAgendaItemCreateManyInput | Prisma.EventAgendaItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EventAgendaItem createManyAndReturn
 */
export type EventAgendaItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * The data used to create many EventAgendaItems.
   */
  data: Prisma.EventAgendaItemCreateManyInput | Prisma.EventAgendaItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EventAgendaItem update
 */
export type EventAgendaItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemInclude<ExtArgs> | null
  /**
   * The data needed to update a EventAgendaItem.
   */
  data: Prisma.XOR<Prisma.EventAgendaItemUpdateInput, Prisma.EventAgendaItemUncheckedUpdateInput>
  /**
   * Choose, which EventAgendaItem to update.
   */
  where: Prisma.EventAgendaItemWhereUniqueInput
}

/**
 * EventAgendaItem updateMany
 */
export type EventAgendaItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventAgendaItems.
   */
  data: Prisma.XOR<Prisma.EventAgendaItemUpdateManyMutationInput, Prisma.EventAgendaItemUncheckedUpdateManyInput>
  /**
   * Filter which EventAgendaItems to update
   */
  where?: Prisma.EventAgendaItemWhereInput
  /**
   * Limit how many EventAgendaItems to update.
   */
  limit?: number
}

/**
 * EventAgendaItem updateManyAndReturn
 */
export type EventAgendaItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * The data used to update EventAgendaItems.
   */
  data: Prisma.XOR<Prisma.EventAgendaItemUpdateManyMutationInput, Prisma.EventAgendaItemUncheckedUpdateManyInput>
  /**
   * Filter which EventAgendaItems to update
   */
  where?: Prisma.EventAgendaItemWhereInput
  /**
   * Limit how many EventAgendaItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EventAgendaItem upsert
 */
export type EventAgendaItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemInclude<ExtArgs> | null
  /**
   * The filter to search for the EventAgendaItem to update in case it exists.
   */
  where: Prisma.EventAgendaItemWhereUniqueInput
  /**
   * In case the EventAgendaItem found by the `where` argument doesn't exist, create a new EventAgendaItem with this data.
   */
  create: Prisma.XOR<Prisma.EventAgendaItemCreateInput, Prisma.EventAgendaItemUncheckedCreateInput>
  /**
   * In case the EventAgendaItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventAgendaItemUpdateInput, Prisma.EventAgendaItemUncheckedUpdateInput>
}

/**
 * EventAgendaItem delete
 */
export type EventAgendaItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemInclude<ExtArgs> | null
  /**
   * Filter which EventAgendaItem to delete.
   */
  where: Prisma.EventAgendaItemWhereUniqueInput
}

/**
 * EventAgendaItem deleteMany
 */
export type EventAgendaItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventAgendaItems to delete
   */
  where?: Prisma.EventAgendaItemWhereInput
  /**
   * Limit how many EventAgendaItems to delete.
   */
  limit?: number
}

/**
 * EventAgendaItem.hosts
 */
export type EventAgendaItem$hostsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItemHost
   */
  select?: Prisma.EventAgendaItemHostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItemHost
   */
  omit?: Prisma.EventAgendaItemHostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemHostInclude<ExtArgs> | null
  where?: Prisma.EventAgendaItemHostWhereInput
  orderBy?: Prisma.EventAgendaItemHostOrderByWithRelationInput | Prisma.EventAgendaItemHostOrderByWithRelationInput[]
  cursor?: Prisma.EventAgendaItemHostWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EventAgendaItemHostScalarFieldEnum | Prisma.EventAgendaItemHostScalarFieldEnum[]
}

/**
 * EventAgendaItem without action
 */
export type EventAgendaItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventAgendaItem
   */
  select?: Prisma.EventAgendaItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventAgendaItem
   */
  omit?: Prisma.EventAgendaItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventAgendaItemInclude<ExtArgs> | null
}
