
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `EventJoinAnswer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model EventJoinAnswer
 * 
 */
export type EventJoinAnswerModel = runtime.Types.Result.DefaultSelection<Prisma.$EventJoinAnswerPayload>

export type AggregateEventJoinAnswer = {
  _count: EventJoinAnswerCountAggregateOutputType | null
  _min: EventJoinAnswerMinAggregateOutputType | null
  _max: EventJoinAnswerMaxAggregateOutputType | null
}

export type EventJoinAnswerMinAggregateOutputType = {
  id: string | null
  eventId: string | null
  userId: string | null
  questionId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventJoinAnswerMaxAggregateOutputType = {
  id: string | null
  eventId: string | null
  userId: string | null
  questionId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventJoinAnswerCountAggregateOutputType = {
  id: number
  eventId: number
  userId: number
  questionId: number
  answer: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type EventJoinAnswerMinAggregateInputType = {
  id?: true
  eventId?: true
  userId?: true
  questionId?: true
  createdAt?: true
  updatedAt?: true
}

export type EventJoinAnswerMaxAggregateInputType = {
  id?: true
  eventId?: true
  userId?: true
  questionId?: true
  createdAt?: true
  updatedAt?: true
}

export type EventJoinAnswerCountAggregateInputType = {
  id?: true
  eventId?: true
  userId?: true
  questionId?: true
  answer?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type EventJoinAnswerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventJoinAnswer to aggregate.
   */
  where?: Prisma.EventJoinAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventJoinAnswers to fetch.
   */
  orderBy?: Prisma.EventJoinAnswerOrderByWithRelationInput | Prisma.EventJoinAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventJoinAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventJoinAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventJoinAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventJoinAnswers
  **/
  _count?: true | EventJoinAnswerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventJoinAnswerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventJoinAnswerMaxAggregateInputType
}

export type GetEventJoinAnswerAggregateType<T extends EventJoinAnswerAggregateArgs> = {
      [P in keyof T & keyof AggregateEventJoinAnswer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventJoinAnswer[P]>
    : Prisma.GetScalarType<T[P], AggregateEventJoinAnswer[P]>
}




export type EventJoinAnswerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventJoinAnswerWhereInput
  orderBy?: Prisma.EventJoinAnswerOrderByWithAggregationInput | Prisma.EventJoinAnswerOrderByWithAggregationInput[]
  by: Prisma.EventJoinAnswerScalarFieldEnum[] | Prisma.EventJoinAnswerScalarFieldEnum
  having?: Prisma.EventJoinAnswerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventJoinAnswerCountAggregateInputType | true
  _min?: EventJoinAnswerMinAggregateInputType
  _max?: EventJoinAnswerMaxAggregateInputType
}

export type EventJoinAnswerGroupByOutputType = {
  id: string
  eventId: string
  userId: string
  questionId: string
  answer: runtime.JsonValue
  createdAt: Date
  updatedAt: Date
  _count: EventJoinAnswerCountAggregateOutputType | null
  _min: EventJoinAnswerMinAggregateOutputType | null
  _max: EventJoinAnswerMaxAggregateOutputType | null
}

type GetEventJoinAnswerGroupByPayload<T extends EventJoinAnswerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventJoinAnswerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventJoinAnswerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventJoinAnswerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventJoinAnswerGroupByOutputType[P]>
      }
    >
  >



export type EventJoinAnswerWhereInput = {
  AND?: Prisma.EventJoinAnswerWhereInput | Prisma.EventJoinAnswerWhereInput[]
  OR?: Prisma.EventJoinAnswerWhereInput[]
  NOT?: Prisma.EventJoinAnswerWhereInput | Prisma.EventJoinAnswerWhereInput[]
  id?: Prisma.StringFilter<"EventJoinAnswer"> | string
  eventId?: Prisma.StringFilter<"EventJoinAnswer"> | string
  userId?: Prisma.StringFilter<"EventJoinAnswer"> | string
  questionId?: Prisma.StringFilter<"EventJoinAnswer"> | string
  answer?: Prisma.JsonFilter<"EventJoinAnswer">
  createdAt?: Prisma.DateTimeFilter<"EventJoinAnswer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventJoinAnswer"> | Date | string
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  question?: Prisma.XOR<Prisma.EventJoinQuestionScalarRelationFilter, Prisma.EventJoinQuestionWhereInput>
  member?: Prisma.XOR<Prisma.EventMemberScalarRelationFilter, Prisma.EventMemberWhereInput>
}

export type EventJoinAnswerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  answer?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  event?: Prisma.EventOrderByWithRelationInput
  question?: Prisma.EventJoinQuestionOrderByWithRelationInput
  member?: Prisma.EventMemberOrderByWithRelationInput
}

export type EventJoinAnswerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  eventId_userId_questionId?: Prisma.EventJoinAnswerEventIdUserIdQuestionIdCompoundUniqueInput
  AND?: Prisma.EventJoinAnswerWhereInput | Prisma.EventJoinAnswerWhereInput[]
  OR?: Prisma.EventJoinAnswerWhereInput[]
  NOT?: Prisma.EventJoinAnswerWhereInput | Prisma.EventJoinAnswerWhereInput[]
  eventId?: Prisma.StringFilter<"EventJoinAnswer"> | string
  userId?: Prisma.StringFilter<"EventJoinAnswer"> | string
  questionId?: Prisma.StringFilter<"EventJoinAnswer"> | string
  answer?: Prisma.JsonFilter<"EventJoinAnswer">
  createdAt?: Prisma.DateTimeFilter<"EventJoinAnswer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventJoinAnswer"> | Date | string
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  question?: Prisma.XOR<Prisma.EventJoinQuestionScalarRelationFilter, Prisma.EventJoinQuestionWhereInput>
  member?: Prisma.XOR<Prisma.EventMemberScalarRelationFilter, Prisma.EventMemberWhereInput>
}, "id" | "eventId_userId_questionId">

export type EventJoinAnswerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  answer?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.EventJoinAnswerCountOrderByAggregateInput
  _max?: Prisma.EventJoinAnswerMaxOrderByAggregateInput
  _min?: Prisma.EventJoinAnswerMinOrderByAggregateInput
}

export type EventJoinAnswerScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventJoinAnswerScalarWhereWithAggregatesInput | Prisma.EventJoinAnswerScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventJoinAnswerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventJoinAnswerScalarWhereWithAggregatesInput | Prisma.EventJoinAnswerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EventJoinAnswer"> | string
  eventId?: Prisma.StringWithAggregatesFilter<"EventJoinAnswer"> | string
  userId?: Prisma.StringWithAggregatesFilter<"EventJoinAnswer"> | string
  questionId?: Prisma.StringWithAggregatesFilter<"EventJoinAnswer"> | string
  answer?: Prisma.JsonWithAggregatesFilter<"EventJoinAnswer">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventJoinAnswer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EventJoinAnswer"> | Date | string
}

export type EventJoinAnswerCreateInput = {
  id?: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutJoinAnswersInput
  question: Prisma.EventJoinQuestionCreateNestedOneWithoutAnswersInput
  member: Prisma.EventMemberCreateNestedOneWithoutJoinAnswersInput
}

export type EventJoinAnswerUncheckedCreateInput = {
  id?: string
  eventId: string
  userId: string
  questionId: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventJoinAnswerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutJoinAnswersNestedInput
  question?: Prisma.EventJoinQuestionUpdateOneRequiredWithoutAnswersNestedInput
  member?: Prisma.EventMemberUpdateOneRequiredWithoutJoinAnswersNestedInput
}

export type EventJoinAnswerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventJoinAnswerCreateManyInput = {
  id?: string
  eventId: string
  userId: string
  questionId: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventJoinAnswerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventJoinAnswerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventJoinAnswerListRelationFilter = {
  every?: Prisma.EventJoinAnswerWhereInput
  some?: Prisma.EventJoinAnswerWhereInput
  none?: Prisma.EventJoinAnswerWhereInput
}

export type EventJoinAnswerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EventJoinAnswerEventIdUserIdQuestionIdCompoundUniqueInput = {
  eventId: string
  userId: string
  questionId: string
}

export type EventJoinAnswerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  answer?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventJoinAnswerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventJoinAnswerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventJoinAnswerCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutEventInput, Prisma.EventJoinAnswerUncheckedCreateWithoutEventInput> | Prisma.EventJoinAnswerCreateWithoutEventInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutEventInput | Prisma.EventJoinAnswerCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyEventInputEnvelope
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
}

export type EventJoinAnswerUncheckedCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutEventInput, Prisma.EventJoinAnswerUncheckedCreateWithoutEventInput> | Prisma.EventJoinAnswerCreateWithoutEventInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutEventInput | Prisma.EventJoinAnswerCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyEventInputEnvelope
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
}

export type EventJoinAnswerUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutEventInput, Prisma.EventJoinAnswerUncheckedCreateWithoutEventInput> | Prisma.EventJoinAnswerCreateWithoutEventInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutEventInput | Prisma.EventJoinAnswerCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutEventInput | Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyEventInputEnvelope
  set?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  disconnect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  delete?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  update?: Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutEventInput | Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventJoinAnswerUpdateManyWithWhereWithoutEventInput | Prisma.EventJoinAnswerUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventJoinAnswerScalarWhereInput | Prisma.EventJoinAnswerScalarWhereInput[]
}

export type EventJoinAnswerUncheckedUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutEventInput, Prisma.EventJoinAnswerUncheckedCreateWithoutEventInput> | Prisma.EventJoinAnswerCreateWithoutEventInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutEventInput | Prisma.EventJoinAnswerCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutEventInput | Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyEventInputEnvelope
  set?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  disconnect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  delete?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  update?: Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutEventInput | Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventJoinAnswerUpdateManyWithWhereWithoutEventInput | Prisma.EventJoinAnswerUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventJoinAnswerScalarWhereInput | Prisma.EventJoinAnswerScalarWhereInput[]
}

export type EventJoinAnswerCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutMemberInput, Prisma.EventJoinAnswerUncheckedCreateWithoutMemberInput> | Prisma.EventJoinAnswerCreateWithoutMemberInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutMemberInput | Prisma.EventJoinAnswerCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyMemberInputEnvelope
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
}

export type EventJoinAnswerUncheckedCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutMemberInput, Prisma.EventJoinAnswerUncheckedCreateWithoutMemberInput> | Prisma.EventJoinAnswerCreateWithoutMemberInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutMemberInput | Prisma.EventJoinAnswerCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyMemberInputEnvelope
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
}

export type EventJoinAnswerUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutMemberInput, Prisma.EventJoinAnswerUncheckedCreateWithoutMemberInput> | Prisma.EventJoinAnswerCreateWithoutMemberInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutMemberInput | Prisma.EventJoinAnswerCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutMemberInput | Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyMemberInputEnvelope
  set?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  disconnect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  delete?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  update?: Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutMemberInput | Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.EventJoinAnswerUpdateManyWithWhereWithoutMemberInput | Prisma.EventJoinAnswerUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.EventJoinAnswerScalarWhereInput | Prisma.EventJoinAnswerScalarWhereInput[]
}

export type EventJoinAnswerUncheckedUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutMemberInput, Prisma.EventJoinAnswerUncheckedCreateWithoutMemberInput> | Prisma.EventJoinAnswerCreateWithoutMemberInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutMemberInput | Prisma.EventJoinAnswerCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutMemberInput | Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyMemberInputEnvelope
  set?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  disconnect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  delete?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  update?: Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutMemberInput | Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.EventJoinAnswerUpdateManyWithWhereWithoutMemberInput | Prisma.EventJoinAnswerUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.EventJoinAnswerScalarWhereInput | Prisma.EventJoinAnswerScalarWhereInput[]
}

export type EventJoinAnswerCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutQuestionInput, Prisma.EventJoinAnswerUncheckedCreateWithoutQuestionInput> | Prisma.EventJoinAnswerCreateWithoutQuestionInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutQuestionInput | Prisma.EventJoinAnswerCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyQuestionInputEnvelope
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
}

export type EventJoinAnswerUncheckedCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutQuestionInput, Prisma.EventJoinAnswerUncheckedCreateWithoutQuestionInput> | Prisma.EventJoinAnswerCreateWithoutQuestionInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutQuestionInput | Prisma.EventJoinAnswerCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyQuestionInputEnvelope
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
}

export type EventJoinAnswerUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutQuestionInput, Prisma.EventJoinAnswerUncheckedCreateWithoutQuestionInput> | Prisma.EventJoinAnswerCreateWithoutQuestionInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutQuestionInput | Prisma.EventJoinAnswerCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutQuestionInput | Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyQuestionInputEnvelope
  set?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  disconnect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  delete?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  update?: Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutQuestionInput | Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.EventJoinAnswerUpdateManyWithWhereWithoutQuestionInput | Prisma.EventJoinAnswerUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.EventJoinAnswerScalarWhereInput | Prisma.EventJoinAnswerScalarWhereInput[]
}

export type EventJoinAnswerUncheckedUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutQuestionInput, Prisma.EventJoinAnswerUncheckedCreateWithoutQuestionInput> | Prisma.EventJoinAnswerCreateWithoutQuestionInput[] | Prisma.EventJoinAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.EventJoinAnswerCreateOrConnectWithoutQuestionInput | Prisma.EventJoinAnswerCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutQuestionInput | Prisma.EventJoinAnswerUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.EventJoinAnswerCreateManyQuestionInputEnvelope
  set?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  disconnect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  delete?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  connect?: Prisma.EventJoinAnswerWhereUniqueInput | Prisma.EventJoinAnswerWhereUniqueInput[]
  update?: Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutQuestionInput | Prisma.EventJoinAnswerUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.EventJoinAnswerUpdateManyWithWhereWithoutQuestionInput | Prisma.EventJoinAnswerUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.EventJoinAnswerScalarWhereInput | Prisma.EventJoinAnswerScalarWhereInput[]
}

export type EventJoinAnswerCreateWithoutEventInput = {
  id?: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  question: Prisma.EventJoinQuestionCreateNestedOneWithoutAnswersInput
  member: Prisma.EventMemberCreateNestedOneWithoutJoinAnswersInput
}

export type EventJoinAnswerUncheckedCreateWithoutEventInput = {
  id?: string
  userId: string
  questionId: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventJoinAnswerCreateOrConnectWithoutEventInput = {
  where: Prisma.EventJoinAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutEventInput, Prisma.EventJoinAnswerUncheckedCreateWithoutEventInput>
}

export type EventJoinAnswerCreateManyEventInputEnvelope = {
  data: Prisma.EventJoinAnswerCreateManyEventInput | Prisma.EventJoinAnswerCreateManyEventInput[]
  skipDuplicates?: boolean
}

export type EventJoinAnswerUpsertWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventJoinAnswerWhereUniqueInput
  update: Prisma.XOR<Prisma.EventJoinAnswerUpdateWithoutEventInput, Prisma.EventJoinAnswerUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutEventInput, Prisma.EventJoinAnswerUncheckedCreateWithoutEventInput>
}

export type EventJoinAnswerUpdateWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventJoinAnswerWhereUniqueInput
  data: Prisma.XOR<Prisma.EventJoinAnswerUpdateWithoutEventInput, Prisma.EventJoinAnswerUncheckedUpdateWithoutEventInput>
}

export type EventJoinAnswerUpdateManyWithWhereWithoutEventInput = {
  where: Prisma.EventJoinAnswerScalarWhereInput
  data: Prisma.XOR<Prisma.EventJoinAnswerUpdateManyMutationInput, Prisma.EventJoinAnswerUncheckedUpdateManyWithoutEventInput>
}

export type EventJoinAnswerScalarWhereInput = {
  AND?: Prisma.EventJoinAnswerScalarWhereInput | Prisma.EventJoinAnswerScalarWhereInput[]
  OR?: Prisma.EventJoinAnswerScalarWhereInput[]
  NOT?: Prisma.EventJoinAnswerScalarWhereInput | Prisma.EventJoinAnswerScalarWhereInput[]
  id?: Prisma.StringFilter<"EventJoinAnswer"> | string
  eventId?: Prisma.StringFilter<"EventJoinAnswer"> | string
  userId?: Prisma.StringFilter<"EventJoinAnswer"> | string
  questionId?: Prisma.StringFilter<"EventJoinAnswer"> | string
  answer?: Prisma.JsonFilter<"EventJoinAnswer">
  createdAt?: Prisma.DateTimeFilter<"EventJoinAnswer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventJoinAnswer"> | Date | string
}

export type EventJoinAnswerCreateWithoutMemberInput = {
  id?: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutJoinAnswersInput
  question: Prisma.EventJoinQuestionCreateNestedOneWithoutAnswersInput
}

export type EventJoinAnswerUncheckedCreateWithoutMemberInput = {
  id?: string
  questionId: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventJoinAnswerCreateOrConnectWithoutMemberInput = {
  where: Prisma.EventJoinAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutMemberInput, Prisma.EventJoinAnswerUncheckedCreateWithoutMemberInput>
}

export type EventJoinAnswerCreateManyMemberInputEnvelope = {
  data: Prisma.EventJoinAnswerCreateManyMemberInput | Prisma.EventJoinAnswerCreateManyMemberInput[]
  skipDuplicates?: boolean
}

export type EventJoinAnswerUpsertWithWhereUniqueWithoutMemberInput = {
  where: Prisma.EventJoinAnswerWhereUniqueInput
  update: Prisma.XOR<Prisma.EventJoinAnswerUpdateWithoutMemberInput, Prisma.EventJoinAnswerUncheckedUpdateWithoutMemberInput>
  create: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutMemberInput, Prisma.EventJoinAnswerUncheckedCreateWithoutMemberInput>
}

export type EventJoinAnswerUpdateWithWhereUniqueWithoutMemberInput = {
  where: Prisma.EventJoinAnswerWhereUniqueInput
  data: Prisma.XOR<Prisma.EventJoinAnswerUpdateWithoutMemberInput, Prisma.EventJoinAnswerUncheckedUpdateWithoutMemberInput>
}

export type EventJoinAnswerUpdateManyWithWhereWithoutMemberInput = {
  where: Prisma.EventJoinAnswerScalarWhereInput
  data: Prisma.XOR<Prisma.EventJoinAnswerUpdateManyMutationInput, Prisma.EventJoinAnswerUncheckedUpdateManyWithoutMemberInput>
}

export type EventJoinAnswerCreateWithoutQuestionInput = {
  id?: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutJoinAnswersInput
  member: Prisma.EventMemberCreateNestedOneWithoutJoinAnswersInput
}

export type EventJoinAnswerUncheckedCreateWithoutQuestionInput = {
  id?: string
  eventId: string
  userId: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventJoinAnswerCreateOrConnectWithoutQuestionInput = {
  where: Prisma.EventJoinAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutQuestionInput, Prisma.EventJoinAnswerUncheckedCreateWithoutQuestionInput>
}

export type EventJoinAnswerCreateManyQuestionInputEnvelope = {
  data: Prisma.EventJoinAnswerCreateManyQuestionInput | Prisma.EventJoinAnswerCreateManyQuestionInput[]
  skipDuplicates?: boolean
}

export type EventJoinAnswerUpsertWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.EventJoinAnswerWhereUniqueInput
  update: Prisma.XOR<Prisma.EventJoinAnswerUpdateWithoutQuestionInput, Prisma.EventJoinAnswerUncheckedUpdateWithoutQuestionInput>
  create: Prisma.XOR<Prisma.EventJoinAnswerCreateWithoutQuestionInput, Prisma.EventJoinAnswerUncheckedCreateWithoutQuestionInput>
}

export type EventJoinAnswerUpdateWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.EventJoinAnswerWhereUniqueInput
  data: Prisma.XOR<Prisma.EventJoinAnswerUpdateWithoutQuestionInput, Prisma.EventJoinAnswerUncheckedUpdateWithoutQuestionInput>
}

export type EventJoinAnswerUpdateManyWithWhereWithoutQuestionInput = {
  where: Prisma.EventJoinAnswerScalarWhereInput
  data: Prisma.XOR<Prisma.EventJoinAnswerUpdateManyMutationInput, Prisma.EventJoinAnswerUncheckedUpdateManyWithoutQuestionInput>
}

export type EventJoinAnswerCreateManyEventInput = {
  id?: string
  userId: string
  questionId: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventJoinAnswerUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question?: Prisma.EventJoinQuestionUpdateOneRequiredWithoutAnswersNestedInput
  member?: Prisma.EventMemberUpdateOneRequiredWithoutJoinAnswersNestedInput
}

export type EventJoinAnswerUncheckedUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventJoinAnswerUncheckedUpdateManyWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventJoinAnswerCreateManyMemberInput = {
  id?: string
  questionId: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventJoinAnswerUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutJoinAnswersNestedInput
  question?: Prisma.EventJoinQuestionUpdateOneRequiredWithoutAnswersNestedInput
}

export type EventJoinAnswerUncheckedUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventJoinAnswerUncheckedUpdateManyWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventJoinAnswerCreateManyQuestionInput = {
  id?: string
  eventId: string
  userId: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventJoinAnswerUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutJoinAnswersNestedInput
  member?: Prisma.EventMemberUpdateOneRequiredWithoutJoinAnswersNestedInput
}

export type EventJoinAnswerUncheckedUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventJoinAnswerUncheckedUpdateManyWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type EventJoinAnswerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  userId?: boolean
  questionId?: boolean
  answer?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  question?: boolean | Prisma.EventJoinQuestionDefaultArgs<ExtArgs>
  member?: boolean | Prisma.EventMemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventJoinAnswer"]>

export type EventJoinAnswerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  userId?: boolean
  questionId?: boolean
  answer?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  question?: boolean | Prisma.EventJoinQuestionDefaultArgs<ExtArgs>
  member?: boolean | Prisma.EventMemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventJoinAnswer"]>

export type EventJoinAnswerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  userId?: boolean
  questionId?: boolean
  answer?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  question?: boolean | Prisma.EventJoinQuestionDefaultArgs<ExtArgs>
  member?: boolean | Prisma.EventMemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventJoinAnswer"]>

export type EventJoinAnswerSelectScalar = {
  id?: boolean
  eventId?: boolean
  userId?: boolean
  questionId?: boolean
  answer?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type EventJoinAnswerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "eventId" | "userId" | "questionId" | "answer" | "createdAt" | "updatedAt", ExtArgs["result"]["eventJoinAnswer"]>
export type EventJoinAnswerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  question?: boolean | Prisma.EventJoinQuestionDefaultArgs<ExtArgs>
  member?: boolean | Prisma.EventMemberDefaultArgs<ExtArgs>
}
export type EventJoinAnswerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  question?: boolean | Prisma.EventJoinQuestionDefaultArgs<ExtArgs>
  member?: boolean | Prisma.EventMemberDefaultArgs<ExtArgs>
}
export type EventJoinAnswerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  question?: boolean | Prisma.EventJoinQuestionDefaultArgs<ExtArgs>
  member?: boolean | Prisma.EventMemberDefaultArgs<ExtArgs>
}

export type $EventJoinAnswerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventJoinAnswer"
  objects: {
    event: Prisma.$EventPayload<ExtArgs>
    question: Prisma.$EventJoinQuestionPayload<ExtArgs>
    member: Prisma.$EventMemberPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    eventId: string
    userId: string
    questionId: string
    answer: runtime.JsonValue
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["eventJoinAnswer"]>
  composites: {}
}

export type EventJoinAnswerGetPayload<S extends boolean | null | undefined | EventJoinAnswerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload, S>

export type EventJoinAnswerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventJoinAnswerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventJoinAnswerCountAggregateInputType | true
  }

export interface EventJoinAnswerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventJoinAnswer'], meta: { name: 'EventJoinAnswer' } }
  /**
   * Find zero or one EventJoinAnswer that matches the filter.
   * @param {EventJoinAnswerFindUniqueArgs} args - Arguments to find a EventJoinAnswer
   * @example
   * // Get one EventJoinAnswer
   * const eventJoinAnswer = await prisma.eventJoinAnswer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventJoinAnswerFindUniqueArgs>(args: Prisma.SelectSubset<T, EventJoinAnswerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventJoinAnswerClient<runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventJoinAnswer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventJoinAnswerFindUniqueOrThrowArgs} args - Arguments to find a EventJoinAnswer
   * @example
   * // Get one EventJoinAnswer
   * const eventJoinAnswer = await prisma.eventJoinAnswer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventJoinAnswerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventJoinAnswerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventJoinAnswerClient<runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventJoinAnswer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventJoinAnswerFindFirstArgs} args - Arguments to find a EventJoinAnswer
   * @example
   * // Get one EventJoinAnswer
   * const eventJoinAnswer = await prisma.eventJoinAnswer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventJoinAnswerFindFirstArgs>(args?: Prisma.SelectSubset<T, EventJoinAnswerFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventJoinAnswerClient<runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventJoinAnswer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventJoinAnswerFindFirstOrThrowArgs} args - Arguments to find a EventJoinAnswer
   * @example
   * // Get one EventJoinAnswer
   * const eventJoinAnswer = await prisma.eventJoinAnswer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventJoinAnswerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventJoinAnswerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventJoinAnswerClient<runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventJoinAnswers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventJoinAnswerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventJoinAnswers
   * const eventJoinAnswers = await prisma.eventJoinAnswer.findMany()
   * 
   * // Get first 10 EventJoinAnswers
   * const eventJoinAnswers = await prisma.eventJoinAnswer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventJoinAnswerWithIdOnly = await prisma.eventJoinAnswer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventJoinAnswerFindManyArgs>(args?: Prisma.SelectSubset<T, EventJoinAnswerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventJoinAnswer.
   * @param {EventJoinAnswerCreateArgs} args - Arguments to create a EventJoinAnswer.
   * @example
   * // Create one EventJoinAnswer
   * const EventJoinAnswer = await prisma.eventJoinAnswer.create({
   *   data: {
   *     // ... data to create a EventJoinAnswer
   *   }
   * })
   * 
   */
  create<T extends EventJoinAnswerCreateArgs>(args: Prisma.SelectSubset<T, EventJoinAnswerCreateArgs<ExtArgs>>): Prisma.Prisma__EventJoinAnswerClient<runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventJoinAnswers.
   * @param {EventJoinAnswerCreateManyArgs} args - Arguments to create many EventJoinAnswers.
   * @example
   * // Create many EventJoinAnswers
   * const eventJoinAnswer = await prisma.eventJoinAnswer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventJoinAnswerCreateManyArgs>(args?: Prisma.SelectSubset<T, EventJoinAnswerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventJoinAnswers and returns the data saved in the database.
   * @param {EventJoinAnswerCreateManyAndReturnArgs} args - Arguments to create many EventJoinAnswers.
   * @example
   * // Create many EventJoinAnswers
   * const eventJoinAnswer = await prisma.eventJoinAnswer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventJoinAnswers and only return the `id`
   * const eventJoinAnswerWithIdOnly = await prisma.eventJoinAnswer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventJoinAnswerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventJoinAnswerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventJoinAnswer.
   * @param {EventJoinAnswerDeleteArgs} args - Arguments to delete one EventJoinAnswer.
   * @example
   * // Delete one EventJoinAnswer
   * const EventJoinAnswer = await prisma.eventJoinAnswer.delete({
   *   where: {
   *     // ... filter to delete one EventJoinAnswer
   *   }
   * })
   * 
   */
  delete<T extends EventJoinAnswerDeleteArgs>(args: Prisma.SelectSubset<T, EventJoinAnswerDeleteArgs<ExtArgs>>): Prisma.Prisma__EventJoinAnswerClient<runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventJoinAnswer.
   * @param {EventJoinAnswerUpdateArgs} args - Arguments to update one EventJoinAnswer.
   * @example
   * // Update one EventJoinAnswer
   * const eventJoinAnswer = await prisma.eventJoinAnswer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventJoinAnswerUpdateArgs>(args: Prisma.SelectSubset<T, EventJoinAnswerUpdateArgs<ExtArgs>>): Prisma.Prisma__EventJoinAnswerClient<runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventJoinAnswers.
   * @param {EventJoinAnswerDeleteManyArgs} args - Arguments to filter EventJoinAnswers to delete.
   * @example
   * // Delete a few EventJoinAnswers
   * const { count } = await prisma.eventJoinAnswer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventJoinAnswerDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventJoinAnswerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventJoinAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventJoinAnswerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventJoinAnswers
   * const eventJoinAnswer = await prisma.eventJoinAnswer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventJoinAnswerUpdateManyArgs>(args: Prisma.SelectSubset<T, EventJoinAnswerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventJoinAnswers and returns the data updated in the database.
   * @param {EventJoinAnswerUpdateManyAndReturnArgs} args - Arguments to update many EventJoinAnswers.
   * @example
   * // Update many EventJoinAnswers
   * const eventJoinAnswer = await prisma.eventJoinAnswer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventJoinAnswers and only return the `id`
   * const eventJoinAnswerWithIdOnly = await prisma.eventJoinAnswer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventJoinAnswerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventJoinAnswerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventJoinAnswer.
   * @param {EventJoinAnswerUpsertArgs} args - Arguments to update or create a EventJoinAnswer.
   * @example
   * // Update or create a EventJoinAnswer
   * const eventJoinAnswer = await prisma.eventJoinAnswer.upsert({
   *   create: {
   *     // ... data to create a EventJoinAnswer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventJoinAnswer we want to update
   *   }
   * })
   */
  upsert<T extends EventJoinAnswerUpsertArgs>(args: Prisma.SelectSubset<T, EventJoinAnswerUpsertArgs<ExtArgs>>): Prisma.Prisma__EventJoinAnswerClient<runtime.Types.Result.GetResult<Prisma.$EventJoinAnswerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventJoinAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventJoinAnswerCountArgs} args - Arguments to filter EventJoinAnswers to count.
   * @example
   * // Count the number of EventJoinAnswers
   * const count = await prisma.eventJoinAnswer.count({
   *   where: {
   *     // ... the filter for the EventJoinAnswers we want to count
   *   }
   * })
  **/
  count<T extends EventJoinAnswerCountArgs>(
    args?: Prisma.Subset<T, EventJoinAnswerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventJoinAnswerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventJoinAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventJoinAnswerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventJoinAnswerAggregateArgs>(args: Prisma.Subset<T, EventJoinAnswerAggregateArgs>): Prisma.PrismaPromise<GetEventJoinAnswerAggregateType<T>>

  /**
   * Group by EventJoinAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventJoinAnswerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventJoinAnswerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventJoinAnswerGroupByArgs['orderBy'] }
      : { orderBy?: EventJoinAnswerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventJoinAnswerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventJoinAnswerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventJoinAnswer model
 */
readonly fields: EventJoinAnswerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventJoinAnswer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventJoinAnswerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  event<T extends Prisma.EventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDefaultArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  question<T extends Prisma.EventJoinQuestionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventJoinQuestionDefaultArgs<ExtArgs>>): Prisma.Prisma__EventJoinQuestionClient<runtime.Types.Result.GetResult<Prisma.$EventJoinQuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  member<T extends Prisma.EventMemberDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventMemberDefaultArgs<ExtArgs>>): Prisma.Prisma__EventMemberClient<runtime.Types.Result.GetResult<Prisma.$EventMemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventJoinAnswer model
 */
export interface EventJoinAnswerFieldRefs {
  readonly id: Prisma.FieldRef<"EventJoinAnswer", 'String'>
  readonly eventId: Prisma.FieldRef<"EventJoinAnswer", 'String'>
  readonly userId: Prisma.FieldRef<"EventJoinAnswer", 'String'>
  readonly questionId: Prisma.FieldRef<"EventJoinAnswer", 'String'>
  readonly answer: Prisma.FieldRef<"EventJoinAnswer", 'Json'>
  readonly createdAt: Prisma.FieldRef<"EventJoinAnswer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EventJoinAnswer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EventJoinAnswer findUnique
 */
export type EventJoinAnswerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerInclude<ExtArgs> | null
  /**
   * Filter, which EventJoinAnswer to fetch.
   */
  where: Prisma.EventJoinAnswerWhereUniqueInput
}

/**
 * EventJoinAnswer findUniqueOrThrow
 */
export type EventJoinAnswerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerInclude<ExtArgs> | null
  /**
   * Filter, which EventJoinAnswer to fetch.
   */
  where: Prisma.EventJoinAnswerWhereUniqueInput
}

/**
 * EventJoinAnswer findFirst
 */
export type EventJoinAnswerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerInclude<ExtArgs> | null
  /**
   * Filter, which EventJoinAnswer to fetch.
   */
  where?: Prisma.EventJoinAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventJoinAnswers to fetch.
   */
  orderBy?: Prisma.EventJoinAnswerOrderByWithRelationInput | Prisma.EventJoinAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventJoinAnswers.
   */
  cursor?: Prisma.EventJoinAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventJoinAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventJoinAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventJoinAnswers.
   */
  distinct?: Prisma.EventJoinAnswerScalarFieldEnum | Prisma.EventJoinAnswerScalarFieldEnum[]
}

/**
 * EventJoinAnswer findFirstOrThrow
 */
export type EventJoinAnswerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerInclude<ExtArgs> | null
  /**
   * Filter, which EventJoinAnswer to fetch.
   */
  where?: Prisma.EventJoinAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventJoinAnswers to fetch.
   */
  orderBy?: Prisma.EventJoinAnswerOrderByWithRelationInput | Prisma.EventJoinAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventJoinAnswers.
   */
  cursor?: Prisma.EventJoinAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventJoinAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventJoinAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventJoinAnswers.
   */
  distinct?: Prisma.EventJoinAnswerScalarFieldEnum | Prisma.EventJoinAnswerScalarFieldEnum[]
}

/**
 * EventJoinAnswer findMany
 */
export type EventJoinAnswerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerInclude<ExtArgs> | null
  /**
   * Filter, which EventJoinAnswers to fetch.
   */
  where?: Prisma.EventJoinAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventJoinAnswers to fetch.
   */
  orderBy?: Prisma.EventJoinAnswerOrderByWithRelationInput | Prisma.EventJoinAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventJoinAnswers.
   */
  cursor?: Prisma.EventJoinAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventJoinAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventJoinAnswers.
   */
  skip?: number
  distinct?: Prisma.EventJoinAnswerScalarFieldEnum | Prisma.EventJoinAnswerScalarFieldEnum[]
}

/**
 * EventJoinAnswer create
 */
export type EventJoinAnswerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerInclude<ExtArgs> | null
  /**
   * The data needed to create a EventJoinAnswer.
   */
  data: Prisma.XOR<Prisma.EventJoinAnswerCreateInput, Prisma.EventJoinAnswerUncheckedCreateInput>
}

/**
 * EventJoinAnswer createMany
 */
export type EventJoinAnswerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventJoinAnswers.
   */
  data: Prisma.EventJoinAnswerCreateManyInput | Prisma.EventJoinAnswerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EventJoinAnswer createManyAndReturn
 */
export type EventJoinAnswerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * The data used to create many EventJoinAnswers.
   */
  data: Prisma.EventJoinAnswerCreateManyInput | Prisma.EventJoinAnswerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EventJoinAnswer update
 */
export type EventJoinAnswerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerInclude<ExtArgs> | null
  /**
   * The data needed to update a EventJoinAnswer.
   */
  data: Prisma.XOR<Prisma.EventJoinAnswerUpdateInput, Prisma.EventJoinAnswerUncheckedUpdateInput>
  /**
   * Choose, which EventJoinAnswer to update.
   */
  where: Prisma.EventJoinAnswerWhereUniqueInput
}

/**
 * EventJoinAnswer updateMany
 */
export type EventJoinAnswerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventJoinAnswers.
   */
  data: Prisma.XOR<Prisma.EventJoinAnswerUpdateManyMutationInput, Prisma.EventJoinAnswerUncheckedUpdateManyInput>
  /**
   * Filter which EventJoinAnswers to update
   */
  where?: Prisma.EventJoinAnswerWhereInput
  /**
   * Limit how many EventJoinAnswers to update.
   */
  limit?: number
}

/**
 * EventJoinAnswer updateManyAndReturn
 */
export type EventJoinAnswerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * The data used to update EventJoinAnswers.
   */
  data: Prisma.XOR<Prisma.EventJoinAnswerUpdateManyMutationInput, Prisma.EventJoinAnswerUncheckedUpdateManyInput>
  /**
   * Filter which EventJoinAnswers to update
   */
  where?: Prisma.EventJoinAnswerWhereInput
  /**
   * Limit how many EventJoinAnswers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EventJoinAnswer upsert
 */
export type EventJoinAnswerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerInclude<ExtArgs> | null
  /**
   * The filter to search for the EventJoinAnswer to update in case it exists.
   */
  where: Prisma.EventJoinAnswerWhereUniqueInput
  /**
   * In case the EventJoinAnswer found by the `where` argument doesn't exist, create a new EventJoinAnswer with this data.
   */
  create: Prisma.XOR<Prisma.EventJoinAnswerCreateInput, Prisma.EventJoinAnswerUncheckedCreateInput>
  /**
   * In case the EventJoinAnswer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventJoinAnswerUpdateInput, Prisma.EventJoinAnswerUncheckedUpdateInput>
}

/**
 * EventJoinAnswer delete
 */
export type EventJoinAnswerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerInclude<ExtArgs> | null
  /**
   * Filter which EventJoinAnswer to delete.
   */
  where: Prisma.EventJoinAnswerWhereUniqueInput
}

/**
 * EventJoinAnswer deleteMany
 */
export type EventJoinAnswerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventJoinAnswers to delete
   */
  where?: Prisma.EventJoinAnswerWhereInput
  /**
   * Limit how many EventJoinAnswers to delete.
   */
  limit?: number
}

/**
 * EventJoinAnswer without action
 */
export type EventJoinAnswerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventJoinAnswer
   */
  select?: Prisma.EventJoinAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventJoinAnswer
   */
  omit?: Prisma.EventJoinAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventJoinAnswerInclude<ExtArgs> | null
}
