
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserPlanPeriod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserPlanPeriod
 * 
 */
export type UserPlanPeriodModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPlanPeriodPayload>

export type AggregateUserPlanPeriod = {
  _count: UserPlanPeriodCountAggregateOutputType | null
  _avg: UserPlanPeriodAvgAggregateOutputType | null
  _sum: UserPlanPeriodSumAggregateOutputType | null
  _min: UserPlanPeriodMinAggregateOutputType | null
  _max: UserPlanPeriodMaxAggregateOutputType | null
}

export type UserPlanPeriodAvgAggregateOutputType = {
  amount: number | null
}

export type UserPlanPeriodSumAggregateOutputType = {
  amount: number | null
}

export type UserPlanPeriodMinAggregateOutputType = {
  id: string | null
  userId: string | null
  plan: $Enums.SubscriptionPlan | null
  source: $Enums.UserPlanSource | null
  billingPeriod: $Enums.BillingPeriod | null
  amount: number | null
  currency: string | null
  stripeCustomerId: string | null
  stripeSubscriptionId: string | null
  stripePaymentEventId: string | null
  stripeCheckoutSessionId: string | null
  startsAt: Date | null
  endsAt: Date | null
  createdAt: Date | null
}

export type UserPlanPeriodMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  plan: $Enums.SubscriptionPlan | null
  source: $Enums.UserPlanSource | null
  billingPeriod: $Enums.BillingPeriod | null
  amount: number | null
  currency: string | null
  stripeCustomerId: string | null
  stripeSubscriptionId: string | null
  stripePaymentEventId: string | null
  stripeCheckoutSessionId: string | null
  startsAt: Date | null
  endsAt: Date | null
  createdAt: Date | null
}

export type UserPlanPeriodCountAggregateOutputType = {
  id: number
  userId: number
  plan: number
  source: number
  billingPeriod: number
  amount: number
  currency: number
  stripeCustomerId: number
  stripeSubscriptionId: number
  stripePaymentEventId: number
  stripeCheckoutSessionId: number
  startsAt: number
  endsAt: number
  createdAt: number
  _all: number
}


export type UserPlanPeriodAvgAggregateInputType = {
  amount?: true
}

export type UserPlanPeriodSumAggregateInputType = {
  amount?: true
}

export type UserPlanPeriodMinAggregateInputType = {
  id?: true
  userId?: true
  plan?: true
  source?: true
  billingPeriod?: true
  amount?: true
  currency?: true
  stripeCustomerId?: true
  stripeSubscriptionId?: true
  stripePaymentEventId?: true
  stripeCheckoutSessionId?: true
  startsAt?: true
  endsAt?: true
  createdAt?: true
}

export type UserPlanPeriodMaxAggregateInputType = {
  id?: true
  userId?: true
  plan?: true
  source?: true
  billingPeriod?: true
  amount?: true
  currency?: true
  stripeCustomerId?: true
  stripeSubscriptionId?: true
  stripePaymentEventId?: true
  stripeCheckoutSessionId?: true
  startsAt?: true
  endsAt?: true
  createdAt?: true
}

export type UserPlanPeriodCountAggregateInputType = {
  id?: true
  userId?: true
  plan?: true
  source?: true
  billingPeriod?: true
  amount?: true
  currency?: true
  stripeCustomerId?: true
  stripeSubscriptionId?: true
  stripePaymentEventId?: true
  stripeCheckoutSessionId?: true
  startsAt?: true
  endsAt?: true
  createdAt?: true
  _all?: true
}

export type UserPlanPeriodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserPlanPeriod to aggregate.
   */
  where?: Prisma.UserPlanPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPlanPeriods to fetch.
   */
  orderBy?: Prisma.UserPlanPeriodOrderByWithRelationInput | Prisma.UserPlanPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserPlanPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPlanPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPlanPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserPlanPeriods
  **/
  _count?: true | UserPlanPeriodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserPlanPeriodAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserPlanPeriodSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserPlanPeriodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserPlanPeriodMaxAggregateInputType
}

export type GetUserPlanPeriodAggregateType<T extends UserPlanPeriodAggregateArgs> = {
      [P in keyof T & keyof AggregateUserPlanPeriod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserPlanPeriod[P]>
    : Prisma.GetScalarType<T[P], AggregateUserPlanPeriod[P]>
}




export type UserPlanPeriodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserPlanPeriodWhereInput
  orderBy?: Prisma.UserPlanPeriodOrderByWithAggregationInput | Prisma.UserPlanPeriodOrderByWithAggregationInput[]
  by: Prisma.UserPlanPeriodScalarFieldEnum[] | Prisma.UserPlanPeriodScalarFieldEnum
  having?: Prisma.UserPlanPeriodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserPlanPeriodCountAggregateInputType | true
  _avg?: UserPlanPeriodAvgAggregateInputType
  _sum?: UserPlanPeriodSumAggregateInputType
  _min?: UserPlanPeriodMinAggregateInputType
  _max?: UserPlanPeriodMaxAggregateInputType
}

export type UserPlanPeriodGroupByOutputType = {
  id: string
  userId: string
  plan: $Enums.SubscriptionPlan
  source: $Enums.UserPlanSource
  billingPeriod: $Enums.BillingPeriod
  amount: number
  currency: string
  stripeCustomerId: string | null
  stripeSubscriptionId: string | null
  stripePaymentEventId: string | null
  stripeCheckoutSessionId: string | null
  startsAt: Date
  endsAt: Date
  createdAt: Date
  _count: UserPlanPeriodCountAggregateOutputType | null
  _avg: UserPlanPeriodAvgAggregateOutputType | null
  _sum: UserPlanPeriodSumAggregateOutputType | null
  _min: UserPlanPeriodMinAggregateOutputType | null
  _max: UserPlanPeriodMaxAggregateOutputType | null
}

type GetUserPlanPeriodGroupByPayload<T extends UserPlanPeriodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserPlanPeriodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserPlanPeriodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserPlanPeriodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserPlanPeriodGroupByOutputType[P]>
      }
    >
  >



export type UserPlanPeriodWhereInput = {
  AND?: Prisma.UserPlanPeriodWhereInput | Prisma.UserPlanPeriodWhereInput[]
  OR?: Prisma.UserPlanPeriodWhereInput[]
  NOT?: Prisma.UserPlanPeriodWhereInput | Prisma.UserPlanPeriodWhereInput[]
  id?: Prisma.StringFilter<"UserPlanPeriod"> | string
  userId?: Prisma.StringFilter<"UserPlanPeriod"> | string
  plan?: Prisma.EnumSubscriptionPlanFilter<"UserPlanPeriod"> | $Enums.SubscriptionPlan
  source?: Prisma.EnumUserPlanSourceFilter<"UserPlanPeriod"> | $Enums.UserPlanSource
  billingPeriod?: Prisma.EnumBillingPeriodFilter<"UserPlanPeriod"> | $Enums.BillingPeriod
  amount?: Prisma.FloatFilter<"UserPlanPeriod"> | number
  currency?: Prisma.StringFilter<"UserPlanPeriod"> | string
  stripeCustomerId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  stripeSubscriptionId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  stripePaymentEventId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  stripeCheckoutSessionId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  startsAt?: Prisma.DateTimeFilter<"UserPlanPeriod"> | Date | string
  endsAt?: Prisma.DateTimeFilter<"UserPlanPeriod"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"UserPlanPeriod"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserPlanPeriodOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  source?: Prisma.SortOrder
  billingPeriod?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeSubscriptionId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripePaymentEventId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeCheckoutSessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserPlanPeriodWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UserPlanPeriodWhereInput | Prisma.UserPlanPeriodWhereInput[]
  OR?: Prisma.UserPlanPeriodWhereInput[]
  NOT?: Prisma.UserPlanPeriodWhereInput | Prisma.UserPlanPeriodWhereInput[]
  userId?: Prisma.StringFilter<"UserPlanPeriod"> | string
  plan?: Prisma.EnumSubscriptionPlanFilter<"UserPlanPeriod"> | $Enums.SubscriptionPlan
  source?: Prisma.EnumUserPlanSourceFilter<"UserPlanPeriod"> | $Enums.UserPlanSource
  billingPeriod?: Prisma.EnumBillingPeriodFilter<"UserPlanPeriod"> | $Enums.BillingPeriod
  amount?: Prisma.FloatFilter<"UserPlanPeriod"> | number
  currency?: Prisma.StringFilter<"UserPlanPeriod"> | string
  stripeCustomerId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  stripeSubscriptionId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  stripePaymentEventId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  stripeCheckoutSessionId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  startsAt?: Prisma.DateTimeFilter<"UserPlanPeriod"> | Date | string
  endsAt?: Prisma.DateTimeFilter<"UserPlanPeriod"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"UserPlanPeriod"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type UserPlanPeriodOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  source?: Prisma.SortOrder
  billingPeriod?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeSubscriptionId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripePaymentEventId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeCheckoutSessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.UserPlanPeriodCountOrderByAggregateInput
  _avg?: Prisma.UserPlanPeriodAvgOrderByAggregateInput
  _max?: Prisma.UserPlanPeriodMaxOrderByAggregateInput
  _min?: Prisma.UserPlanPeriodMinOrderByAggregateInput
  _sum?: Prisma.UserPlanPeriodSumOrderByAggregateInput
}

export type UserPlanPeriodScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserPlanPeriodScalarWhereWithAggregatesInput | Prisma.UserPlanPeriodScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserPlanPeriodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserPlanPeriodScalarWhereWithAggregatesInput | Prisma.UserPlanPeriodScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserPlanPeriod"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UserPlanPeriod"> | string
  plan?: Prisma.EnumSubscriptionPlanWithAggregatesFilter<"UserPlanPeriod"> | $Enums.SubscriptionPlan
  source?: Prisma.EnumUserPlanSourceWithAggregatesFilter<"UserPlanPeriod"> | $Enums.UserPlanSource
  billingPeriod?: Prisma.EnumBillingPeriodWithAggregatesFilter<"UserPlanPeriod"> | $Enums.BillingPeriod
  amount?: Prisma.FloatWithAggregatesFilter<"UserPlanPeriod"> | number
  currency?: Prisma.StringWithAggregatesFilter<"UserPlanPeriod"> | string
  stripeCustomerId?: Prisma.StringNullableWithAggregatesFilter<"UserPlanPeriod"> | string | null
  stripeSubscriptionId?: Prisma.StringNullableWithAggregatesFilter<"UserPlanPeriod"> | string | null
  stripePaymentEventId?: Prisma.StringNullableWithAggregatesFilter<"UserPlanPeriod"> | string | null
  stripeCheckoutSessionId?: Prisma.StringNullableWithAggregatesFilter<"UserPlanPeriod"> | string | null
  startsAt?: Prisma.DateTimeWithAggregatesFilter<"UserPlanPeriod"> | Date | string
  endsAt?: Prisma.DateTimeWithAggregatesFilter<"UserPlanPeriod"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserPlanPeriod"> | Date | string
}

export type UserPlanPeriodCreateInput = {
  id?: string
  plan: $Enums.SubscriptionPlan
  source: $Enums.UserPlanSource
  billingPeriod: $Enums.BillingPeriod
  amount?: number
  currency?: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  startsAt: Date | string
  endsAt: Date | string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPlanPeriodsInput
}

export type UserPlanPeriodUncheckedCreateInput = {
  id?: string
  userId: string
  plan: $Enums.SubscriptionPlan
  source: $Enums.UserPlanSource
  billingPeriod: $Enums.BillingPeriod
  amount?: number
  currency?: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  startsAt: Date | string
  endsAt: Date | string
  createdAt?: Date | string
}

export type UserPlanPeriodUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumSubscriptionPlanFieldUpdateOperationsInput | $Enums.SubscriptionPlan
  source?: Prisma.EnumUserPlanSourceFieldUpdateOperationsInput | $Enums.UserPlanSource
  billingPeriod?: Prisma.EnumBillingPeriodFieldUpdateOperationsInput | $Enums.BillingPeriod
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPlanPeriodsNestedInput
}

export type UserPlanPeriodUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumSubscriptionPlanFieldUpdateOperationsInput | $Enums.SubscriptionPlan
  source?: Prisma.EnumUserPlanSourceFieldUpdateOperationsInput | $Enums.UserPlanSource
  billingPeriod?: Prisma.EnumBillingPeriodFieldUpdateOperationsInput | $Enums.BillingPeriod
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserPlanPeriodCreateManyInput = {
  id?: string
  userId: string
  plan: $Enums.SubscriptionPlan
  source: $Enums.UserPlanSource
  billingPeriod: $Enums.BillingPeriod
  amount?: number
  currency?: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  startsAt: Date | string
  endsAt: Date | string
  createdAt?: Date | string
}

export type UserPlanPeriodUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumSubscriptionPlanFieldUpdateOperationsInput | $Enums.SubscriptionPlan
  source?: Prisma.EnumUserPlanSourceFieldUpdateOperationsInput | $Enums.UserPlanSource
  billingPeriod?: Prisma.EnumBillingPeriodFieldUpdateOperationsInput | $Enums.BillingPeriod
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserPlanPeriodUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumSubscriptionPlanFieldUpdateOperationsInput | $Enums.SubscriptionPlan
  source?: Prisma.EnumUserPlanSourceFieldUpdateOperationsInput | $Enums.UserPlanSource
  billingPeriod?: Prisma.EnumBillingPeriodFieldUpdateOperationsInput | $Enums.BillingPeriod
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserPlanPeriodListRelationFilter = {
  every?: Prisma.UserPlanPeriodWhereInput
  some?: Prisma.UserPlanPeriodWhereInput
  none?: Prisma.UserPlanPeriodWhereInput
}

export type UserPlanPeriodOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserPlanPeriodCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  source?: Prisma.SortOrder
  billingPeriod?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrder
  stripeSubscriptionId?: Prisma.SortOrder
  stripePaymentEventId?: Prisma.SortOrder
  stripeCheckoutSessionId?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserPlanPeriodAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type UserPlanPeriodMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  source?: Prisma.SortOrder
  billingPeriod?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrder
  stripeSubscriptionId?: Prisma.SortOrder
  stripePaymentEventId?: Prisma.SortOrder
  stripeCheckoutSessionId?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserPlanPeriodMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  source?: Prisma.SortOrder
  billingPeriod?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrder
  stripeSubscriptionId?: Prisma.SortOrder
  stripePaymentEventId?: Prisma.SortOrder
  stripeCheckoutSessionId?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserPlanPeriodSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type UserPlanPeriodCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserPlanPeriodCreateWithoutUserInput, Prisma.UserPlanPeriodUncheckedCreateWithoutUserInput> | Prisma.UserPlanPeriodCreateWithoutUserInput[] | Prisma.UserPlanPeriodUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPlanPeriodCreateOrConnectWithoutUserInput | Prisma.UserPlanPeriodCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserPlanPeriodCreateManyUserInputEnvelope
  connect?: Prisma.UserPlanPeriodWhereUniqueInput | Prisma.UserPlanPeriodWhereUniqueInput[]
}

export type UserPlanPeriodUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserPlanPeriodCreateWithoutUserInput, Prisma.UserPlanPeriodUncheckedCreateWithoutUserInput> | Prisma.UserPlanPeriodCreateWithoutUserInput[] | Prisma.UserPlanPeriodUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPlanPeriodCreateOrConnectWithoutUserInput | Prisma.UserPlanPeriodCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserPlanPeriodCreateManyUserInputEnvelope
  connect?: Prisma.UserPlanPeriodWhereUniqueInput | Prisma.UserPlanPeriodWhereUniqueInput[]
}

export type UserPlanPeriodUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserPlanPeriodCreateWithoutUserInput, Prisma.UserPlanPeriodUncheckedCreateWithoutUserInput> | Prisma.UserPlanPeriodCreateWithoutUserInput[] | Prisma.UserPlanPeriodUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPlanPeriodCreateOrConnectWithoutUserInput | Prisma.UserPlanPeriodCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserPlanPeriodUpsertWithWhereUniqueWithoutUserInput | Prisma.UserPlanPeriodUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserPlanPeriodCreateManyUserInputEnvelope
  set?: Prisma.UserPlanPeriodWhereUniqueInput | Prisma.UserPlanPeriodWhereUniqueInput[]
  disconnect?: Prisma.UserPlanPeriodWhereUniqueInput | Prisma.UserPlanPeriodWhereUniqueInput[]
  delete?: Prisma.UserPlanPeriodWhereUniqueInput | Prisma.UserPlanPeriodWhereUniqueInput[]
  connect?: Prisma.UserPlanPeriodWhereUniqueInput | Prisma.UserPlanPeriodWhereUniqueInput[]
  update?: Prisma.UserPlanPeriodUpdateWithWhereUniqueWithoutUserInput | Prisma.UserPlanPeriodUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserPlanPeriodUpdateManyWithWhereWithoutUserInput | Prisma.UserPlanPeriodUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserPlanPeriodScalarWhereInput | Prisma.UserPlanPeriodScalarWhereInput[]
}

export type UserPlanPeriodUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserPlanPeriodCreateWithoutUserInput, Prisma.UserPlanPeriodUncheckedCreateWithoutUserInput> | Prisma.UserPlanPeriodCreateWithoutUserInput[] | Prisma.UserPlanPeriodUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPlanPeriodCreateOrConnectWithoutUserInput | Prisma.UserPlanPeriodCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserPlanPeriodUpsertWithWhereUniqueWithoutUserInput | Prisma.UserPlanPeriodUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserPlanPeriodCreateManyUserInputEnvelope
  set?: Prisma.UserPlanPeriodWhereUniqueInput | Prisma.UserPlanPeriodWhereUniqueInput[]
  disconnect?: Prisma.UserPlanPeriodWhereUniqueInput | Prisma.UserPlanPeriodWhereUniqueInput[]
  delete?: Prisma.UserPlanPeriodWhereUniqueInput | Prisma.UserPlanPeriodWhereUniqueInput[]
  connect?: Prisma.UserPlanPeriodWhereUniqueInput | Prisma.UserPlanPeriodWhereUniqueInput[]
  update?: Prisma.UserPlanPeriodUpdateWithWhereUniqueWithoutUserInput | Prisma.UserPlanPeriodUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserPlanPeriodUpdateManyWithWhereWithoutUserInput | Prisma.UserPlanPeriodUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserPlanPeriodScalarWhereInput | Prisma.UserPlanPeriodScalarWhereInput[]
}

export type EnumUserPlanSourceFieldUpdateOperationsInput = {
  set?: $Enums.UserPlanSource
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type UserPlanPeriodCreateWithoutUserInput = {
  id?: string
  plan: $Enums.SubscriptionPlan
  source: $Enums.UserPlanSource
  billingPeriod: $Enums.BillingPeriod
  amount?: number
  currency?: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  startsAt: Date | string
  endsAt: Date | string
  createdAt?: Date | string
}

export type UserPlanPeriodUncheckedCreateWithoutUserInput = {
  id?: string
  plan: $Enums.SubscriptionPlan
  source: $Enums.UserPlanSource
  billingPeriod: $Enums.BillingPeriod
  amount?: number
  currency?: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  startsAt: Date | string
  endsAt: Date | string
  createdAt?: Date | string
}

export type UserPlanPeriodCreateOrConnectWithoutUserInput = {
  where: Prisma.UserPlanPeriodWhereUniqueInput
  create: Prisma.XOR<Prisma.UserPlanPeriodCreateWithoutUserInput, Prisma.UserPlanPeriodUncheckedCreateWithoutUserInput>
}

export type UserPlanPeriodCreateManyUserInputEnvelope = {
  data: Prisma.UserPlanPeriodCreateManyUserInput | Prisma.UserPlanPeriodCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserPlanPeriodUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserPlanPeriodWhereUniqueInput
  update: Prisma.XOR<Prisma.UserPlanPeriodUpdateWithoutUserInput, Prisma.UserPlanPeriodUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserPlanPeriodCreateWithoutUserInput, Prisma.UserPlanPeriodUncheckedCreateWithoutUserInput>
}

export type UserPlanPeriodUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserPlanPeriodWhereUniqueInput
  data: Prisma.XOR<Prisma.UserPlanPeriodUpdateWithoutUserInput, Prisma.UserPlanPeriodUncheckedUpdateWithoutUserInput>
}

export type UserPlanPeriodUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserPlanPeriodScalarWhereInput
  data: Prisma.XOR<Prisma.UserPlanPeriodUpdateManyMutationInput, Prisma.UserPlanPeriodUncheckedUpdateManyWithoutUserInput>
}

export type UserPlanPeriodScalarWhereInput = {
  AND?: Prisma.UserPlanPeriodScalarWhereInput | Prisma.UserPlanPeriodScalarWhereInput[]
  OR?: Prisma.UserPlanPeriodScalarWhereInput[]
  NOT?: Prisma.UserPlanPeriodScalarWhereInput | Prisma.UserPlanPeriodScalarWhereInput[]
  id?: Prisma.StringFilter<"UserPlanPeriod"> | string
  userId?: Prisma.StringFilter<"UserPlanPeriod"> | string
  plan?: Prisma.EnumSubscriptionPlanFilter<"UserPlanPeriod"> | $Enums.SubscriptionPlan
  source?: Prisma.EnumUserPlanSourceFilter<"UserPlanPeriod"> | $Enums.UserPlanSource
  billingPeriod?: Prisma.EnumBillingPeriodFilter<"UserPlanPeriod"> | $Enums.BillingPeriod
  amount?: Prisma.FloatFilter<"UserPlanPeriod"> | number
  currency?: Prisma.StringFilter<"UserPlanPeriod"> | string
  stripeCustomerId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  stripeSubscriptionId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  stripePaymentEventId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  stripeCheckoutSessionId?: Prisma.StringNullableFilter<"UserPlanPeriod"> | string | null
  startsAt?: Prisma.DateTimeFilter<"UserPlanPeriod"> | Date | string
  endsAt?: Prisma.DateTimeFilter<"UserPlanPeriod"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"UserPlanPeriod"> | Date | string
}

export type UserPlanPeriodCreateManyUserInput = {
  id?: string
  plan: $Enums.SubscriptionPlan
  source: $Enums.UserPlanSource
  billingPeriod: $Enums.BillingPeriod
  amount?: number
  currency?: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  stripePaymentEventId?: string | null
  stripeCheckoutSessionId?: string | null
  startsAt: Date | string
  endsAt: Date | string
  createdAt?: Date | string
}

export type UserPlanPeriodUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumSubscriptionPlanFieldUpdateOperationsInput | $Enums.SubscriptionPlan
  source?: Prisma.EnumUserPlanSourceFieldUpdateOperationsInput | $Enums.UserPlanSource
  billingPeriod?: Prisma.EnumBillingPeriodFieldUpdateOperationsInput | $Enums.BillingPeriod
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserPlanPeriodUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumSubscriptionPlanFieldUpdateOperationsInput | $Enums.SubscriptionPlan
  source?: Prisma.EnumUserPlanSourceFieldUpdateOperationsInput | $Enums.UserPlanSource
  billingPeriod?: Prisma.EnumBillingPeriodFieldUpdateOperationsInput | $Enums.BillingPeriod
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserPlanPeriodUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.EnumSubscriptionPlanFieldUpdateOperationsInput | $Enums.SubscriptionPlan
  source?: Prisma.EnumUserPlanSourceFieldUpdateOperationsInput | $Enums.UserPlanSource
  billingPeriod?: Prisma.EnumBillingPeriodFieldUpdateOperationsInput | $Enums.BillingPeriod
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePaymentEventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCheckoutSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserPlanPeriodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  plan?: boolean
  source?: boolean
  billingPeriod?: boolean
  amount?: boolean
  currency?: boolean
  stripeCustomerId?: boolean
  stripeSubscriptionId?: boolean
  stripePaymentEventId?: boolean
  stripeCheckoutSessionId?: boolean
  startsAt?: boolean
  endsAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userPlanPeriod"]>

export type UserPlanPeriodSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  plan?: boolean
  source?: boolean
  billingPeriod?: boolean
  amount?: boolean
  currency?: boolean
  stripeCustomerId?: boolean
  stripeSubscriptionId?: boolean
  stripePaymentEventId?: boolean
  stripeCheckoutSessionId?: boolean
  startsAt?: boolean
  endsAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userPlanPeriod"]>

export type UserPlanPeriodSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  plan?: boolean
  source?: boolean
  billingPeriod?: boolean
  amount?: boolean
  currency?: boolean
  stripeCustomerId?: boolean
  stripeSubscriptionId?: boolean
  stripePaymentEventId?: boolean
  stripeCheckoutSessionId?: boolean
  startsAt?: boolean
  endsAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userPlanPeriod"]>

export type UserPlanPeriodSelectScalar = {
  id?: boolean
  userId?: boolean
  plan?: boolean
  source?: boolean
  billingPeriod?: boolean
  amount?: boolean
  currency?: boolean
  stripeCustomerId?: boolean
  stripeSubscriptionId?: boolean
  stripePaymentEventId?: boolean
  stripeCheckoutSessionId?: boolean
  startsAt?: boolean
  endsAt?: boolean
  createdAt?: boolean
}

export type UserPlanPeriodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "plan" | "source" | "billingPeriod" | "amount" | "currency" | "stripeCustomerId" | "stripeSubscriptionId" | "stripePaymentEventId" | "stripeCheckoutSessionId" | "startsAt" | "endsAt" | "createdAt", ExtArgs["result"]["userPlanPeriod"]>
export type UserPlanPeriodInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserPlanPeriodIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserPlanPeriodIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserPlanPeriodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserPlanPeriod"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    plan: $Enums.SubscriptionPlan
    source: $Enums.UserPlanSource
    billingPeriod: $Enums.BillingPeriod
    amount: number
    currency: string
    stripeCustomerId: string | null
    stripeSubscriptionId: string | null
    stripePaymentEventId: string | null
    stripeCheckoutSessionId: string | null
    startsAt: Date
    endsAt: Date
    createdAt: Date
  }, ExtArgs["result"]["userPlanPeriod"]>
  composites: {}
}

export type UserPlanPeriodGetPayload<S extends boolean | null | undefined | UserPlanPeriodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload, S>

export type UserPlanPeriodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserPlanPeriodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserPlanPeriodCountAggregateInputType | true
  }

export interface UserPlanPeriodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserPlanPeriod'], meta: { name: 'UserPlanPeriod' } }
  /**
   * Find zero or one UserPlanPeriod that matches the filter.
   * @param {UserPlanPeriodFindUniqueArgs} args - Arguments to find a UserPlanPeriod
   * @example
   * // Get one UserPlanPeriod
   * const userPlanPeriod = await prisma.userPlanPeriod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserPlanPeriodFindUniqueArgs>(args: Prisma.SelectSubset<T, UserPlanPeriodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserPlanPeriodClient<runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserPlanPeriod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserPlanPeriodFindUniqueOrThrowArgs} args - Arguments to find a UserPlanPeriod
   * @example
   * // Get one UserPlanPeriod
   * const userPlanPeriod = await prisma.userPlanPeriod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserPlanPeriodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserPlanPeriodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserPlanPeriodClient<runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserPlanPeriod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPlanPeriodFindFirstArgs} args - Arguments to find a UserPlanPeriod
   * @example
   * // Get one UserPlanPeriod
   * const userPlanPeriod = await prisma.userPlanPeriod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserPlanPeriodFindFirstArgs>(args?: Prisma.SelectSubset<T, UserPlanPeriodFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserPlanPeriodClient<runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserPlanPeriod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPlanPeriodFindFirstOrThrowArgs} args - Arguments to find a UserPlanPeriod
   * @example
   * // Get one UserPlanPeriod
   * const userPlanPeriod = await prisma.userPlanPeriod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserPlanPeriodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserPlanPeriodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserPlanPeriodClient<runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserPlanPeriods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPlanPeriodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserPlanPeriods
   * const userPlanPeriods = await prisma.userPlanPeriod.findMany()
   * 
   * // Get first 10 UserPlanPeriods
   * const userPlanPeriods = await prisma.userPlanPeriod.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userPlanPeriodWithIdOnly = await prisma.userPlanPeriod.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserPlanPeriodFindManyArgs>(args?: Prisma.SelectSubset<T, UserPlanPeriodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserPlanPeriod.
   * @param {UserPlanPeriodCreateArgs} args - Arguments to create a UserPlanPeriod.
   * @example
   * // Create one UserPlanPeriod
   * const UserPlanPeriod = await prisma.userPlanPeriod.create({
   *   data: {
   *     // ... data to create a UserPlanPeriod
   *   }
   * })
   * 
   */
  create<T extends UserPlanPeriodCreateArgs>(args: Prisma.SelectSubset<T, UserPlanPeriodCreateArgs<ExtArgs>>): Prisma.Prisma__UserPlanPeriodClient<runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserPlanPeriods.
   * @param {UserPlanPeriodCreateManyArgs} args - Arguments to create many UserPlanPeriods.
   * @example
   * // Create many UserPlanPeriods
   * const userPlanPeriod = await prisma.userPlanPeriod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserPlanPeriodCreateManyArgs>(args?: Prisma.SelectSubset<T, UserPlanPeriodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserPlanPeriods and returns the data saved in the database.
   * @param {UserPlanPeriodCreateManyAndReturnArgs} args - Arguments to create many UserPlanPeriods.
   * @example
   * // Create many UserPlanPeriods
   * const userPlanPeriod = await prisma.userPlanPeriod.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserPlanPeriods and only return the `id`
   * const userPlanPeriodWithIdOnly = await prisma.userPlanPeriod.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserPlanPeriodCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserPlanPeriodCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserPlanPeriod.
   * @param {UserPlanPeriodDeleteArgs} args - Arguments to delete one UserPlanPeriod.
   * @example
   * // Delete one UserPlanPeriod
   * const UserPlanPeriod = await prisma.userPlanPeriod.delete({
   *   where: {
   *     // ... filter to delete one UserPlanPeriod
   *   }
   * })
   * 
   */
  delete<T extends UserPlanPeriodDeleteArgs>(args: Prisma.SelectSubset<T, UserPlanPeriodDeleteArgs<ExtArgs>>): Prisma.Prisma__UserPlanPeriodClient<runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserPlanPeriod.
   * @param {UserPlanPeriodUpdateArgs} args - Arguments to update one UserPlanPeriod.
   * @example
   * // Update one UserPlanPeriod
   * const userPlanPeriod = await prisma.userPlanPeriod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserPlanPeriodUpdateArgs>(args: Prisma.SelectSubset<T, UserPlanPeriodUpdateArgs<ExtArgs>>): Prisma.Prisma__UserPlanPeriodClient<runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserPlanPeriods.
   * @param {UserPlanPeriodDeleteManyArgs} args - Arguments to filter UserPlanPeriods to delete.
   * @example
   * // Delete a few UserPlanPeriods
   * const { count } = await prisma.userPlanPeriod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserPlanPeriodDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserPlanPeriodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserPlanPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPlanPeriodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserPlanPeriods
   * const userPlanPeriod = await prisma.userPlanPeriod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserPlanPeriodUpdateManyArgs>(args: Prisma.SelectSubset<T, UserPlanPeriodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserPlanPeriods and returns the data updated in the database.
   * @param {UserPlanPeriodUpdateManyAndReturnArgs} args - Arguments to update many UserPlanPeriods.
   * @example
   * // Update many UserPlanPeriods
   * const userPlanPeriod = await prisma.userPlanPeriod.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserPlanPeriods and only return the `id`
   * const userPlanPeriodWithIdOnly = await prisma.userPlanPeriod.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserPlanPeriodUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserPlanPeriodUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserPlanPeriod.
   * @param {UserPlanPeriodUpsertArgs} args - Arguments to update or create a UserPlanPeriod.
   * @example
   * // Update or create a UserPlanPeriod
   * const userPlanPeriod = await prisma.userPlanPeriod.upsert({
   *   create: {
   *     // ... data to create a UserPlanPeriod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserPlanPeriod we want to update
   *   }
   * })
   */
  upsert<T extends UserPlanPeriodUpsertArgs>(args: Prisma.SelectSubset<T, UserPlanPeriodUpsertArgs<ExtArgs>>): Prisma.Prisma__UserPlanPeriodClient<runtime.Types.Result.GetResult<Prisma.$UserPlanPeriodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserPlanPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPlanPeriodCountArgs} args - Arguments to filter UserPlanPeriods to count.
   * @example
   * // Count the number of UserPlanPeriods
   * const count = await prisma.userPlanPeriod.count({
   *   where: {
   *     // ... the filter for the UserPlanPeriods we want to count
   *   }
   * })
  **/
  count<T extends UserPlanPeriodCountArgs>(
    args?: Prisma.Subset<T, UserPlanPeriodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserPlanPeriodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserPlanPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPlanPeriodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserPlanPeriodAggregateArgs>(args: Prisma.Subset<T, UserPlanPeriodAggregateArgs>): Prisma.PrismaPromise<GetUserPlanPeriodAggregateType<T>>

  /**
   * Group by UserPlanPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPlanPeriodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserPlanPeriodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserPlanPeriodGroupByArgs['orderBy'] }
      : { orderBy?: UserPlanPeriodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserPlanPeriodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserPlanPeriodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserPlanPeriod model
 */
readonly fields: UserPlanPeriodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserPlanPeriod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserPlanPeriodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserPlanPeriod model
 */
export interface UserPlanPeriodFieldRefs {
  readonly id: Prisma.FieldRef<"UserPlanPeriod", 'String'>
  readonly userId: Prisma.FieldRef<"UserPlanPeriod", 'String'>
  readonly plan: Prisma.FieldRef<"UserPlanPeriod", 'SubscriptionPlan'>
  readonly source: Prisma.FieldRef<"UserPlanPeriod", 'UserPlanSource'>
  readonly billingPeriod: Prisma.FieldRef<"UserPlanPeriod", 'BillingPeriod'>
  readonly amount: Prisma.FieldRef<"UserPlanPeriod", 'Float'>
  readonly currency: Prisma.FieldRef<"UserPlanPeriod", 'String'>
  readonly stripeCustomerId: Prisma.FieldRef<"UserPlanPeriod", 'String'>
  readonly stripeSubscriptionId: Prisma.FieldRef<"UserPlanPeriod", 'String'>
  readonly stripePaymentEventId: Prisma.FieldRef<"UserPlanPeriod", 'String'>
  readonly stripeCheckoutSessionId: Prisma.FieldRef<"UserPlanPeriod", 'String'>
  readonly startsAt: Prisma.FieldRef<"UserPlanPeriod", 'DateTime'>
  readonly endsAt: Prisma.FieldRef<"UserPlanPeriod", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"UserPlanPeriod", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserPlanPeriod findUnique
 */
export type UserPlanPeriodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodInclude<ExtArgs> | null
  /**
   * Filter, which UserPlanPeriod to fetch.
   */
  where: Prisma.UserPlanPeriodWhereUniqueInput
}

/**
 * UserPlanPeriod findUniqueOrThrow
 */
export type UserPlanPeriodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodInclude<ExtArgs> | null
  /**
   * Filter, which UserPlanPeriod to fetch.
   */
  where: Prisma.UserPlanPeriodWhereUniqueInput
}

/**
 * UserPlanPeriod findFirst
 */
export type UserPlanPeriodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodInclude<ExtArgs> | null
  /**
   * Filter, which UserPlanPeriod to fetch.
   */
  where?: Prisma.UserPlanPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPlanPeriods to fetch.
   */
  orderBy?: Prisma.UserPlanPeriodOrderByWithRelationInput | Prisma.UserPlanPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserPlanPeriods.
   */
  cursor?: Prisma.UserPlanPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPlanPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPlanPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserPlanPeriods.
   */
  distinct?: Prisma.UserPlanPeriodScalarFieldEnum | Prisma.UserPlanPeriodScalarFieldEnum[]
}

/**
 * UserPlanPeriod findFirstOrThrow
 */
export type UserPlanPeriodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodInclude<ExtArgs> | null
  /**
   * Filter, which UserPlanPeriod to fetch.
   */
  where?: Prisma.UserPlanPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPlanPeriods to fetch.
   */
  orderBy?: Prisma.UserPlanPeriodOrderByWithRelationInput | Prisma.UserPlanPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserPlanPeriods.
   */
  cursor?: Prisma.UserPlanPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPlanPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPlanPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserPlanPeriods.
   */
  distinct?: Prisma.UserPlanPeriodScalarFieldEnum | Prisma.UserPlanPeriodScalarFieldEnum[]
}

/**
 * UserPlanPeriod findMany
 */
export type UserPlanPeriodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodInclude<ExtArgs> | null
  /**
   * Filter, which UserPlanPeriods to fetch.
   */
  where?: Prisma.UserPlanPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPlanPeriods to fetch.
   */
  orderBy?: Prisma.UserPlanPeriodOrderByWithRelationInput | Prisma.UserPlanPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserPlanPeriods.
   */
  cursor?: Prisma.UserPlanPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPlanPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPlanPeriods.
   */
  skip?: number
  distinct?: Prisma.UserPlanPeriodScalarFieldEnum | Prisma.UserPlanPeriodScalarFieldEnum[]
}

/**
 * UserPlanPeriod create
 */
export type UserPlanPeriodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodInclude<ExtArgs> | null
  /**
   * The data needed to create a UserPlanPeriod.
   */
  data: Prisma.XOR<Prisma.UserPlanPeriodCreateInput, Prisma.UserPlanPeriodUncheckedCreateInput>
}

/**
 * UserPlanPeriod createMany
 */
export type UserPlanPeriodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserPlanPeriods.
   */
  data: Prisma.UserPlanPeriodCreateManyInput | Prisma.UserPlanPeriodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserPlanPeriod createManyAndReturn
 */
export type UserPlanPeriodCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * The data used to create many UserPlanPeriods.
   */
  data: Prisma.UserPlanPeriodCreateManyInput | Prisma.UserPlanPeriodCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserPlanPeriod update
 */
export type UserPlanPeriodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodInclude<ExtArgs> | null
  /**
   * The data needed to update a UserPlanPeriod.
   */
  data: Prisma.XOR<Prisma.UserPlanPeriodUpdateInput, Prisma.UserPlanPeriodUncheckedUpdateInput>
  /**
   * Choose, which UserPlanPeriod to update.
   */
  where: Prisma.UserPlanPeriodWhereUniqueInput
}

/**
 * UserPlanPeriod updateMany
 */
export type UserPlanPeriodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserPlanPeriods.
   */
  data: Prisma.XOR<Prisma.UserPlanPeriodUpdateManyMutationInput, Prisma.UserPlanPeriodUncheckedUpdateManyInput>
  /**
   * Filter which UserPlanPeriods to update
   */
  where?: Prisma.UserPlanPeriodWhereInput
  /**
   * Limit how many UserPlanPeriods to update.
   */
  limit?: number
}

/**
 * UserPlanPeriod updateManyAndReturn
 */
export type UserPlanPeriodUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * The data used to update UserPlanPeriods.
   */
  data: Prisma.XOR<Prisma.UserPlanPeriodUpdateManyMutationInput, Prisma.UserPlanPeriodUncheckedUpdateManyInput>
  /**
   * Filter which UserPlanPeriods to update
   */
  where?: Prisma.UserPlanPeriodWhereInput
  /**
   * Limit how many UserPlanPeriods to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserPlanPeriod upsert
 */
export type UserPlanPeriodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodInclude<ExtArgs> | null
  /**
   * The filter to search for the UserPlanPeriod to update in case it exists.
   */
  where: Prisma.UserPlanPeriodWhereUniqueInput
  /**
   * In case the UserPlanPeriod found by the `where` argument doesn't exist, create a new UserPlanPeriod with this data.
   */
  create: Prisma.XOR<Prisma.UserPlanPeriodCreateInput, Prisma.UserPlanPeriodUncheckedCreateInput>
  /**
   * In case the UserPlanPeriod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserPlanPeriodUpdateInput, Prisma.UserPlanPeriodUncheckedUpdateInput>
}

/**
 * UserPlanPeriod delete
 */
export type UserPlanPeriodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodInclude<ExtArgs> | null
  /**
   * Filter which UserPlanPeriod to delete.
   */
  where: Prisma.UserPlanPeriodWhereUniqueInput
}

/**
 * UserPlanPeriod deleteMany
 */
export type UserPlanPeriodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserPlanPeriods to delete
   */
  where?: Prisma.UserPlanPeriodWhereInput
  /**
   * Limit how many UserPlanPeriods to delete.
   */
  limit?: number
}

/**
 * UserPlanPeriod without action
 */
export type UserPlanPeriodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPlanPeriod
   */
  select?: Prisma.UserPlanPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPlanPeriod
   */
  omit?: Prisma.UserPlanPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPlanPeriodInclude<ExtArgs> | null
}
