# =============================================================================
# Tempo Configuration - Distributed Tracing Backend
# =============================================================================
#
# Tempo stores and queries distributed traces.
# This configuration is optimized for local development with:
#   - Local filesystem storage
#   - Short retention (1h for dev)
#   - Search enabled
#
# =============================================================================

# Server configuration
server:
  http_listen_port: 3200
  grpc_listen_port: 9095
  log_level: warn

# Query configuration
query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09

# Distributor configuration
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

# Ingester configuration
ingester:
  max_block_duration: 5m
  max_block_bytes: 10485760 # 10MB
  flush_check_period: 10s
  trace_idle_period: 10s
  complete_block_timeout: 15m

# Compactor configuration
compactor:
  compaction:
    block_retention: 1h

# Storage configuration
storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

# Overrides configuration (new format)
overrides:
  defaults:
    # Maximum duration for trace search queries
    max_search_duration: 1h

# Metrics generator - Generate metrics from spans (complementary to OTel Collector)
metrics_generator:
  registry:
    external_labels:
      source: tempo
      env: dev
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces
  processor:
    # Span metrics - request/duration/error metrics derived from spans
    span_metrics:
      enable_target_info: true
      dimensions:
        - service.name
        - http.method
        - http.status_code
        - graphql.operation.type
    # Service graphs - visualize service dependencies
    service_graphs:
      enable_client_server_prefix: true
      dimensions:
        - service.name
