
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Visibility = {
  PUBLIC: 'PUBLIC',
  HIDDEN: 'HIDDEN'
} as const

export type Visibility = (typeof Visibility)[keyof typeof Visibility]


export const AddressVisibility = {
  PUBLIC: 'PUBLIC',
  AFTER_JOIN: 'AFTER_JOIN',
  HIDDEN: 'HIDDEN'
} as const

export type AddressVisibility = (typeof AddressVisibility)[keyof typeof AddressVisibility]


export const MembersVisibility = {
  PUBLIC: 'PUBLIC',
  AFTER_JOIN: 'AFTER_JOIN',
  HIDDEN: 'HIDDEN'
} as const

export type MembersVisibility = (typeof MembersVisibility)[keyof typeof MembersVisibility]


export const JoinMode = {
  OPEN: 'OPEN',
  REQUEST: 'REQUEST',
  INVITE_ONLY: 'INVITE_ONLY'
} as const

export type JoinMode = (typeof JoinMode)[keyof typeof JoinMode]


export const Mode = {
  ONE_TO_ONE: 'ONE_TO_ONE',
  GROUP: 'GROUP',
  CUSTOM: 'CUSTOM'
} as const

export type Mode = (typeof Mode)[keyof typeof Mode]


export const MeetingKind = {
  ONSITE: 'ONSITE',
  ONLINE: 'ONLINE',
  HYBRID: 'HYBRID'
} as const

export type MeetingKind = (typeof MeetingKind)[keyof typeof MeetingKind]


export const Role = {
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  USER: 'USER'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const Level = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED'
} as const

export type Level = (typeof Level)[keyof typeof Level]


export const EventMemberRole = {
  OWNER: 'OWNER',
  MODERATOR: 'MODERATOR',
  PARTICIPANT: 'PARTICIPANT'
} as const

export type EventMemberRole = (typeof EventMemberRole)[keyof typeof EventMemberRole]


export const EventMemberStatus = {
  JOINED: 'JOINED',
  PENDING: 'PENDING',
  INVITED: 'INVITED',
  REJECTED: 'REJECTED',
  BANNED: 'BANNED',
  LEFT: 'LEFT',
  KICKED: 'KICKED',
  CANCELLED: 'CANCELLED',
  WAITLIST: 'WAITLIST'
} as const

export type EventMemberStatus = (typeof EventMemberStatus)[keyof typeof EventMemberStatus]


export const NotificationKind = {
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_CANCELED: 'EVENT_CANCELED',
  EVENT_DELETED: 'EVENT_DELETED',
  EVENT_INVITE: 'EVENT_INVITE',
  EVENT_INVITE_ACCEPTED: 'EVENT_INVITE_ACCEPTED',
  EVENT_MEMBERSHIP_APPROVED: 'EVENT_MEMBERSHIP_APPROVED',
  EVENT_MEMBERSHIP_REJECTED: 'EVENT_MEMBERSHIP_REJECTED',
  EVENT_MEMBER_KICKED: 'EVENT_MEMBER_KICKED',
  EVENT_MEMBER_ROLE_CHANGED: 'EVENT_MEMBER_ROLE_CHANGED',
  JOIN_REQUEST: 'JOIN_REQUEST',
  BANNED: 'BANNED',
  UNBANNED: 'UNBANNED',
  WAITLIST_JOINED: 'WAITLIST_JOINED',
  WAITLIST_PROMOTED: 'WAITLIST_PROMOTED',
  EVENT_REVIEW_RECEIVED: 'EVENT_REVIEW_RECEIVED',
  EVENT_FEEDBACK_RECEIVED: 'EVENT_FEEDBACK_RECEIVED',
  EVENT_FEEDBACK_REQUEST: 'EVENT_FEEDBACK_REQUEST',
  REVIEW_HIDDEN: 'REVIEW_HIDDEN',
  EVENT_COMMENT_ADDED: 'EVENT_COMMENT_ADDED',
  COMMENT_REPLY: 'COMMENT_REPLY',
  COMMENT_HIDDEN: 'COMMENT_HIDDEN',
  NEW_MESSAGE: 'NEW_MESSAGE',
  NEW_COMMENT: 'NEW_COMMENT',
  NEW_REVIEW: 'NEW_REVIEW',
  EVENT_CHAT_MESSAGE: 'EVENT_CHAT_MESSAGE',
  CHECKIN_CONFIRMED: 'CHECKIN_CONFIRMED',
  CHECKIN_REJECTED: 'CHECKIN_REJECTED',
  CHECKIN_BLOCKED: 'CHECKIN_BLOCKED',
  CHECKIN_UNBLOCKED: 'CHECKIN_UNBLOCKED',
  EVENT_REMINDER: 'EVENT_REMINDER',
  SYSTEM: 'SYSTEM'
} as const

export type NotificationKind = (typeof NotificationKind)[keyof typeof NotificationKind]


export const NotificationEntity = {
  EVENT: 'EVENT',
  MESSAGE: 'MESSAGE',
  PAYMENT: 'PAYMENT',
  INVOICE: 'INVOICE',
  USER: 'USER',
  REVIEW: 'REVIEW',
  SYSTEM: 'SYSTEM',
  OTHER: 'OTHER'
} as const

export type NotificationEntity = (typeof NotificationEntity)[keyof typeof NotificationEntity]


export const SponsorshipStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELED: 'CANCELED'
} as const

export type SponsorshipStatus = (typeof SponsorshipStatus)[keyof typeof SponsorshipStatus]


export const SubscriptionPlan = {
  PLUS: 'PLUS',
  PRO: 'PRO'
} as const

export type SubscriptionPlan = (typeof SubscriptionPlan)[keyof typeof SubscriptionPlan]


export const UserPlanSource = {
  SUBSCRIPTION: 'SUBSCRIPTION',
  ONE_OFF: 'ONE_OFF'
} as const

export type UserPlanSource = (typeof UserPlanSource)[keyof typeof UserPlanSource]


export const BillingPeriod = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY'
} as const

export type BillingPeriod = (typeof BillingPeriod)[keyof typeof BillingPeriod]


export const SubscriptionStatus = {
  INCOMPLETE: 'INCOMPLETE',
  TRIALING: 'TRIALING',
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  CANCELED: 'CANCELED',
  UNPAID: 'UNPAID',
  PAUSED: 'PAUSED'
} as const

export type SubscriptionStatus = (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus]


export const EventPlan = {
  FREE: 'FREE',
  PLUS: 'PLUS',
  PRO: 'PRO'
} as const

export type EventPlan = (typeof EventPlan)[keyof typeof EventPlan]


export const PublicationStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  SCHEDULED: 'SCHEDULED'
} as const

export type PublicationStatus = (typeof PublicationStatus)[keyof typeof PublicationStatus]


export const CheckinMethod = {
  SELF_MANUAL: 'SELF_MANUAL',
  MODERATOR_PANEL: 'MODERATOR_PANEL',
  EVENT_QR: 'EVENT_QR',
  USER_QR: 'USER_QR'
} as const

export type CheckinMethod = (typeof CheckinMethod)[keyof typeof CheckinMethod]


export const CheckinAction = {
  CHECK_IN: 'CHECK_IN',
  UNCHECK: 'UNCHECK',
  REJECT: 'REJECT',
  BLOCK_ALL: 'BLOCK_ALL',
  UNBLOCK_ALL: 'UNBLOCK_ALL',
  BLOCK_METHOD: 'BLOCK_METHOD',
  UNBLOCK_METHOD: 'UNBLOCK_METHOD',
  QR_TOKEN_ROTATED: 'QR_TOKEN_ROTATED',
  METHODS_CHANGED: 'METHODS_CHANGED',
  ATTEMPT_DENIED: 'ATTEMPT_DENIED'
} as const

export type CheckinAction = (typeof CheckinAction)[keyof typeof CheckinAction]


export const CheckinSource = {
  USER: 'USER',
  MODERATOR: 'MODERATOR',
  SYSTEM: 'SYSTEM'
} as const

export type CheckinSource = (typeof CheckinSource)[keyof typeof CheckinSource]


export const CheckinResult = {
  SUCCESS: 'SUCCESS',
  DENIED: 'DENIED',
  NOOP: 'NOOP'
} as const

export type CheckinResult = (typeof CheckinResult)[keyof typeof CheckinResult]


export const MemberEvent = {
  JOIN: 'JOIN',
  REQUEST: 'REQUEST',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  LEAVE: 'LEAVE',
  KICK: 'KICK',
  BAN: 'BAN',
  UNBAN: 'UNBAN',
  INVITE: 'INVITE',
  ACCEPT_INVITE: 'ACCEPT_INVITE',
  CANCEL_REQUEST: 'CANCEL_REQUEST',
  WAITLIST: 'WAITLIST',
  WAITLIST_LEAVE: 'WAITLIST_LEAVE',
  WAITLIST_PROMOTE: 'WAITLIST_PROMOTE'
} as const

export type MemberEvent = (typeof MemberEvent)[keyof typeof MemberEvent]


export const JoinQuestionType = {
  TEXT: 'TEXT',
  SINGLE_CHOICE: 'SINGLE_CHOICE',
  MULTI_CHOICE: 'MULTI_CHOICE'
} as const

export type JoinQuestionType = (typeof JoinQuestionType)[keyof typeof JoinQuestionType]


export const FeedbackQuestionType = {
  TEXT: 'TEXT',
  SINGLE_CHOICE: 'SINGLE_CHOICE',
  MULTI_CHOICE: 'MULTI_CHOICE'
} as const

export type FeedbackQuestionType = (typeof FeedbackQuestionType)[keyof typeof FeedbackQuestionType]


export const ReportEntity = {
  EVENT: 'EVENT',
  COMMENT: 'COMMENT',
  REVIEW: 'REVIEW',
  USER: 'USER',
  MESSAGE: 'MESSAGE',
  CHAT: 'CHAT'
} as const

export type ReportEntity = (typeof ReportEntity)[keyof typeof ReportEntity]


export const AgendaHostKind = {
  USER: 'USER',
  MANUAL: 'MANUAL'
} as const

export type AgendaHostKind = (typeof AgendaHostKind)[keyof typeof AgendaHostKind]


export const AuditScope = {
  EVENT: 'EVENT',
  PUBLICATION: 'PUBLICATION',
  MEMBER: 'MEMBER',
  MODERATION: 'MODERATION',
  CHECKIN: 'CHECKIN',
  INVITE_LINK: 'INVITE_LINK',
  COMMENT: 'COMMENT',
  REVIEW: 'REVIEW',
  AGENDA: 'AGENDA',
  FAQ: 'FAQ',
  BILLING: 'BILLING',
  SYSTEM: 'SYSTEM'
} as const

export type AuditScope = (typeof AuditScope)[keyof typeof AuditScope]


export const AuditAction = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  PUBLISH: 'PUBLISH',
  UNPUBLISH: 'UNPUBLISH',
  SCHEDULE: 'SCHEDULE',
  CANCEL: 'CANCEL',
  STATUS_CHANGE: 'STATUS_CHANGE',
  ROLE_CHANGE: 'ROLE_CHANGE',
  INVITE: 'INVITE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  KICK: 'KICK',
  BAN: 'BAN',
  UNBAN: 'UNBAN',
  LEAVE: 'LEAVE',
  CONFIG_CHANGE: 'CONFIG_CHANGE',
  HIDE: 'HIDE',
  UNHIDE: 'UNHIDE',
  WAITLIST: 'WAITLIST',
  WAITLIST_LEAVE: 'WAITLIST_LEAVE',
  WAITLIST_PROMOTE: 'WAITLIST_PROMOTE'
} as const

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction]


export const AuditActorType = {
  USER: 'USER',
  SYSTEM: 'SYSTEM',
  INTEGRATION: 'INTEGRATION'
} as const

export type AuditActorType = (typeof AuditActorType)[keyof typeof AuditActorType]
